### PR TITLE
Add support for models.ini

### PR DESCRIPTION
**Pull request by brosenberg42**
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/53)

### CODE REVIEW

**Comment by jrobble** [comment]
Reviewed 37 of 37 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[cpp/DarknetDetection/plugin-files/descriptor/descriptor.json, line 167 at r1](https://beta.reviewable.io/reviews/openmpf/openmpf-components/53#-L8IxVa39KU350vfWd7T:-L8IxVa39KU350vfWd7U:b-7s3ocq) ([raw file](https://github.com/openmpf/openmpf-components/blob/667252827431e5c79e648bcef4f35e42aa1e324a/cpp/DarknetDetection/plugin-files/descriptor/descriptor.json#L167)):*
Use this for the description:

> Enables preprocessor mode. If enabled, and multiple Darknet detections in a frame share the same classification, then those are merged into a single detection where the region corresponds to the superset region that encapsulates all of the original detections, and the confidence value is the probability that at least one of the original detections is a true positive. If disabled, multiple Darknet detections in a frame are not merged together.

---

*[cpp/DarknetDetection/plugin-files/models/models.ini, line 2 at r1](https://beta.reviewable.io/reviews/openmpf/openmpf-components/53#-L8J-Qc5-aKf1AFI3QYa:-L8J-Qc5-aKf1AFI3QYb:b-7o5iw5) ([raw file](https://github.com/openmpf/openmpf-components/blob/667252827431e5c79e648bcef4f35e42aa1e324a/cpp/DarknetDetection/plugin-files/models/models.ini#L2)):*
> ```INI
> [tiny yolo]
> network_config=tiny-yolo.cfg
> ```

Also drop comments for the "network_config" and "names" stating that the files are included in the component source code. 

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/openmpf/openmpf-components/53)*

**Comment by jrobble** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[cpp/DarknetDetection/plugin-files/models/models.ini, line 2 at r1](https://beta.reviewable.io/reviews/openmpf/openmpf-components/53#-L8J-Qc5-aKf1AFI3QYa:-L8J941JEXI_yghSXjNz:bjcg8zj) ([raw file](https://github.com/openmpf/openmpf-components/blob/667252827431e5c79e648bcef4f35e42aa1e324a/cpp/DarknetDetection/plugin-files/models/models.ini#L2)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Also drop comments for the "network_config" and "names" stating that the files are included in the component source code. 
</blockquote></details>

Also, update the "weights" comment to state that it's also included. Reading the comment below, it's not clear if I should download it or not.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/openmpf/openmpf-components/53)*

**Comment by jrobble** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[cpp/DarknetDetection/DarknetDetection.cpp, line 116 at r2](https://beta.reviewable.io/reviews/openmpf/openmpf-components/53#-L8J9tSyDfbN8-fTQsqx:-L8J9tSyDfbN8-fTQsqy:b-b7f4ui) ([raw file](https://github.com/openmpf/openmpf-components/blob/119e8ce261c10deb655465e8de282ae30f5f7474/cpp/DarknetDetection/DarknetDetection.cpp#L116)):*
This error is a bit redundant: 

> Failed to load model due to: Failed to load model because a required file was not present. Expected a file to exist at either "/opt/mpf/share/models//DarknetDetection/tiny-yolo.weights" or "/home/mpf/git/openmpf-projects/openmpf/trunk/install/bin/../plugins/DarknetDetection/models/tiny-yolo.weights".

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/openmpf/openmpf-components/53)*

**Comment by brosenberg42** [comment]
Review status: 19 of 22 files reviewed at latest revision, 3 unresolved discussions.

---

*[cpp/DarknetDetection/DarknetDetection.cpp, line 116 at r2](https://reviewable.io:443/reviews/openmpf/openmpf-components/53#-L8J9tSyDfbN8-fTQsqx:-L8JDBVU5eNe7CzSq6XU:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/119e8ce261c10deb655465e8de282ae30f5f7474/cpp/DarknetDetection/DarknetDetection.cpp#L116)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

This error is a bit redundant: 

> Failed to load model due to: Failed to load model because a required file was not present. Expected a file to exist at either "/opt/mpf/share/models//DarknetDetection/tiny-yolo.weights" or "/home/mpf/git/openmpf-projects/openmpf/trunk/install/bin/../plugins/DarknetDetection/models/tiny-yolo.weights".
</blockquote></details>

Done.

---

*[cpp/DarknetDetection/plugin-files/descriptor/descriptor.json, line 167 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-components/53#-L8IxVa39KU350vfWd7T:-L8JDCvms0OWMXPOFks4:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/667252827431e5c79e648bcef4f35e42aa1e324a/cpp/DarknetDetection/plugin-files/descriptor/descriptor.json#L167)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Use this for the description:

> Enables preprocessor mode. If enabled, and multiple Darknet detections in a frame share the same classification, then those are merged into a single detection where the region corresponds to the superset region that encapsulates all of the original detections, and the confidence value is the probability that at least one of the original detections is a true positive. If disabled, multiple Darknet detections in a frame are not merged together.

</blockquote></details>

Done.

---

*[cpp/DarknetDetection/plugin-files/models/models.ini, line 2 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-components/53#-L8J-Qc5-aKf1AFI3QYa:-L8JDIDv01WSNlq0UMFC:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/667252827431e5c79e648bcef4f35e42aa1e324a/cpp/DarknetDetection/plugin-files/models/models.ini#L2)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Also, update the "weights" comment to state that it's also included. Reading the comment below, it's not clear if I should download it or not.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-components/53)*

**Comment by jrobble** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-components/53)*

**Pull request merged**
