### PR TITLE
Add USE_KEY_FRAMES property to descriptors

### PR DESCRIPTION
**Pull request by brosenberg42**
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/30)

### CODE REVIEW

**Comment by jrobble** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[cpp/DlibFaceDetection/plugin-files/descriptor/descriptor.json, line 33 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-components/30#-KvXm_IvEd_zhoGl3iVV:-KvXm_IvEd_zhoGl3iVW:bicl8bc) ([raw file](https://github.com/openmpf/openmpf-components/blob/1d178d055fe56fa9c25ab5eac2f408a40ac62086/cpp/DlibFaceDetection/plugin-files/descriptor/descriptor.json#L33)):*
> ```JSON
>         {
>           "name": "USE_KEY_FRAMES",
>           "description": "When true the component will only look at key frames (I-frames) from the input video",
> ```

Please end description in period. 

Also, please move this property under FEED_FORWARD_TOP_CONFIDENCE_COUNT and above FRAME_INTERVAL. That makes more sense because the order of precedence is FF, USE_KEY_FRAMES, and then FRAME_INTERVAL, as implemented in MPFVideoCapture.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-components/30)*

**Comment by jrobble** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-components/30)*

**Comment by brosenberg42** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[cpp/DlibFaceDetection/plugin-files/descriptor/descriptor.json, line 33 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-components/30#-KvXm_IvEd_zhoGl3iVV:-KvY6SO4Z613VwzyhALg:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/1d178d055fe56fa9c25ab5eac2f408a40ac62086/cpp/DlibFaceDetection/plugin-files/descriptor/descriptor.json#L33)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Please end description in period. 

Also, please move this property under FEED_FORWARD_TOP_CONFIDENCE_COUNT and above FRAME_INTERVAL. That makes more sense because the order of precedence is FF, USE_KEY_FRAMES, and then FRAME_INTERVAL, as implemented in MPFVideoCapture.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-components/30)*

**Comment by jrobble** [comment]
*[cpp/DlibFaceDetection/plugin-files/descriptor/descriptor.json, line 33 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-components/30#-KvXm_IvEd_zhoGl3iVV:-KvYUbIn4iLdbgnRjZCA:b-oqffm5) ([raw file](https://github.com/openmpf/openmpf-components/blob/1d178d055fe56fa9c25ab5eac2f408a40ac62086/cpp/DlibFaceDetection/plugin-files/descriptor/descriptor.json#L33)):*
I hate to nitpick, but:

> Please end description in period.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-components/30)*

**Comment by brosenberg42** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[cpp/DlibFaceDetection/plugin-files/descriptor/descriptor.json, line 33 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-components/30#-KvXm_IvEd_zhoGl3iVV:-KvZ6HRYVjchiYTOvAYS:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/1d178d055fe56fa9c25ab5eac2f408a40ac62086/cpp/DlibFaceDetection/plugin-files/descriptor/descriptor.json#L33)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

I hate to nitpick, but:

> Please end description in period.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-components/30)*

**Comment by jrobble** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-components/30)*

**Pull request merged**
