### PR TITLE
Keyword tagging

### PR DESCRIPTION
**Pull request by mcrensh**
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/133)

### CODE REVIEW

**Comment by jrobble** [comment]
___
*[cpp/TesseractOCRTextDetection/test/test_tesseract_ocr_detection.cpp, line 254 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/133#-M2-z3wf0dfwIihkz209:-M2-z3wf0dfwIihkz20A:baijxbr) ([raw file](https://github.com/openmpf/openmpf-components/blob/588c931546c7f5fa09c92176f10b1000a49c65ec/cpp/TesseractOCRTextDetection/test/test_tesseract_ocr_detection.cpp#L254)):*
> ```cpp
> }
> 
> TEST(TESSERACTOCR, MissingLanguagesTest) {
> ```

You removed a lot of tests from this file. Was that just for debug reasons? I think all the tests, with the exception of ` TaggingTest` should remain.

**Comment by mcrensh** [comment]
___
*[cpp/KeywordTagging/CMakeLists.txt, line 8 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/133#-M0y8Jr37eRfon73sZ-u:-M6ohPkb7Wewb66GiwRW:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/7df97cf690f04f4d0babd0a345ec7ec367c9fed3/cpp/KeywordTagging/CMakeLists.txt#L8)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Please update the copyright in your new code files to 2020. See this header block and the one below.
</blockquote></details>

Done.

**Review by hhuangMITRE — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/133)* status: 3 of 41 files reviewed, 16 unresolved discussions (waiting on @hhuangMITRE, @jrobble, and @mcrensh)

___
*[java/TikaTextDetection/plugin-files/descriptor/descriptor.json, line 42 at r9](https://reviewable.io/reviews/openmpf/openmpf-components/133#-MGRO4VM9NY2UXtnT0df:-MGRO4VM9NY2UXtnT0dg:b-lpjhq2) ([raw file](https://github.com/openmpf/openmpf-components/blob/72618de35e008585551610cf31805cc3436e7354/java/TikaTextDetection/plugin-files/descriptor/descriptor.json#L42)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
>   {
>           "name": "FULL_REGEX_SEARCH",
>           "description": "Toggles REGEX search to include all matching trigger words associated with the regex patterns for each tag. When disabled, only the first instance of the first matching trigger word for each tag category is included.",
>           "type": "BOOLEAN",
>           "defaultValue": "true"
>         },
> ```
</details>


I'm leaving a note here that this option is no longer used and should be removed. 
___
*[java/TikaTextDetection/src/main/java/org/mitre/mpf/detection/tika/TikaTextDetectionComponent.java, line 28 at r9](https://reviewable.io/reviews/openmpf/openmpf-components/133#-MGRMJF01nb5tc_rissa:-MGRMJF14KFpNYZdUmYw:bpql6g6) ([raw file](https://github.com/openmpf/openmpf-components/blob/72618de35e008585551610cf31805cc3436e7354/java/TikaTextDetection/src/main/java/org/mitre/mpf/detection/tika/TikaTextDetectionComponent.java#L28)):*
> ```Java
> 
> package org.mitre.mpf.detection.tika;
> ```

Looks good. The regex text tagging has been removed. 

The`text-tags.json` file in this component can now be removed. I can remove in a follow up after I test this component further alongside the AzureOCR component. I'm leaving a reminder here for now.
___
*[java/TikaTextDetection/src/test/java/org/mitre/mpf/detection/tika/TestTikaTextDetectionComponent.java, line 68 at r9](https://reviewable.io/reviews/openmpf/openmpf-components/133#-MGROvtw8cQ-7z-tpFd1:-MGROvtw8cQ-7z-tpFd2:b-umzhzl) ([raw file](https://github.com/openmpf/openmpf-components/blob/72618de35e008585551610cf31805cc3436e7354/java/TikaTextDetection/src/test/java/org/mitre/mpf/detection/tika/TestTikaTextDetectionComponent.java#L68)):*
> ```Java
>     public void testGetDetectionsGeneric() throws MPFComponentDetectionError {
>         String mediaPath = this.getClass().getResource("/data/test-tika-detection.pptx").getPath();
> ```

Keyword tagging tests have been removed and I've double checked the component output vs. original output in WFM. 

Detected text tags match, and it also appears KeywordTagging has cleaned up excess whitespace found by TikaTextDetection, mostly extra newlines. I recall this filtering was done because in the OCR component, extra white space was often found all over the results, and we had to make sure that the text was cleared of that by default. Since we're only trimming down white space, I think this filtering is fine. 

Just in case, I'll leave a note reminding myself to ask if we should also have KeywordTagging clean up text picked up in AzureOCR, TikaText, and other text detection components by default. 

In the meantime, I'm reviewing the AzureOCR component changes as well.

**Review by hhuangMITRE — COMMENTED** [review]
I reviewed and tested Keyword text-tagging with Tesseract, TikaTextDetection, and AzureOCRTextDetection. 
Looks good. The text-tagger in AzureOCRTextDetection did not have `TRIGGER_WORD`results before, so swapping to KeywordTagger added that detection info.

I've also made two changes to the KeywordTagging component during testing. I've placed in a Dockerfile for the KeywordTagger so I could test it in an MPF docker build and also removed the `TAGGING_FILE` job property from the component since it is no longer needed. Please update your local version to match and let me know if you have questions with these changes.

@mcrensh to ensure we include keyword-tagging with the other components in a docker build (also for Jenkins docker build tests), we will need to update the [docker-compose.components.yml](https://github.com/openmpf/openmpf-docker/blob/master/docker-compose.components.yml). This will be done in a separate PR.

Basically, in the openmpf/openmpf-docker branch, we will need to submit a new keyword-tagging PR, with the docker-compose.components.yml file updated with the keyword-tagger component below:

```
  keyword-tagger:
    <<: *detection-component-base
    image: ${REGISTRY}openmpf_keyword_tagging:${TAG}
    build: ${OPENMPF_PROJECTS_PATH}/openmpf-components/cpp/KeywordTagging

```

Afterwards, we can run a docker build on Jenkins with the openmpf-components and openmpf-docker branches updated to these two PRs. Let me know if you'd like to try out the docker build and we can meet up to discuss the steps to get that running. 

I'm currently having trouble getting access to the AzureSpeechDetection service, so I might need someone who can access the Azure Cognitive Speech Services to test out keyword tagging on it. Otherwise, everything else looks good. 

> Reviewed 1 of 10 files at r9.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/133#-:-MGoYqtHEFfRFzaY1NrT:b3wppzo)* status: 4 of 42 files reviewed, 16 unresolved discussions (waiting on @hhuangMITRE, @jrobble, and @mcrensh)

___
*[cpp/KeywordTagging/Dockerfile, line 26 at r10](https://reviewable.io/reviews/openmpf/openmpf-components/133#-MGoY0sG5OmYUjEjfH_f:-MGoY0sH5BkH5E_1S8d2:b-xb2tah) ([raw file](https://github.com/openmpf/openmpf-components/blob/c88ebec07e9bbf3cab01b34f3b41d90c28342aa6/cpp/KeywordTagging/Dockerfile#L26)):*
> ```Dockerfile
> # limitations under the License.                                            #
> #############################################################################
> ```

I wanted to try out the Docker build while testing with AzureOCR Text Detection, so I added this file in as well. Please look over and let me know if you have any questions. 
___
*[python/AzureOcrTextDetection/plugin-files/descriptor/descriptor.json, line 54 at r9](https://reviewable.io/reviews/openmpf/openmpf-components/133#-MGo92kmByVn2yI6vjIn:-MGo92knDxbkZFkMvNub:b-22sm58) ([raw file](https://github.com/openmpf/openmpf-components/blob/72618de35e008585551610cf31805cc3436e7354/python/AzureOcrTextDetection/plugin-files/descriptor/descriptor.json#L54)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
>    {
>           "name": "TAGGING_FILE",
>           "description": "Name of a JSON file that describes a tag hierarchy to be used on the full text returned from Azure OCR. Will default to the plugin's acs_ocr_component directory unless an alternate path to tagging file is specified (i.e. `$MPF_HOME/.../text-tags.json`).",
>           "type": "STRING",
>           "defaultValue": "text-tags.json"
>         }
> ```
</details>


Leaving a note here that this is no longer needed after removing text-tagging from this component.

UPDATE: While adding in the KeywordTagging Dockerfile, I removed this property as well.

**Comment by mcrensh** [comment]
___
*[cpp/KeywordTagging/plugin-files/descriptor/descriptor.json, line 22 at r6](https://reviewable.io/reviews/openmpf/openmpf-components/133#-MEZlbFQ6-FEl-YFTNHG:-MHBjrlf99_Si40QR4zu:b4k0f2h) ([raw file](https://github.com/openmpf/openmpf-components/blob/fb4b62571349c1c5fe6cb5745162e2af35c4c1d3/cpp/KeywordTagging/plugin-files/descriptor/descriptor.json#L22)):*
<details><summary><i>Previously, hhuangMITRE (Howard W Huang) wrote…</i></summary><blockquote>

> ```
>         "DETECTION_TEXT",
>         "DETECTION_SPEECH"
>       ]
> ```
Making `DETECTION_SPEECH` a requirement caused the feed-forward behavior for Tesseract-KeywordTagging job to fail in WFM. I've updated this to only make `DETECTION_TEXT` a requirement in order to test the component in WFM.  
</blockquote></details>

I've removed DETECTION_TEXT as well so that it works with speech as well

**Review by mcrensh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/133)* status: 4 of 44 files reviewed, 16 unresolved discussions (waiting on @hhuangMITRE and @jrobble)

___
*[cpp/KeywordTagging/test/test_keyword_tagging.cpp, line 32 at r6](https://reviewable.io/reviews/openmpf/openmpf-components/133#-ME5z5HW91sheq2ggZeo:-MHBk5iZ8k3z5MZC_KoJ:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/fb4b62571349c1c5fe6cb5745162e2af35c4c1d3/cpp/KeywordTagging/test/test_keyword_tagging.cpp#L32)):*
<details><summary><i>Previously, hhuangMITRE (Howard W Huang) wrote…</i></summary><blockquote>

Looks good. I built and ran the keyword tagging tests from my end, they all passed. They're also performing text-tagging checks from the Tesseract tagging component tests.

I'm going to repeat these tests manually w/ feed-forward of Tesseract results in WFM and make sure that the output is as expected.
</blockquote></details>

Done.
___
*[java/TikaTextDetection/plugin-files/descriptor/descriptor.json, line 42 at r9](https://reviewable.io/reviews/openmpf/openmpf-components/133#-MGRO4VM9NY2UXtnT0df:-MHBp9l4BkbA6qd2VCqz:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/72618de35e008585551610cf31805cc3436e7354/java/TikaTextDetection/plugin-files/descriptor/descriptor.json#L42)):*
<details><summary><i>Previously, hhuangMITRE (Howard W Huang) wrote…</i></summary><blockquote>

> ```
>   {
>           "name": "FULL_REGEX_SEARCH",
>           "description": "Toggles REGEX search to include all matching trigger words associated with the regex patterns for each tag. When disabled, only the first instance of the first matching trigger word for each tag category is included.",
>           "type": "BOOLEAN",
>           "defaultValue": "true"
>         },
> ```

I'm leaving a note here that this option is no longer used and should be removed. 
</blockquote></details>

Done.
___
*[java/TikaTextDetection/src/main/java/org/mitre/mpf/detection/tika/TikaTextDetectionComponent.java, line 28 at r9](https://reviewable.io/reviews/openmpf/openmpf-components/133#-MGRMJF01nb5tc_rissa:-MHBpDe46_K1aO4ssy_e:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/72618de35e008585551610cf31805cc3436e7354/java/TikaTextDetection/src/main/java/org/mitre/mpf/detection/tika/TikaTextDetectionComponent.java#L28)):*
<details><summary><i>Previously, hhuangMITRE (Howard W Huang) wrote…</i></summary><blockquote>

Looks good. The regex text tagging has been removed. 

The`text-tags.json` file in this component can now be removed. I can remove in a follow up after I test this component further alongside the AzureOCR component. I'm leaving a reminder here for now.
</blockquote></details>

Done.

**Review by jrobble — CHANGES_REQUESTED** [review]
> so I might need someone who can access the Azure Cognitive Speech Services to test out keyword tagging on it

I tested it with ACS Speech and it works.

> Reviewed 11 of 167 files at r1, 5 of 53 files at r2, 13 of 197 files at r3, 3 of 231 files at r4, 1 of 222 files at r5, 1 of 1 files at r6, 1 of 5 files at r7, 1 of 2 files at r8, 5 of 10 files at r9, 1 of 2 files at r10, 2 of 3 files at r11, 15 of 16 files at r12.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/133#-:-MLEzILM9QQo5s_dQTmM:b-cc2mk0)* status: all files reviewed, 6 unresolved discussions (waiting on @hhuangMITRE and @mcrensh)

___
*[cpp/KeywordTagging/plugin-files/descriptor/descriptor.json, line 2 at r11](https://reviewable.io/reviews/openmpf/openmpf-components/133#-MJn5Gu87U5wZ4DSe770:-MJn5Gu87U5wZ4DSe771:bda8dr6) ([raw file](https://github.com/openmpf/openmpf-components/blob/8156409926fd1a98193497b0ebbcf42a9b7679ba/cpp/KeywordTagging/plugin-files/descriptor/descriptor.json#L2)):*
> ```JSON
> {
>   "componentName": "KeywordTaggingComponent",
> ```

I decided to call this just "KeywordTagging" and changed the name of the lib and other things accordingly.
___
*[cpp/TesseractOCRTextDetection/plugin-files/descriptor/descriptor.json, line 41 at r11](https://reviewable.io/reviews/openmpf/openmpf-components/133#-MJn8YsT69_DzmHEacAE:-MJn8YsT69_DzmHEacAF:bdmqh01) ([raw file](https://github.com/openmpf/openmpf-components/blob/eb35d510e89819f6a91222bc2000f3f56bf6f676/cpp/TesseractOCRTextDetection/plugin-files/descriptor/descriptor.json#L41)):*
> ```JSON
>         },
>         {
>           "name": "TAGGING_FILE",
> ```

Remove the "# Text Tagging" section from the Tesseract component README.md and add the content to a KeywordTagging component README.md.
___
*[cpp/TesseractOCRTextDetection/test/test_tesseract_ocr_detection.cpp, line 844 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/133#-M505nJV7C1fxHOsvv9K:-MKLYSVT6RpR7p76apqg:b-bfpwky) ([raw file](https://github.com/openmpf/openmpf-components/blob/588c931546c7f5fa09c92176f10b1000a49c65ec/cpp/TesseractOCRTextDetection/test/test_tesseract_ocr_detection.cpp#L844)):*
<details><summary><i>Previously, hhuangMITRE (Howard W Huang) wrote…</i></summary><blockquote>

My apologies, I think I missed a discussion where Jeff had requested we remove the parallel vs. serial checks. I'll make any updates here during the merge. 

@jrobble should I remove the serial processing behavior checks from the system tests? I remember while I was in another review you mentioned that we had removed these tests on purpose since they are mainly runtime checks (comparing parallel vs serial behavior, which is not what these output tests are for). We're also set to do parallel processing now by default.

We could leave the serial checks in to make sure they produce the same output as parallel runs, but otherwise I'm also fine with removing those comparisons and leaving the default checks in parallel processing. 
</blockquote></details>

I think in general I was saying that we shouldn't write any tests that compare the speed of serial vs. parallel processing, but it's okay to ensure that parallel processing is returning the expected results. I think the current tests are fine. I know we recently worked on getting the tests to run in 5 min, so I'm fine with the serial and parallel tests.
___
*[cpp/TesseractOCRTextDetection/test/test_tesseract_ocr_detection.cpp, line 161 at r11](https://reviewable.io/reviews/openmpf/openmpf-components/133#-MJnB6zvANTCV5lVx8XE:-MJnB6zvANTCV5lVx8XF:bsmgygm) ([raw file](https://github.com/openmpf/openmpf-components/blob/8156409926fd1a98193497b0ebbcf42a9b7679ba/cpp/TesseractOCRTextDetection/test/test_tesseract_ocr_detection.cpp#L161)):*
> ```cpp
> }
> 
> bool assertSameText(const std::string &expected, const std::string &actual, log4cxx::LoggerPtr hw_logger_) {
> ```

There is no `ASSERT_` call made within `assertSameText`, so the name is a bit misleading.

Please update `assertSameText` so that `ASSERT_TRUE` is called within the function like it is in `assertInImage`.

This:

```
    assertInImage("data/tags-keyword.png", "Passenger Passport", results, "TEXT");
    expected = "Passenger Passport";
    ASSERT_TRUE(assertSameText(expected, results[0].detection_properties.at("TEXT"), hw_logger_));
```

Can be refactored to:

```
    assertInImage("data/tags-keyword.png", "Passenger Passport", results, "TEXT");
    assertSameText("Passenger Passport", results[0].detection_properties.at("TEXT"), hw_logger_);
```
___
*[cpp/TesseractOCRTextDetection/test/test_tesseract_ocr_detection.cpp, line 563 at r11](https://reviewable.io/reviews/openmpf/openmpf-components/133#-MJn9_xUBP1zz33ypSZy:-MJn9_xUBP1zz33ypSZz:b-454h8b) ([raw file](https://github.com/openmpf/openmpf-components/blob/8156409926fd1a98193497b0ebbcf42a9b7679ba/cpp/TesseractOCRTextDetection/test/test_tesseract_ocr_detection.cpp#L563)):*
> ```cpp
>     // Test basic text detection.
>     // Ensure each test case produces expected text result.
>     // Originally used to test tag results, which have been transferred to the keyword tagging component.
> ```

You can remove this "Originally" comment. No need to mention ancient history in the comments. The git history speaks for itself.
___
*[java/TikaTextDetection/src/test/java/org/mitre/mpf/detection/tika/TestTikaTextDetectionComponent.java, line 68 at r9](https://reviewable.io/reviews/openmpf/openmpf-components/133#-MGROvtw8cQ-7z-tpFd1:-MKLXxeO7N5RGMOUGR0R:b-bru5j0) ([raw file](https://github.com/openmpf/openmpf-components/blob/72618de35e008585551610cf31805cc3436e7354/java/TikaTextDetection/src/test/java/org/mitre/mpf/detection/tika/TestTikaTextDetectionComponent.java#L68)):*
<details><summary><i>Previously, hhuangMITRE (Howard W Huang) wrote…</i></summary><blockquote>

Keyword tagging tests have been removed and I've double checked the component output vs. original output in WFM. 

Detected text tags match, and it also appears KeywordTagging has cleaned up excess whitespace found by TikaTextDetection, mostly extra newlines. I recall this filtering was done because in the OCR component, extra white space was often found all over the results, and we had to make sure that the text was cleared of that by default. Since we're only trimming down white space, I think this filtering is fine. 

Just in case, I'll leave a note reminding myself to ask if we should also have KeywordTagging clean up text picked up in AzureOCR, TikaText, and other text detection components by default. 

In the meantime, I'm reviewing the AzureOCR component changes as well. 
</blockquote></details>

I believe we decided that cleaning up the whitespace is desirable.

**Review by mcrensh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/133)* status: 35 of 43 files reviewed, 6 unresolved discussions (waiting on @hhuangMITRE and @jrobble)

___
*[cpp/TesseractOCRTextDetection/plugin-files/descriptor/descriptor.json, line 41 at r11](https://reviewable.io/reviews/openmpf/openmpf-components/133#-MJn8YsT69_DzmHEacAE:-MLRPjtX6AL6oxh3QTkj:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/eb35d510e89819f6a91222bc2000f3f56bf6f676/cpp/TesseractOCRTextDetection/plugin-files/descriptor/descriptor.json#L41)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Remove the "# Text Tagging" section from the Tesseract component README.md and add the content to a KeywordTagging component README.md.
</blockquote></details>

Done.
___
*[cpp/TesseractOCRTextDetection/test/test_tesseract_ocr_detection.cpp, line 161 at r11](https://reviewable.io/reviews/openmpf/openmpf-components/133#-MJnB6zvANTCV5lVx8XE:-MLRWDhvBeXG3RhuwpgG:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/8156409926fd1a98193497b0ebbcf42a9b7679ba/cpp/TesseractOCRTextDetection/test/test_tesseract_ocr_detection.cpp#L161)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

There is no `ASSERT_` call made within `assertSameText`, so the name is a bit misleading.

Please update `assertSameText` so that `ASSERT_TRUE` is called within the function like it is in `assertInImage`.

This:

```
    assertInImage("data/tags-keyword.png", "Passenger Passport", results, "TEXT");
    expected = "Passenger Passport";
    ASSERT_TRUE(assertSameText(expected, results[0].detection_properties.at("TEXT"), hw_logger_));
```

Can be refactored to:

```
    assertInImage("data/tags-keyword.png", "Passenger Passport", results, "TEXT");
    assertSameText("Passenger Passport", results[0].detection_properties.at("TEXT"), hw_logger_);
```

</blockquote></details>

Done.
___
*[cpp/TesseractOCRTextDetection/test/test_tesseract_ocr_detection.cpp, line 563 at r11](https://reviewable.io/reviews/openmpf/openmpf-components/133#-MJn9_xUBP1zz33ypSZy:-MLRWLYJAgZdivZQRd0q:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/8156409926fd1a98193497b0ebbcf42a9b7679ba/cpp/TesseractOCRTextDetection/test/test_tesseract_ocr_detection.cpp#L563)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

You can remove this "Originally" comment. No need to mention ancient history in the comments. The git history speaks for itself.
</blockquote></details>

Done.

**Review by mcrensh — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/133#-:-MLRWbmHCz9dU64GRiQS:bnfp4nl)* status: 35 of 43 files reviewed, 6 unresolved discussions (waiting on @hhuangMITRE and @jrobble)

**Review by jrobble — APPROVED** [review]
> Reviewed 7 of 8 files at r13, 3 of 3 files at r14, 2 of 2 files at r15.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/133)* status: all files reviewed, 3 unresolved discussions (waiting on @hhuangMITRE)

**Review by jrobble — APPROVED** [review]
> Reviewed 1 of 1 files at r16.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/133)* status: all files reviewed, 3 unresolved discussions (waiting on @hhuangMITRE)

**Review by jrobble — APPROVED** [review]
> Dismissed @hhuangMITRE from 3 discussions.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/133)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
