### PR TITLE
Changes for improved docker build

### PR DESCRIPTION
**Pull request by brosenberg42**
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/124)

### CODE REVIEW

**Comment by brosenberg42** [comment]
___
*[cpp/DarknetDetection/darknet_lib/CMakeLists.txt, line 122 at r3](https://reviewable.io/reviews/openmpf/openmpf-components/124#-Lz8TwDV8b1zfaM5hmC8:-Lz8VTQ1AbtqkasjSi-J:bks37k7) ([raw file](https://github.com/openmpf/openmpf-components/blob/0545ad325d18ce4f6a825904ac6e927eebb49350/cpp/DarknetDetection/darknet_lib/CMakeLists.txt#L122)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

You dropped `-DGPU -DOPENCV`. What were those used for?
</blockquote></details>

They are already set on line 128.

**Comment by jrobble** [comment]
___
*[cpp/TesseractOCRTextDetection/plugin-files/descriptor/descriptor.json, line 44 at r4](https://reviewable.io/reviews/openmpf/openmpf-components/124#-LzJL-N5BKGnNyOpthIw:-LzJL-N604II4PVeTY_u:brny6xp) ([raw file](https://github.com/openmpf/openmpf-components/blob/4a314ef84a1aa227fc2c575387df77262499a528/cpp/TesseractOCRTextDetection/plugin-files/descriptor/descriptor.json#L44)):*
Should this be `config/text-tags.json`?

Also, I have a problem running the sample binary on my dev. VM:

```
[mpf@openmpf-master build]$ ./sample_tesseract_ocr_detector -i test/data/tags-keywordregex.png 
log4cxx: Could not open file [config/Log4cxxConfig.xml].
log4cxx: No appender could be found for logger (TesseractOCRTextDetection).
log4cxx: Please initialize the log4cxx system properly.
ERROR: Config file not loaded.
Running job on image data uri: test/data/tags-keywordregex.png
GetDetections failed
```

---

Note that specific directories are mentioned in the component source and README.md:

```
                LOG4CXX_ERROR(hw_logger_, "[" + job.job_name + "] Tesseract language models not found. Please add the " +
                                          "associated *.traineddata files to your tessdata directory " +
                                          "($MPF_HOME/plugins/TesseractOCRTextDetection/tessdata) " +
                                          "or shared models directory " +
                                          "($MPF_HOME/share/models/TesseractOCRTextDetection/tessdata).");
```

> Language models supported by Tesseract are stored by default in
`$MPF_HOME/plugins/TesseractOCRTextDetection/tessdata` directory and script

`$MPF_HOME/plugins/TesseractOCRTextDetection` is not a valid location on the Docker image. Instead it's `$MPF_HOME/plugins/plugin`.

It may be simpler to create a symlink `$MPF_HOME/plugins/TesseractOCRTextDetection` to `$MPF_HOME/plugins/plugin` on the image rather than change the source code.

**Comment by jrobble** [comment]
___
*[cpp/TesseractOCRTextDetection/test/CMakeLists.txt, line 50 at r5](https://reviewable.io/reviews/openmpf/openmpf-components/124#-LzsdpoEBfnAX9rUhPCI:-LzsdpoF6iM43GXAVKNU:bs3zg2j) ([raw file](https://github.com/openmpf/openmpf-components/blob/1190e738c6dafb31bcadd8354bb21b794e180a9e/cpp/TesseractOCRTextDetection/test/CMakeLists.txt#L50)):*
> ```CMake
> 
>     # Install test images and videos.
>     file(COPY data/ DESTINATION data)
> ```

Why do we use symlinks for some things and COPY others? Shouldn't we use symlinks for everything we can? 


I understand the need to copy "data", since that is not part of the "plugin" dir, but we copy "config" into the "test" dir, but symlink to "config" from the "build" dir, which is not consistent.

**Comment by brosenberg42** [comment]
___
*[cpp/TesseractOCRTextDetection/test/CMakeLists.txt, line 50 at r5](https://reviewable.io/reviews/openmpf/openmpf-components/124#-LzsdpoEBfnAX9rUhPCI:-Lzw4UG2DKibEZ-SR6PI:b-hlq5v0) ([raw file](https://github.com/openmpf/openmpf-components/blob/1190e738c6dafb31bcadd8354bb21b794e180a9e/cpp/TesseractOCRTextDetection/test/CMakeLists.txt#L50)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Why do we use symlinks for some things and COPY others? Shouldn't we use symlinks for everything we can? 


I understand the need to copy "data", since that is not part of the "plugin" dir, but we copy "config" into the "test" dir, but symlink to "config" from the "build" dir, which is not consistent.
</blockquote></details>

That is because both `TesseractOCRTextDetection/plugin-files/config` and `TesseractOCRTextDetection/test/config` exist.

**Comment by jrobble** [comment]
___
*[cpp/TesseractOCRTextDetection/test/CMakeLists.txt, line 50 at r5](https://reviewable.io/reviews/openmpf/openmpf-components/124#-LzsdpoEBfnAX9rUhPCI:-Lzw7Uah2eds_kXYGALG:b-n7s0ce) ([raw file](https://github.com/openmpf/openmpf-components/blob/1190e738c6dafb31bcadd8354bb21b794e180a9e/cpp/TesseractOCRTextDetection/test/CMakeLists.txt#L50)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

That is because both `TesseractOCRTextDetection/plugin-files/config` and `TesseractOCRTextDetection/test/config` exist.
</blockquote></details>

Got it. That's fine then.

**Comment by jrobble** [comment]
___
*[cpp/TesseractOCRTextDetection/plugin-files/descriptor/descriptor.json, line 44 at r4](https://reviewable.io/reviews/openmpf/openmpf-components/124#-LzJL-N5BKGnNyOpthIw:-Lzw8GS419MPPK3kJNHj:b-8v4jpe) ([raw file](https://github.com/openmpf/openmpf-components/blob/4a314ef84a1aa227fc2c575387df77262499a528/cpp/TesseractOCRTextDetection/plugin-files/descriptor/descriptor.json#L44)):*
The README still says:

> Language models supported by Tesseract are stored by default in
`$MPF_HOME/plugins/TesseractOCRTextDetection/tessdata` directory

It seems you need to add a caveat there about Docker deployments.

**Comment by jrobble** [comment]
___
*[cpp/TesseractOCRTextDetection/TesseractOCRTextDetection.cpp, line 734 at r5](https://reviewable.io/reviews/openmpf/openmpf-components/124#-LzwE4Af52sBsJfC9Bmi:-LzwE4Af52sBsJfC9Bmj:b-gy2rq0) ([raw file](https://github.com/openmpf/openmpf-components/blob/1190e738c6dafb31bcadd8354bb21b794e180a9e/cpp/TesseractOCRTextDetection/TesseractOCRTextDetection.cpp#L734)):*
Let's print out the full path instead of just "tessdata" in this message:

> 2020-01-31 15:29:28,277 WARN [0x7f7d5e8ea8c0] TesseractOCRTextDetection:746 - [Job 51:eng-bul.png] Some Tessdata models were not found, or are not co-located. Please ensure that all of the following models exist in the same directory, either /opt/mpf/share/models//TesseractOCRTextDetection/tessdata or tessdata: script/Cyrillic .

Specially, I'm talking about the "or tessdata: script/Cyrillic " part.

**Comment by brosenberg42** [comment]
I am going re-create this PR with a new branch since I am reverting a lot of stuff.

**Pull request closed without merging**
