### PR TITLE
Updating Azure Read Detection README (v3.2).

### PR DESCRIPTION
**Pull request by hhuangMITRE**
Adding info regarding the Read API v3.2, as well as incoming changes to Azure's Read OCR services. 

Moving forward, we will be looking into testing Read v4.0 as part of the Azure's Computer Vision API.

- - -
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/327)

### CODE REVIEW

**Review by jrobble — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/327)* status: all files reviewed, 1 unresolved discussion (waiting on @hhuangMITRE)

**Review by hhuangMITRE — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/327)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @jrobble)

___
*[`python/AzureReadTextDetection/README.md` line 41 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/327#-NUS94381gUzSfDOtheM:-NUSEcRZ82r4loIErjdg:bj1lvx) ([raw file](https://github.com/openmpf/openmpf-components/blob/4197fcd31b31d382c534a1217359a5b7c9984e88/python/AzureReadTextDetection/README.md#L41)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Is this still the complete list of languages?

If the number of languages is short, you can list them here. If not, provide some examples and link to the Azure documentation that has the supported languages and respective BCP-47 codes in it.

Other changes to this doc look good.
</blockquote></details>

Ah thanks for catching that! The list is 164 now, they've massively increased the number of listed languages over several v3.2 model updates. 

I included the link to the official list of supported languages and respective BCP-47 codes. Currently, the document is covering the latest GA Read API (3.2).

However, upon some further thought, I felt a bit unsure about just leaving a link, as my intuition is the Azure team could always update the language support listed to reflect Read v4.0 moving forward (the page seems to cover the latest GA version, which is still 3.2 for now). 

So as precaution, I've included a markdown-formatted list of the supported languages (and additional handwritten support) as well. Let me know if this looks good or if we should move that info to a separate markdown file for tracking purposes.

**Review by jrobble — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/327)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @hhuangMITRE)

___
*[`python/AzureReadTextDetection/README.md` line 42 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/327#-NUSGr9-4mfrDlXtr1vJ:-NUSGr9-4mfrDlXtr1vK:b-av6ro) ([raw file](https://github.com/openmpf/openmpf-components/blob/07b4b3b559a03477c5d31cc6fb7943c13359fc62/python/AzureReadTextDetection/README.md#L42)):*
> ```Markdown
>    otherwise.
> - `LANGUAGE`:  When provided, disables automatic language detection and processes document based on provided language.
>    The language code must be in case-sensitive BCP-47.  Currently, 164 languages are supported, with 9 languages also having handwritten text support [see here]](https://aka.ms/ocr-languages).
> ```

Remove the extra bracket at the end of `[see here]]`.
___
*[`python/AzureReadTextDetection/README.md` line 44 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/327#-NUSHARs8JYMGY_XqoRB:-NUSHARs8JYMGY_XqoRC:bl7ncr2) ([raw file](https://github.com/openmpf/openmpf-components/blob/07b4b3b559a03477c5d31cc6fb7943c13359fc62/python/AzureReadTextDetection/README.md#L44)):*
> ```Markdown
>    The language code must be in case-sensitive BCP-47.  Currently, 164 languages are supported, with 9 languages also having handwritten text support [see here]](https://aka.ms/ocr-languages).
> 
>    For tracking purposes, the currently listed 164 supported languages and associated BCP-47 codes include:
> ```

Please make sure to note that the table is for v3.2.

Also, let's separate the table out into its own section, like [this](https://github.com/openmpf/openmpf-components/tree/master/python/AzureSpeechDetection#language-identifiers).

**Review by hhuangMITRE — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/327)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @jrobble)

___
*[`python/AzureReadTextDetection/README.md` line 42 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/327#-NUSGr9-4mfrDlXtr1vJ:-NUSNAvZ6KbTECOJ6NgV:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/07b4b3b559a03477c5d31cc6fb7943c13359fc62/python/AzureReadTextDetection/README.md#L42)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Remove the extra bracket at the end of `[see here]]`.
</blockquote></details>

Done.
___
*[`python/AzureReadTextDetection/README.md` line 44 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/327#-NUSHARs8JYMGY_XqoRB:-NUSNFhX5PTpTYhCorAH:b40uvfn) ([raw file](https://github.com/openmpf/openmpf-components/blob/07b4b3b559a03477c5d31cc6fb7943c13359fc62/python/AzureReadTextDetection/README.md#L44)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Please make sure to note that the table is for v3.2.

Also, let's separate the table out into its own section, like [this](https://github.com/openmpf/openmpf-components/tree/master/python/AzureSpeechDetection#language-identifiers).
</blockquote></details>

Yep, that looks better. Also, I meant to include the OCR version in the previous update, thanks for quickly catching that.

**Review by hhuangMITRE — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/327)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @jrobble)

___
*[`python/AzureReadTextDetection/README.md` line 44 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/327#-NUSHARs8JYMGY_XqoRB:-NUS_Q-h3lpcCmokd-p3:b-7xjch2) ([raw file](https://github.com/openmpf/openmpf-components/blob/07b4b3b559a03477c5d31cc6fb7943c13359fc62/python/AzureReadTextDetection/README.md#L44)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Let's remove the `(optional)` part from the column names to avoid confusion. Better yet, change the column name to `BCP-47` to match the Azure Speech component.
</blockquote></details>

Done. I've updated the description to BCP-47.
___
*[`python/AzureReadTextDetection/README.md` line 42 at r3](https://reviewable.io/reviews/openmpf/openmpf-components/327#-NUSRBoX3I_L3eDDNzo8:-NUS_LO42v67WAoynYcH:b-j0rmd) ([raw file](https://github.com/openmpf/openmpf-components/blob/44192f1a775ecaa08e0e60107cb5b79b27dcb072/python/AzureReadTextDetection/README.md#L42)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

I think you want:

```
Currently, 164 languages are supported, with 9 languages also having handwritten text support (see [language docs](https://aka.ms/ocr-languages)).
```
</blockquote></details>

That looks better, changes done.

**Review by jrobble — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/327)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @hhuangMITRE)

**Pull request merged**
