### PR TITLE
Add Azure OCR Text Detection Component using Azure Read API. (#1162)

### PR DESCRIPTION
**Pull request by hhuangMITRE**
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/224)

### CODE REVIEW

**Comment by hhuangMITRE** [comment]
Note: Angles returned by Azure Read API are in clockwise direction in degrees between (-180, 180]. Let me know if the ROTATION values (specified by MPF) uses a different orientation. I noticed during the tests I kept updating the angle values from their original OCR test values. (Ex. from 90 to 270).

**Comment by hhuangMITRE** [comment]
Just leaving a status update here: after updating my docker build, I was able to review the markup results. I'm currently making some alternations to get the bounding box data to align over the text a bit better and will submit an update after. I may also transfer those improvements to the Read API results processor for the form recognizer component as well in a separate PR.

**Review by jrobble — CHANGES_REQUESTED** [review]
> Reviewed 4 of 20 files at r1, 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/224)* status: 5 of 20 files reviewed, 12 unresolved discussions (waiting on @brosenberg42 and @hhuangMITRE)

___
*[python/AzureReadTextDetection/README.md, line 19 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/224#-MX4-ayy7VI_Cy1JKf--:-MX4-ayy7VI_Cy1JKf-0:b-ueg4jq) ([raw file](https://github.com/openmpf/openmpf-components/blob/85729625bec9810ca090dedfa928db9ea86c71af/python/AzureReadTextDetection/README.md#L19)):*
> ```Markdown
> 
>    - `https://{endpoint}/vision/v3.1/read/analyze` - v3.1 Read OCR analysis.
>    - `https://{endpoint}/vision/v3.1-preview.2/read/analyze` - v3.1 preview Read OCR analysis.
> ```

It seems that Azure is on [v3.2 preview 3](https://westcentralus.dev.cognitive.microsoft.com/docs/services/computer-vision-v3-2-preview-3/operations/56f91f2e778daf14a499f21b) now.

Do we want to target that? 

Was there something about v3.1 preview 2 that interested us over just version 3.1?
___
*[python/AzureReadTextDetection/README.md, line 48 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/224#-MX3Zwlg6PXXoLIBk3Ob:-MX3Zwlg6PXXoLIBk3Oc:bwru7k) ([raw file](https://github.com/openmpf/openmpf-components/blob/85729625bec9810ca090dedfa928db9ea86c71af/python/AzureReadTextDetection/README.md#L48)):*
> ```Markdown
> `sample_acs_read_detector.py` can be used to quickly test with the Azure
> endpoint. It supports images, video (*.avi), and PDF inputs only. PDF inputs must contain the `.pdf`
> extension to be properly recognized as generic job inputs. Similarly video inputs must contain the ".avi" extension.
> ```

Use backticks around `.avi`.
___
*[python/AzureReadTextDetection/acs_read_detection_component/acs_read_detection_component.py, line 48 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/224#-MX3oEgbEZfBIPdgLJWJ:-MX3oEgbEZfBIPdgLJWK:b-9gp5mg) ([raw file](https://github.com/openmpf/openmpf-components/blob/85729625bec9810ca090dedfa928db9ea86c71af/python/AzureReadTextDetection/acs_read_detection_component/acs_read_detection_component.py#L48)):*
> ```Python
>     detection_type = 'TEXT'
> 
>     def get_detections_from_generic(self, generic_job):
> ```

Make this a static method by annotating with `@staticmethod`.
___
*[python/AzureReadTextDetection/acs_read_detection_component/acs_read_detection_component.py, line 118 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/224#-MX3dtai2E5uoJ2HGvcY:-MX3dtai2E5uoJ2HGvcZ:b-tqtvlh) ([raw file](https://github.com/openmpf/openmpf-components/blob/85729625bec9810ca090dedfa928db9ea86c71af/python/AzureReadTextDetection/acs_read_detection_component/acs_read_detection_component.py#L118)):*
> ```Python
> 
> 
>     def get_indexed_detections(self, frames):
> ```

This is not used.
___
*[python/AzureReadTextDetection/acs_read_detection_component/acs_read_detection_component.py, line 136 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/224#-MX3mgdoAIs1DcGhtGfz:-MX3mgdoAIs1DcGhtGg-:b2bi28e) ([raw file](https://github.com/openmpf/openmpf-components/blob/85729625bec9810ca090dedfa928db9ea86c71af/python/AzureReadTextDetection/acs_read_detection_component/acs_read_detection_component.py#L136)):*
> ```Python
>                 yield idx, detection
> 
>     def get_image_detections(self, frame, is_video=False):
> ```

Add `is_video` to the method comment.
___
*[python/AzureReadTextDetection/acs_read_detection_component/acs_read_detection_component.py, line 172 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/224#-MX3bVbpCB6weqtQDYsv:-MX3bVbq-cwul65LJVO0:bltuvp2) ([raw file](https://github.com/openmpf/openmpf-components/blob/85729625bec9810ca090dedfa928db9ea86c71af/python/AzureReadTextDetection/acs_read_detection_component/acs_read_detection_component.py#L172)):*
> ```Python
> 
>             try:
>                 results = urllib.request.urlopen(result_request)
> ```

@brosenberg42 recently landed changes that add HTTP retries to the Azure components, so instead of:

```
results = urllib.request.urlopen(result_request)
```

You should instead do:

```
with self._http_retry.urlopen(result_request) as results:
```

See [here](https://github.com/openmpf/openmpf-components/blob/develop/python/AzureFormDetection/acs_form_detection_component/acs_form_detection_component.py#L138).
___
*[python/AzureReadTextDetection/acs_read_detection_component/acs_read_detection_component.py, line 202 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/224#-MX3d-dK7h3WW_oUsuRv:-MX3d-dK7h3WW_oUsuRw:b81y000) ([raw file](https://github.com/openmpf/openmpf-components/blob/85729625bec9810ca090dedfa928db9ea86c71af/python/AzureReadTextDetection/acs_read_detection_component/acs_read_detection_component.py#L202)):*
> ```Python
>         request = urllib.request.Request(self._acs_url, bytes(encoded_frame), self._acs_headers)
>         try:
>             response = urllib.request.urlopen(request)
> ```

Again, use:

```
with self._http_retry.urlopen(request) as response:
```

See [here](https://github.com/openmpf/openmpf-components/blob/develop/python/AzureFormDetection/acs_form_detection_component/acs_form_detection_component.py#L167).
___
*[python/AzureReadTextDetection/acs_read_detection_component/acs_read_detection_component.py, line 428 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/224#-MX3o-GD5kELDfQeT2Cz:-MX3o-GD5kELDfQeT2D-:b-9gp5mg) ([raw file](https://github.com/openmpf/openmpf-components/blob/85729625bec9810ca090dedfa928db9ea86c71af/python/AzureReadTextDetection/acs_read_detection_component/acs_read_detection_component.py#L428)):*
> ```Python
>         return corrected_box
> 
>     def _convert_to_rect(self, bounding_box):
> ```

Make this a static method by annotating with `@staticmethod`.
___
*[python/AzureReadTextDetection/acs_read_detection_component/acs_read_detection_component.py, line 450 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/224#-MX3gNGu-TYPfJsFsVOG:-MX3gNGu-TYPfJsFsVOH:bh15fc3) ([raw file](https://github.com/openmpf/openmpf-components/blob/85729625bec9810ca090dedfa928db9ea86c71af/python/AzureReadTextDetection/acs_read_detection_component/acs_read_detection_component.py#L450)):*
PyCharm gives this warning:

> Local variable 'p_ref' might be referenced before assignment
___
*[python/AzureReadTextDetection/acs_read_detection_component/acs_read_detection_component.py, line 458 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/224#-MX3nmYx3rP3pjMSvx59:-MX3nmYx3rP3pjMSvx5A:b-997mf2) ([raw file](https://github.com/openmpf/openmpf-components/blob/85729625bec9810ca090dedfa928db9ea86c71af/python/AzureReadTextDetection/acs_read_detection_component/acs_read_detection_component.py#L458)):*
> ```Python
> 
> 
>     def _orient_bounding_box(self, bounding_box, angle):
> ```

Make this a static method by annotating with `@staticmethod`.
___
*[python/AzureReadTextDetection/plugin-files/descriptor/descriptor.json, line 19 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/224#-MX3YZhm7gcb02InoA0F:-MX3YZhm7gcb02InoA0G:b-dquco8) ([raw file](https://github.com/openmpf/openmpf-components/blob/85729625bec9810ca090dedfa928db9ea86c71af/python/AzureReadTextDetection/plugin-files/descriptor/descriptor.json#L19)):*
> ```JSON
>         "DETECTION",
>         "DETECTION_TEXT",
>         "DETECTION_TEXT_AZURE"
> ```

Change this last one to `DETECTION_TEXT_AZURE_READ`, and change the AzureOcrTextDetection component to use `DETECTION_TEXT_AZURE_OCR`.
___
*[python/AzureReadTextDetection/tests/test_acs.py, line 172 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/224#-MX3XnRSDSgeeJrrWcjM:-MX3XnRSDSgeeJrrWcjN:b-dl83jn) ([raw file](https://github.com/openmpf/openmpf-components/blob/85729625bec9810ca090dedfa928db9ea86c71af/python/AzureReadTextDetection/tests/test_acs.py#L172)):*
> ```Python
>     def test_chinese_text(self):
>         self.set_results_path(get_test_file('foreign/chinese-two-cities-results.json'))
>         job = mpf.ImageJob('Test', get_test_file('foreign/chinese-two-cities.png'), get_test_properties(), {}, None)
> ```

The `foreign` and `orientation` dirs are missing.

**Review by hhuangMITRE — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/224)* status: 3 of 49 files reviewed, 12 unresolved discussions (waiting on @brosenberg42 and @jrobble)

___
*[python/AzureReadTextDetection/README.md, line 19 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/224#-MX4-ayy7VI_Cy1JKf--:-MXGW_Kr1uphVbbaii5H:b-zgqxb5) ([raw file](https://github.com/openmpf/openmpf-components/blob/85729625bec9810ca090dedfa928db9ea86c71af/python/AzureReadTextDetection/README.md#L19)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

It seems that Azure is on [v3.2 preview 3](https://westcentralus.dev.cognitive.microsoft.com/docs/services/computer-vision-v3-2-preview-3/operations/56f91f2e778daf14a499f21b) now.

Do we want to target that? 

Was there something about v3.1 preview 2 that interested us over just version 3.1?
</blockquote></details>

Yep, I've looked over the v3.2 preview notes, there are a greater number of supported languages so I've updated the documentation to reflect that. I thinking targeting the latest version would be best.

Previously, I was trying to identify why Azure had dropped support for reporting detected languages and tried out various versions (including v3.1 previews and v3.0). That was a leftover comment from back then regarding which of the most recent versions I've tested (v3.1, v3.1-preview 2).

I've updated the documentation to reflect stable releases + most recent preview version (v3.0, v3.1, v3.2-preview). 
___
*[python/AzureReadTextDetection/README.md, line 48 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/224#-MX3Zwlg6PXXoLIBk3Ob:-MXGZSmr4wZfTc0ClU_T:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/85729625bec9810ca090dedfa928db9ea86c71af/python/AzureReadTextDetection/README.md#L48)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Use backticks around `.avi`.
</blockquote></details>

Done.
___
*[python/AzureReadTextDetection/acs_read_detection_component/acs_read_detection_component.py, line 48 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/224#-MX3oEgbEZfBIPdgLJWJ:-MXGZWqRDoGoCZcgUdn9:bqez4q8) ([raw file](https://github.com/openmpf/openmpf-components/blob/85729625bec9810ca090dedfa928db9ea86c71af/python/AzureReadTextDetection/acs_read_detection_component/acs_read_detection_component.py#L48)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Make this a static method by annotating with `@staticmethod`.
</blockquote></details>

Done. I've also set a couple of the other methods to static as well since they weren't using class variables. 
___
*[python/AzureReadTextDetection/acs_read_detection_component/acs_read_detection_component.py, line 118 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/224#-MX3dtai2E5uoJ2HGvcY:-MXGZhNO-IsDgYiDKPdh:bss4a2b) ([raw file](https://github.com/openmpf/openmpf-components/blob/85729625bec9810ca090dedfa928db9ea86c71af/python/AzureReadTextDetection/acs_read_detection_component/acs_read_detection_component.py#L118)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

This is not used.
</blockquote></details>

Removed.
___
*[python/AzureReadTextDetection/acs_read_detection_component/acs_read_detection_component.py, line 136 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/224#-MX3mgdoAIs1DcGhtGfz:-MXGZjv9-qYCJszD1EXH:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/85729625bec9810ca090dedfa928db9ea86c71af/python/AzureReadTextDetection/acs_read_detection_component/acs_read_detection_component.py#L136)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Add `is_video` to the method comment.
</blockquote></details>

Done.
___
*[python/AzureReadTextDetection/acs_read_detection_component/acs_read_detection_component.py, line 172 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/224#-MX3bVbpCB6weqtQDYsv:-MXGZkzR4pBAjK1-zUE9:b-nhemam) ([raw file](https://github.com/openmpf/openmpf-components/blob/85729625bec9810ca090dedfa928db9ea86c71af/python/AzureReadTextDetection/acs_read_detection_component/acs_read_detection_component.py#L172)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

@brosenberg42 recently landed changes that add HTTP retries to the Azure components, so instead of:

```
results = urllib.request.urlopen(result_request)
```

You should instead do:

```
with self._http_retry.urlopen(result_request) as results:
```

See [here](https://github.com/openmpf/openmpf-components/blob/develop/python/AzureFormDetection/acs_form_detection_component/acs_form_detection_component.py#L138).
</blockquote></details>

@jrobble I've updated to use the new HTTP retries utility but I noticed something in the original code:
```
                with self._http_retry.urlopen(result_request) as results:
                    if results.status != 200:
                        raise mpf.DetectionError.DETECTION_FAILED.exception(
                            'GET request failed with HTTP status {}\n'.format(results.status) +
                            '\nHTTP request body:\n{}'.format(json_results))
                    json_results = json.load(results)

```
At [line 142](https://github.com/openmpf/openmpf-components/blob/develop/python/AzureFormDetection/acs_form_detection_component/acs_form_detection_component.py#L142) of the ACS form detection component, I think json_results was called before it was initialized. I can quickly update this PR to fix that too, but since this is another component, should it belong in its own PR as a one-liner?
___
*[python/AzureReadTextDetection/acs_read_detection_component/acs_read_detection_component.py, line 202 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/224#-MX3d-dK7h3WW_oUsuRv:-MXGa7uN2Jeh6eU_w4Cq:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/85729625bec9810ca090dedfa928db9ea86c71af/python/AzureReadTextDetection/acs_read_detection_component/acs_read_detection_component.py#L202)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Again, use:

```
with self._http_retry.urlopen(request) as response:
```

See [here](https://github.com/openmpf/openmpf-components/blob/develop/python/AzureFormDetection/acs_form_detection_component/acs_form_detection_component.py#L167).
</blockquote></details>

Done.
___
*[python/AzureReadTextDetection/acs_read_detection_component/acs_read_detection_component.py, line 428 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/224#-MX3o-GD5kELDfQeT2Cz:-MXGaFGn19xaGIRgJRsa:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/85729625bec9810ca090dedfa928db9ea86c71af/python/AzureReadTextDetection/acs_read_detection_component/acs_read_detection_component.py#L428)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Make this a static method by annotating with `@staticmethod`.
</blockquote></details>

Done.
___
*[python/AzureReadTextDetection/acs_read_detection_component/acs_read_detection_component.py, line 450 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/224#-MX3gNGu-TYPfJsFsVOG:-MXGaGCK19NJYkYv9RpI:b-8re00i) ([raw file](https://github.com/openmpf/openmpf-components/blob/85729625bec9810ca090dedfa928db9ea86c71af/python/AzureReadTextDetection/acs_read_detection_component/acs_read_detection_component.py#L450)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

PyCharm gives this warning:

> Local variable 'p_ref' might be referenced before assignment
</blockquote></details>

Fixed, thanks for catching that. It should have been only executed within the `else:` block.
___
*[python/AzureReadTextDetection/acs_read_detection_component/acs_read_detection_component.py, line 458 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/224#-MX3nmYx3rP3pjMSvx59:-MXGaN-e41YtxtEcuPXY:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/85729625bec9810ca090dedfa928db9ea86c71af/python/AzureReadTextDetection/acs_read_detection_component/acs_read_detection_component.py#L458)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Make this a static method by annotating with `@staticmethod`.
</blockquote></details>

Done.
___
*[python/AzureReadTextDetection/plugin-files/descriptor/descriptor.json, line 19 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/224#-MX3YZhm7gcb02InoA0F:-MXGaQ6I4-q2GoDMvLkG:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/85729625bec9810ca090dedfa928db9ea86c71af/python/AzureReadTextDetection/plugin-files/descriptor/descriptor.json#L19)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Change this last one to `DETECTION_TEXT_AZURE_READ`, and change the AzureOcrTextDetection component to use `DETECTION_TEXT_AZURE_OCR`.
</blockquote></details>

Done.
___
*[python/AzureReadTextDetection/tests/test_acs.py, line 172 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/224#-MX3XnRSDSgeeJrrWcjM:-MXGaZ-P7JflHqPNg3Z-:bbxins0) ([raw file](https://github.com/openmpf/openmpf-components/blob/85729625bec9810ca090dedfa928db9ea86c71af/python/AzureReadTextDetection/tests/test_acs.py#L172)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

The `foreign` and `orientation` dirs are missing.
</blockquote></details>

Fixed, included missing files in commit this time. They were meant to be included with the updated unit tests.

**Review by brosenberg42 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/224)* status: 2 of 49 files reviewed, 12 unresolved discussions (waiting on @brosenberg42 and @jrobble)

___
*[python/AzureReadTextDetection/Dockerfile, line 29 at r4](https://reviewable.io/reviews/openmpf/openmpf-components/224#-McAeoYt4vk-spIGVcRx:-McAeoYt4vk-spIGVcRy:b8gljq6) ([raw file](https://github.com/openmpf/openmpf-components/blob/686d348b2c8328560f85a6b156f8440c03a1f36b/python/AzureReadTextDetection/Dockerfile#L29)):*
> ```Dockerfile
> ARG BUILD_REGISTRY
> ARG BUILD_TAG=latest
> FROM ${BUILD_REGISTRY}openmpf_python_executor_ssb:${BUILD_TAG}
> ```

New features in Docker let us simplify most Python component Dockerfiles.
___
*[python/AzureReadTextDetection/acs_read_detection_component/acs_read_detection_component.py, line 42 at r4](https://reviewable.io/reviews/openmpf/openmpf-components/224#-McAeh8fCrsY9hRKB1Go:-McAeh8fCrsY9hRKB1Gp:b-9y1a7h) ([raw file](https://github.com/openmpf/openmpf-components/blob/686d348b2c8328560f85a6b156f8440c03a1f36b/python/AzureReadTextDetection/acs_read_detection_component/acs_read_detection_component.py#L42)):*
> ```Python
> import mpf_component_util as mpf_util
> 
> logger = logging.getLogger('AcsReadComponent')
> ```

These logging changes are needed for CLI runner to work correctly
___
*[python/AzureReadTextDetection/acs_read_detection_component/acs_read_detection_component.py, line 212 at r4](https://reviewable.io/reviews/openmpf/openmpf-components/224#-McAe9SB0yxsj65M99dL:-McAe9SB0yxsj65M99dM:b-3e5ecv) ([raw file](https://github.com/openmpf/openmpf-components/blob/686d348b2c8328560f85a6b156f8440c03a1f36b/python/AzureReadTextDetection/acs_read_detection_component/acs_read_detection_component.py#L212)):*
> ```Python
> 
>     @staticmethod
>     def _get_required_property(property_name, job_properties):
> ```

With `MPF_PROP_` support, component no longer need to handle environment variables manually.
___
*[python/AzureReadTextDetection/tests/test_acs.py, line 129 at r4](https://reviewable.io/reviews/openmpf/openmpf-components/224#-McAeKS-4FyNFCsPSe1k:-McAeKS-4FyNFCsPSe1l:bn6yrg2) ([raw file](https://github.com/openmpf/openmpf-components/blob/686d348b2c8328560f85a6b156f8440c03a1f36b/python/AzureReadTextDetection/tests/test_acs.py#L129)):*
> ```Python
> 
>     # Set the class max file size limit to a smaller value to force resizing.
>     @mock.patch.object(FrameEncoder, 'MAX_FILE_SIZE', new_callable=lambda: 20 * 1024 * 1024)
> ```

Using `@mock.patch.object)` makes the modification to `MAX_FILE_SIZE` only apply to this test, instead of it being applied to all tests that run after it.

**Review by brosenberg42 — COMMENTED** [review]
Unlike the OCR endpoint from AzureOcrTextDetection, the Read API reports confidence values. I think we should include the confidence values in the results. Since each word will have its own confidence, I think it makes sense to average them.

> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/224#-:-McAl-UG2ZBh_31Xd0-g:bxrzo2t)* status: 2 of 50 files reviewed, 12 unresolved discussions (waiting on @brosenberg42 and @jrobble)

___
*[python/AzureReadTextDetection/acs_read_detection_component/acs_read_detection_component.py, line 177 at r4](https://reviewable.io/reviews/openmpf/openmpf-components/224#-McAkqSL0vyq_6ZgIyZ9:-McAkqSL0vyq_6ZgIyZA:bukl5ef) ([raw file](https://github.com/openmpf/openmpf-components/blob/686d348b2c8328560f85a6b156f8440c03a1f36b/python/AzureReadTextDetection/acs_read_detection_component/acs_read_detection_component.py#L177)):*
> ```Python
>                 time.sleep(wait_sec)
>                 attempt_num += 1
>             except urllib.error.HTTPError as e:
> ```

I removed this except block because `self._http_retry.urlopen` already does the same thing.

**Review by hhuangMITRE — COMMENTED** [review]
*Add average confidence scores for detected words (per line or merged lines). 

> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/224#-:-McBG7w9BwBnCps_4xpe:b-4idihk)* status: 2 of 50 files reviewed, 12 unresolved discussions (waiting on @brosenberg42 and @jrobble)

**Review by brosenberg42 — APPROVED** [review]

**Pull request merged**
