### PR TITLE
Update components that have CONFIDENCE_THRESHOLD in their descriptor files.

### PR DESCRIPTION
**Pull request by clnowacki**
**Issues:**

- https://github.com/openmpf/openmpf/issues/1718

**Related PRs**

- https://github.com/openmpf/openmpf/pull/1760
- https://github.com/openmpf/openmpf-docker/pull/209

- - -
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/350)

### CODE REVIEW

**Review by brosenberg42 — CHANGES_REQUESTED** [review]
> Reviewed 8 of 13 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/350)* status: all files reviewed, 4 unresolved discussions (waiting on @clnowacki and @jrobble)

___
*[`cpp/OcvDnnDetection/OcvDnnDetection.cpp` line 674 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/350#-NsJ0jw--Yw_l48diNIb:-NsJ0jw--Yw_l48diNIc:b8qrrx4) ([raw file](https://github.com/openmpf/openmpf-components/blob/7dfeacc06ed9ef7492129f7cdbb7d116e35fb234/cpp/OcvDnnDetection/OcvDnnDetection.cpp#L674)):*
> ```cpp
>     std::string quality_property = GetProperty(props, "QUALITY_SELECTION_PROPERTY", "CONFIDENCE");
>     if (quality_property != "CONFIDENCE") {
>         throw std::runtime_error("Unrecognized quality selection property \"" + quality_property + "\". Only CONFIDENCE is supported for quality selection.");
> ```

We should be throwing `MPFInvalidPropertyException` in this case. For example:
```c++
throw MPFInvalidPropertyException(
    "QUALITY_SELECTION_PROPERTY",
    "Unrecognized quality selection property \"" 
        + quality_property + "\". Only CONFIDENCE is supported for quality selection."
);
```
___
*[`cpp/OcvDnnDetection/plugin-files/descriptor/descriptor.json` line 140 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/350#-NsIyZ-q7UwDXxozTiQl:-NsIyZ-q7UwDXxozTiQm:byinch8) ([raw file](https://github.com/openmpf/openmpf-components/blob/7dfeacc06ed9ef7492129f7cdbb7d116e35fb234/cpp/OcvDnnDetection/plugin-files/descriptor/descriptor.json#L140)):*
> ```JSON
>           "description": "Minimum value of the QUALITY_SELECTION_PROPERTY needed to keep detection and start a track.",
>           "type": "DOUBLE",
>           "defaultValue": "detection.quality.selection.threshold"
> ```

This should either be:
`"defaultValue": "0"`
or
`"propertiesKey": "detection.quality.selection.threshold"`
___
*[`cpp/OcvYoloDetection/Config.cpp` line 96 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/350#-NsJ13L5Co3UypGMpRRp:-NsJ13L5Co3UypGMpRRq:b-eig14y) ([raw file](https://github.com/openmpf/openmpf-components/blob/7dfeacc06ed9ef7492129f7cdbb7d116e35fb234/cpp/OcvYoloDetection/Config.cpp#L96)):*
> ```cpp
>             std::string quality_property = GetProperty(jobProps, "QUALITY_SELECTION_PROPERTY", "CONFIDENCE");
>             if (quality_property != "CONFIDENCE") {
>                 throw std::runtime_error("Unsupported quality selection property \"" + quality_property + "\". Only CONFIDENCE is supported for quality selection.");
> ```

This should throw `MPFInvalidPropertyException`.
___
*[`python/EastTextDetection/east_component/east_component.py` line 60 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/350#-NsJ1L_X16qeHJsEZu5I:-NsJ1L_X16qeHJsEZu5J:b-elbskv) ([raw file](https://github.com/openmpf/openmpf-components/blob/7dfeacc06ed9ef7492129f7cdbb7d116e35fb234/python/EastTextDetection/east_component/east_component.py#L60)):*
> ```Python
>         quality_property = props.get('QUALITY_SELECTION_PROPERTY', 'CONFIDENCE')
>         if quality_property != "CONFIDENCE":
>             raise ValueError('Unsupported quality selection property \"' + quality_property + '\". Only CONFIDENCE is supported.')
> ```

This should raise `mpf.DetectionError.INVALID_PROPERTY.exception('Unsupported quality selection ...')`

**Review by clnowacki — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/350)* status: 9 of 14 files reviewed, 4 unresolved discussions (waiting on @brosenberg42 and @jrobble)

___
*[`cpp/OcvDnnDetection/OcvDnnDetection.cpp` line 674 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/350#-NsJ0jw--Yw_l48diNIb:-NsTUBmG63N-1E1QhjKc:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/7dfeacc06ed9ef7492129f7cdbb7d116e35fb234/cpp/OcvDnnDetection/OcvDnnDetection.cpp#L674)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

We should be throwing `MPFInvalidPropertyException` in this case. For example:
```c++
throw MPFInvalidPropertyException(
    "QUALITY_SELECTION_PROPERTY",
    "Unrecognized quality selection property \"" 
        + quality_property + "\". Only CONFIDENCE is supported for quality selection."
);
```
</blockquote></details>

Done.
___
*[`cpp/OcvDnnDetection/plugin-files/descriptor/descriptor.json` line 140 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/350#-NsIyZ-q7UwDXxozTiQl:-NsTUYYzDLErzoRtZ4Fx:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/7dfeacc06ed9ef7492129f7cdbb7d116e35fb234/cpp/OcvDnnDetection/plugin-files/descriptor/descriptor.json#L140)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

This should either be:
`"defaultValue": "0"`
or
`"propertiesKey": "detection.quality.selection.threshold"`
</blockquote></details>

Done.
___
*[`cpp/OcvYoloDetection/Config.cpp` line 96 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/350#-NsJ13L5Co3UypGMpRRp:-NsTUaMb9iqA_Nz0gKej:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/7dfeacc06ed9ef7492129f7cdbb7d116e35fb234/cpp/OcvYoloDetection/Config.cpp#L96)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

This should throw `MPFInvalidPropertyException`.
</blockquote></details>

Done.
___
*[`python/EastTextDetection/east_component/east_component.py` line 60 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/350#-NsJ1L_X16qeHJsEZu5I:-NsTUuC6-0DedthtAofU:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/7dfeacc06ed9ef7492129f7cdbb7d116e35fb234/python/EastTextDetection/east_component/east_component.py#L60)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

This should raise `mpf.DetectionError.INVALID_PROPERTY.exception('Unsupported quality selection ...')`
</blockquote></details>

Done.

**Review by brosenberg42 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/350)* status: 12 of 14 files reviewed, 1 unresolved discussion (waiting on @clnowacki and @jrobble)

___
*[`cpp/OcvDnnDetection/OcvDnnDetection.cpp` line 674 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/350#-NsJ0jw--Yw_l48diNIb:-NsUB8aRBCZxNV1_tZen:b-78b2uu) ([raw file](https://github.com/openmpf/openmpf-components/blob/7dfeacc06ed9ef7492129f7cdbb7d116e35fb234/cpp/OcvDnnDetection/OcvDnnDetection.cpp#L674)):*
In the example in my comment, I pass `"QUALITY_SELECTION_PROPERTY"` as the first argument. The first argument to `MPFInvalidPropertyException` is the property name and the second is the message. `MPFInvalidPropertyException` creates the .what() message with: `"The " + propertyName + " job property contained an invalid value. " + reason`.

Currently, the .what() message is:
> The Unrecognized quality selection property "<quality_property>". Only CONFIDENCE is supported for quality selection. job property contained an invalid value.

This is only an issue for the C++ code. The way you did in Python is correct.
___
*[`cpp/OcvYoloDetection/Config.cpp` line 96 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/350#-NsJ13L5Co3UypGMpRRp:-NsUDjSIA1n5V7G6ud2m:bu228pf) ([raw file](https://github.com/openmpf/openmpf-components/blob/7dfeacc06ed9ef7492129f7cdbb7d116e35fb234/cpp/OcvYoloDetection/Config.cpp#L96)):*
<details><summary><i>Previously, clnowacki wrote…</i></summary><blockquote>

Done.
</blockquote></details>

The first parameter to MPFInvalidPropertyException should be the name of the property.

**Review by clnowacki — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/350)* status: 12 of 14 files reviewed, 1 unresolved discussion (waiting on @brosenberg42 and @jrobble)

___
*[`cpp/OcvYoloDetection/Config.cpp` line 96 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/350#-NsJ13L5Co3UypGMpRRp:-NsUMhYw-s70YF2TMkhR:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/7dfeacc06ed9ef7492129f7cdbb7d116e35fb234/cpp/OcvYoloDetection/Config.cpp#L96)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

The first parameter to MPFInvalidPropertyException should be the name of the property.
</blockquote></details>

Done.

**Review by brosenberg42 — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/350)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jrobble)

**Pull request merged**
