### PR TITLE
Add CUDA support to Darknet component

### PR DESCRIPTION
**Pull request by brosenberg42**
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/58)

### CODE REVIEW

**Comment by jrobble** [comment]
Reviewed 16 of 17 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[cpp/DarknetDetection/CMakeLists.txt, line 44 at r1](https://beta.reviewable.io/reviews/openmpf/openmpf-components/58#-L9QVEHP1K7OehrpPPMk:-L9QVEHP1K7OehrpPPMl:be6evv9) ([raw file](https://github.com/openmpf/openmpf-components/blob/b1760f09b8280c97ecdd76f40b80f4c50c36f58b/cpp/DarknetDetection/CMakeLists.txt#L44)):*
> ```CMake
> get_plugin_build_location(DarknetDetection pluginLocation)
> 
> if (DEFINED ENV{MPF_DISABLE_CUDA_BUILD})
> ```

How is MPF_DISABLE_CUDA_BUILD used in practice? How have you been using it? 

---

*[cpp/DarknetDetection/DarknetDetection.cpp, line 128 at r1](https://beta.reviewable.io/reviews/openmpf/openmpf-components/58#-L9QlQ1pDgF2YziiI0o8:-L9QlQ1pDgF2YziiI0o9:b-o7bcee) ([raw file](https://github.com/openmpf/openmpf-components/blob/b1760f09b8280c97ecdd76f40b80f4c50c36f58b/cpp/DarknetDetection/DarknetDetection.cpp#L128)):*
> ```cpp
> 
>         MPFImageReader image_reader(job);
>         int number_of_classifications
> ```

`number_of_classifications` is only used in the `else` below. Can we leave it there? 

It's still in the `else` in `DarknetDetection::GetDetections(const MPFVideoJob &job, std::vector<MPFVideoTrack> &tracks)`.

---

*[cpp/DarknetDetection/darknet_lib/CMakeLists.txt, line 94 at r1](https://beta.reviewable.io/reviews/openmpf/openmpf-components/58#-L9QWsM3EUNEBW1sHThr:-L9QWsM3EUNEBW1sHThs:bjox4nl) ([raw file](https://github.com/openmpf/openmpf-components/blob/b1760f09b8280c97ecdd76f40b80f4c50c36f58b/cpp/DarknetDetection/darknet_lib/CMakeLists.txt#L94)):*
> ```CMake
> 
> 
> if (CUDA_FOUND)
> ```

So this will not be set unless you tried to find CUDA in the top-level CMakeLists.txt for this component, right?

I'm wondering if we should define our own variable for this purpose, for clarity and to potentially prevent future build problems. What if another component, or aspect of OpenMPF, gets built before this one that uses CUDA? Will that define CUDA_FOUND before this component is even built?

---

*[cpp/DarknetDetection/darknet_lib/CMakeLists.txt, line 109 at r1](https://beta.reviewable.io/reviews/openmpf/openmpf-components/58#-L9QYvmJE-FUVVdxjCr6:-L9QYvmJE-FUVVdxjCr7:b-4lw2vs) ([raw file](https://github.com/openmpf/openmpf-components/blob/b1760f09b8280c97ecdd76f40b80f4c50c36f58b/cpp/DarknetDetection/darknet_lib/CMakeLists.txt#L109)):*
> ```CMake
> 
>     find_package(CUDA REQUIRED)
>     set(CUDA_NVCC_FLAGS -DGPU -DOPENCV --compiler-options -fPIC )
> ```

I found this in the [Darknet Makefile](https://github.com/pjreddie/darknet/blob/cd5d393b46b59dc72a5150436e70fa91a2918b2d/Makefile#L7):

```
ARCH= -gencode arch=compute_30,code=sm_30 \
      -gencode arch=compute_35,code=sm_35 \
      -gencode arch=compute_50,code=[sm_50,compute_50] \
      -gencode arch=compute_52,code=[sm_52,compute_52]
#      -gencode arch=compute_20,code=[sm_20,sm_21] \ This one is deprecated?
```

I don't see these options represented anywhere in the Darknet component code. Am I missing something?

If not, would we need to set these options using CUDA_NVCC_FLAGS?

I'm asking for future reference, since this will be addressed in https://github.com/openmpf/openmpf/issues/530.

---

*[cpp/DarknetDetection/darknet_lib/include/darknet.h, line 717 at r1](https://beta.reviewable.io/reviews/openmpf/openmpf-components/58#-L9QbLg2BX365Ert5Un1:-L9QbLg2BX365Ert5Un2:b-vaxici) ([raw file](https://github.com/openmpf/openmpf-components/blob/bfaf2d2fe27407638cc71e5cebfdaa3293be7006/cpp/DarknetDetection/darknet_lib/include/darknet.h#L717)):*
> ```objc
> int num_boxes(network *net);
> box *make_boxes(network *net);
> float **make_probs(network *net);
> ```

Why this modification?

---

*[cpp/DarknetDetection/darknet_lib/src/image.h, line 22 at r1](https://beta.reviewable.io/reviews/openmpf/openmpf-components/58#-L9QazP27MCEVoMRG53X:-L9QazP27MCEVoMRG53Y:b-3ns5f1) ([raw file](https://github.com/openmpf/openmpf-components/blob/bfaf2d2fe27407638cc71e5cebfdaa3293be7006/cpp/DarknetDetection/darknet_lib/src/image.h#L22)):*
> ```objc
> #endif
> 
> // ----
> ```

Is this something you added? Just wondering because I remember you said you'd like to try to avoid modifying the original Darknet code.

---

*[cpp/DarknetDetection/darknet_wrapper/DarknetImpl.cpp, line 333 at r1](https://beta.reviewable.io/reviews/openmpf/openmpf-components/58#-L9Qpf1d1Ikcq0cC1qDN:-L9Qpf1d1Ikcq0cC1qDO:bto7p8e) ([raw file](https://github.com/openmpf/openmpf-components/blob/b1760f09b8280c97ecdd76f40b80f4c50c36f58b/cpp/DarknetDetection/darknet_wrapper/DarknetImpl.cpp#L333)):*
> ```cpp
> 
> 
> extern "C" {
> ```

Why does this need the `extern`?

---

*[cpp/DarknetDetection/plugin-files/descriptor/descriptor.json, line 172 at r1](https://beta.reviewable.io/reviews/openmpf/openmpf-components/58#-L9QkSXM5j7kSYmmQsvZ:-L9QkSXM5j7kSYmmQsv_:b-t27o6n) ([raw file](https://github.com/openmpf/openmpf-components/blob/b1760f09b8280c97ecdd76f40b80f4c50c36f58b/cpp/DarknetDetection/plugin-files/descriptor/descriptor.json#L172)):*
Add this as the first line of this description:

> Only applies if USE_PREPROCESSOR is false.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/openmpf/openmpf-components/58)*

**Comment by brosenberg42** [comment]
Review status: 13 of 15 files reviewed at latest revision, 8 unresolved discussions.

---

*[cpp/DarknetDetection/CMakeLists.txt, line 44 at r1](https://beta.reviewable.io/reviews/openmpf/openmpf-components/58#-L9QVEHP1K7OehrpPPMk:-L9QwVwD-rThrZ3fopjw:b-85i8kh) ([raw file](https://github.com/openmpf/openmpf-components/blob/b1760f09b8280c97ecdd76f40b80f4c50c36f58b/cpp/DarknetDetection/CMakeLists.txt#L44)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

How is MPF_DISABLE_CUDA_BUILD used in practice? How have you been using it? 
</blockquote></details>

I have CUDA installed but most of the time I don't need to build the CUDA version when I am testing on my local VM. The environment variable can be set anywhere. I set it in `~/.bashrc`.  

---

*[cpp/DarknetDetection/DarknetDetection.cpp, line 128 at r1](https://beta.reviewable.io/reviews/openmpf/openmpf-components/58#-L9QlQ1pDgF2YziiI0o8:-L9RJ_wQ6W4rNnrd2FTO:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/b1760f09b8280c97ecdd76f40b80f4c50c36f58b/cpp/DarknetDetection/DarknetDetection.cpp#L128)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

`number_of_classifications` is only used in the `else` below. Can we leave it there? 

It's still in the `else` in `DarknetDetection::GetDetections(const MPFVideoJob &job, std::vector<MPFVideoTrack> &tracks)`.
</blockquote></details>

Done.

---

*[cpp/DarknetDetection/darknet_lib/CMakeLists.txt, line 94 at r1](https://beta.reviewable.io/reviews/openmpf/openmpf-components/58#-L9QWsM3EUNEBW1sHThr:-L9RAhUKDSlwRv3Xwo7c:b-tozjwa) ([raw file](https://github.com/openmpf/openmpf-components/blob/b1760f09b8280c97ecdd76f40b80f4c50c36f58b/cpp/DarknetDetection/darknet_lib/CMakeLists.txt#L94)):*
> So this will not be set unless you tried to find CUDA in the top-level CMakeLists.txt for this component, right?

That is correct.

> Will that define CUDA_FOUND before this component is even built?

It will. 

I'm not opposed to adding the variable, I just don't understand why the situation you mentioned is an issue.

---

*[cpp/DarknetDetection/darknet_lib/CMakeLists.txt, line 109 at r1](https://beta.reviewable.io/reviews/openmpf/openmpf-components/58#-L9QYvmJE-FUVVdxjCr6:-L9RBea47lrPUcARXNwA:b-yug4iv) ([raw file](https://github.com/openmpf/openmpf-components/blob/b1760f09b8280c97ecdd76f40b80f4c50c36f58b/cpp/DarknetDetection/darknet_lib/CMakeLists.txt#L109)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

I found this in the [Darknet Makefile](https://github.com/pjreddie/darknet/blob/cd5d393b46b59dc72a5150436e70fa91a2918b2d/Makefile#L7):

```
ARCH= -gencode arch=compute_30,code=sm_30 \
      -gencode arch=compute_35,code=sm_35 \
      -gencode arch=compute_50,code=[sm_50,compute_50] \
      -gencode arch=compute_52,code=[sm_52,compute_52]
#      -gencode arch=compute_20,code=[sm_20,sm_21] \ This one is deprecated?
```

I don't see these options represented anywhere in the Darknet component code. Am I missing something?

If not, would we need to set these options using CUDA_NVCC_FLAGS?

I'm asking for future reference, since this will be addressed in https://github.com/openmpf/openmpf/issues/530.
</blockquote></details>

I did not set the `-gencode` options anywhere, but it still worked on the GPU. I was leaving the fine tuning for  [openmpf/openmpf#530](https://github.com/openmpf/openmpf/issues/530).  I am pretty sure that modifying `CUDA_NVCC_FLAGS` will allow you to set those options. I added a comment to that issue including a link to the documentation for those variables.

---

*[cpp/DarknetDetection/darknet_lib/include/darknet.h, line 717 at r1](https://beta.reviewable.io/reviews/openmpf/openmpf-components/58#-L9QbLg2BX365Ert5Un1:-L9QvfrjARkDcIMHEDzj:bqdzbv0) ([raw file](https://github.com/openmpf/openmpf-components/blob/bfaf2d2fe27407638cc71e5cebfdaa3293be7006/cpp/DarknetDetection/darknet_lib/include/darknet.h#L717)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Why this modification?
</blockquote></details>

I added that when I was originally debugging some darknet stuff and forgot to remove it.

---

*[cpp/DarknetDetection/darknet_lib/src/image.h, line 14 at r1](https://beta.reviewable.io/reviews/openmpf/openmpf-components/58#-L9QwIc74G4nBGQCG4Hm:-L9QwIc74G4nBGQCG4Hn:b-o3ffgh) ([raw file](https://github.com/openmpf/openmpf-components/blob/bfaf2d2fe27407638cc71e5cebfdaa3293be7006/cpp/DarknetDetection/darknet_lib/src/image.h#L14)):*
> ```objc
> #ifndef __cplusplus
> #ifdef OPENCV
> int fill_image_from_stream(CvCapture *cap, image im);
> ```

This is where I copied the declarations from.

---

*[cpp/DarknetDetection/darknet_lib/src/image.h, line 22 at r1](https://beta.reviewable.io/reviews/openmpf/openmpf-components/58#-L9QazP27MCEVoMRG53X:-L9Qvx0aBF0dC1hyJZ1n:b-jtevcp) ([raw file](https://github.com/openmpf/openmpf-components/blob/bfaf2d2fe27407638cc71e5cebfdaa3293be7006/cpp/DarknetDetection/darknet_lib/src/image.h#L22)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Is this something you added? Just wondering because I remember you said you'd like to try to avoid modifying the original Darknet code.
</blockquote></details>

I did add that. I tried to remind myself to remove it, that is why there is the `//----` comments. Those exact declarations are just above here, but they are inside of some #ifdef's.

---

*[cpp/DarknetDetection/darknet_wrapper/DarknetImpl.cpp, line 333 at r1](https://beta.reviewable.io/reviews/openmpf/openmpf-components/58#-L9Qpf1d1Ikcq0cC1qDN:-L9R--pQ61cifcc7BAUK:buv614d) ([raw file](https://github.com/openmpf/openmpf-components/blob/b1760f09b8280c97ecdd76f40b80f4c50c36f58b/cpp/DarknetDetection/darknet_wrapper/DarknetImpl.cpp#L333)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Why does this need the `extern`?
</blockquote></details>

You need to do that when you want to call a C++ function using dlsym. If you don't have `extern "C"` around the function, the C++ compiler will mangle the function name.
With dlsym, you need to pass in the name of function you want to call as a string which is difficult if its name has been mangled.

---

*[cpp/DarknetDetection/plugin-files/descriptor/descriptor.json, line 172 at r1](https://beta.reviewable.io/reviews/openmpf/openmpf-components/58#-L9QkSXM5j7kSYmmQsvZ:-L9RJd2RDMrj_iARvI5z:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/b1760f09b8280c97ecdd76f40b80f4c50c36f58b/cpp/DarknetDetection/plugin-files/descriptor/descriptor.json#L172)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Add this as the first line of this description:

> Only applies if USE_PREPROCESSOR is false.

</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/openmpf/openmpf-components/58)*

**Comment by jrobble** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[cpp/DarknetDetection/CMakeLists.txt, line 44 at r1](https://beta.reviewable.io/reviews/openmpf/openmpf-components/58#-L9QVEHP1K7OehrpPPMk:-L9RRH8xD236q2Q7y9fe:b5vmboy) ([raw file](https://github.com/openmpf/openmpf-components/blob/b1760f09b8280c97ecdd76f40b80f4c50c36f58b/cpp/DarknetDetection/CMakeLists.txt#L44)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

I have CUDA installed but most of the time I don't need to build the CUDA version when I am testing on my local VM. The environment variable can be set anywhere. I set it in `~/.bashrc`.  
</blockquote></details>

I see. It's worth adding this to the docs you're putting together.

---

*[cpp/DarknetDetection/darknet_lib/CMakeLists.txt, line 94 at r1](https://beta.reviewable.io/reviews/openmpf/openmpf-components/58#-L9QWsM3EUNEBW1sHThr:-L9RRglE0yTKLZVVwa81:b-cmee5e) ([raw file](https://github.com/openmpf/openmpf-components/blob/b1760f09b8280c97ecdd76f40b80f4c50c36f58b/cpp/DarknetDetection/darknet_lib/CMakeLists.txt#L94)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

> So this will not be set unless you tried to find CUDA in the top-level CMakeLists.txt for this component, right?

That is correct.

> Will that define CUDA_FOUND before this component is even built?

It will. 

I'm not opposed to adding the variable, I just don't understand why the situation you mentioned is an issue.
</blockquote></details>

In the top-level CMakeLists.txt file for this component, if MPF_DISABLE_CUDA_BUILD is defined then we never run `find_package(CUDA)`. If some other aspect of OpenMPF results in running that, then the CUDA build of this component won't be disabled, even if MPF_DISABLE_CUDA_BUILD is defined.

You're depending on all other aspects of OpenMPF to respect MPF_DISABLE_CUDA_BUILD and not run `find_package(CUDA)`. I don't think it's safe to depend on other component implementations.

---

*[cpp/DarknetDetection/darknet_lib/CMakeLists.txt, line 109 at r1](https://beta.reviewable.io/reviews/openmpf/openmpf-components/58#-L9QYvmJE-FUVVdxjCr6:-L9RSiqACX4SKysxWsC5:b-haw8gt) ([raw file](https://github.com/openmpf/openmpf-components/blob/b1760f09b8280c97ecdd76f40b80f4c50c36f58b/cpp/DarknetDetection/darknet_lib/CMakeLists.txt#L109)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

I did not set the `-gencode` options anywhere, but it still worked on the GPU. I was leaving the fine tuning for  [openmpf/openmpf#530](https://github.com/openmpf/openmpf/issues/530).  I am pretty sure that modifying `CUDA_NVCC_FLAGS` will allow you to set those options. I added a comment to that issue including a link to the documentation for those variables.
</blockquote></details>

Thanks for dropping a comment on that issue.

---

*[cpp/DarknetDetection/darknet_wrapper/DarknetImpl.cpp, line 333 at r1](https://beta.reviewable.io/reviews/openmpf/openmpf-components/58#-L9Qpf1d1Ikcq0cC1qDN:-L9RT1dp8YCdhjX2lu4T:b-3fdviq) ([raw file](https://github.com/openmpf/openmpf-components/blob/b1760f09b8280c97ecdd76f40b80f4c50c36f58b/cpp/DarknetDetection/darknet_wrapper/DarknetImpl.cpp#L333)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

You need to do that when you want to call a C++ function using dlsym. If you don't have `extern "C"` around the function, the C++ compiler will mangle the function name.
With dlsym, you need to pass in the name of function you want to call as a string which is difficult if its name has been mangled.

</blockquote></details>

Thanks for the explanation. Makes sense.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/openmpf/openmpf-components/58)*

**Comment by brosenberg42** [comment]
Review status: 12 of 15 files reviewed at latest revision, 1 unresolved discussion.

---

*[cpp/DarknetDetection/darknet_lib/CMakeLists.txt, line 94 at r1](https://beta.reviewable.io/reviews/openmpf/openmpf-components/58#-L9QWsM3EUNEBW1sHThr:-L9ReZaYAmIj-biJQUBQ:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/b1760f09b8280c97ecdd76f40b80f4c50c36f58b/cpp/DarknetDetection/darknet_lib/CMakeLists.txt#L94)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

In the top-level CMakeLists.txt file for this component, if MPF_DISABLE_CUDA_BUILD is defined then we never run `find_package(CUDA)`. If some other aspect of OpenMPF results in running that, then the CUDA build of this component won't be disabled, even if MPF_DISABLE_CUDA_BUILD is defined.

You're depending on all other aspects of OpenMPF to respect MPF_DISABLE_CUDA_BUILD and not run `find_package(CUDA)`. I don't think it's safe to depend on other component implementations.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/openmpf/openmpf-components/58)*

**Comment by jrobble** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/openmpf/openmpf-components/58)*

**Comment by jrobble** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/openmpf/openmpf-components/58)*

**Pull request merged**
