### PR TITLE
Update caffe component to do shell-like file name expansion.

### PR DESCRIPTION
**Pull request by clnowacki**
added file name expansion to the hash input file processing, and added a default pipeline that computes the activation values and spectral hash for the loss3/classifier layer in the googlenet model.

also added a try/catch block in the calculation of the spectral hash to catch potential cv::Exceptions.

---
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/39)

### CODE REVIEW

**Comment by jrobble** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[cpp/CaffeDetection/CaffeDetection.cpp, line 54 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-components/39#-Kw_aHSolU7AoaicXez8:-Kw_aHSpd30QDit8SbBJ:b-t1nwnj) ([raw file](https://github.com/openmpf/openmpf-components/blob/d0d67213be2f7c03a80aa26772e1aa11f677a118/cpp/CaffeDetection/CaffeDetection.cpp#L54)):*
> ```cpp
> // Returns an error string. If it is not empty, then the filename
> // expansion failed and the exp_filename output should not be used.
> std::string expandFileName(const std::string &filename, std::string &exp_filename) {
> ```

Please add this function as a utility to the SDK. Maybe openmpf-cpp-component-sdk/detection/utils/src/Utils.cpp is the best place for it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-components/39)*

**Comment by clnowacki** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[cpp/CaffeDetection/CaffeDetection.cpp, line 54 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-components/39#-Kw_aHSolU7AoaicXez8:-Kw_dwhI4ubg6Ea9NwSb:b2nhll9) ([raw file](https://github.com/openmpf/openmpf-components/blob/d0d67213be2f7c03a80aa26772e1aa11f677a118/cpp/CaffeDetection/CaffeDetection.cpp#L54)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Please add this function as a utility to the SDK. Maybe openmpf-cpp-component-sdk/detection/utils/src/Utils.cpp is the best place for it.
</blockquote></details>

Ok.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-components/39)*

**Comment by jrobble** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[cpp/CaffeDetection/plugin-files/descriptor/descriptor.json, line 231 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-components/39#-Kw_qUYqTqem8RmF2DP0:-Kw_qUYr7_CuKVy2IVKC:b-jxrmg1) ([raw file](https://github.com/openmpf/openmpf-components/blob/d0d67213be2f7c03a80aa26772e1aa11f677a118/cpp/CaffeDetection/plugin-files/descriptor/descriptor.json#L231)):*
> ```JSON
>     },
>     {
>       "name": "CAFFE GOOGLENET DETECTION WITH LOSS3/CLASSIFIER LAYER ACTIVATION VALUES AND SPECTRAL HASH ACTION",
> ```

To be consistent with the naming scheme in other components, let's rename this to:

"CAFFE GOOGLENET DETECTION (WITH LOSS3/CLASSIFIER LAYER ACTIVATION VALUES AND SPECTRAL HASH) ACTION"

---

*[cpp/CaffeDetection/plugin-files/descriptor/descriptor.json, line 313 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-components/39#-Kw_qhHJp4zVWiGMRPrf:-Kw_qhHJp4zVWiGMRPrg:b-4j74uz) ([raw file](https://github.com/openmpf/openmpf-components/blob/d0d67213be2f7c03a80aa26772e1aa11f677a118/cpp/CaffeDetection/plugin-files/descriptor/descriptor.json#L313)):*
> ```JSON
>     },
>     {
>       "name": "CAFFE GOOGLENET DETECTION WITH LOSS3/CLASSIFIER LAYER ACTIVATION VALUES AND SPECTRAL HASH TASK",
> ```

Let's rename this to:

"CAFFE GOOGLENET DETECTION (WITH LOSS3/CLASSIFIER LAYER ACTIVATION VALUES AND SPECTRAL HASH) TASK"

---

*[cpp/CaffeDetection/plugin-files/descriptor/descriptor.json, line 336 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-components/39#-Kw_qjP3IgfjtGljapJd:-Kw_qjP3IgfjtGljapJe:b-rabq0) ([raw file](https://github.com/openmpf/openmpf-components/blob/d0d67213be2f7c03a80aa26772e1aa11f677a118/cpp/CaffeDetection/plugin-files/descriptor/descriptor.json#L336)):*
> ```JSON
>     },
>     {
>       "name": "CAFFE GOOGLENET DETECTION WITH LOSS3/CLASSIFIER LAYER ACTIVATION VALUES AND SPECTRAL HASH PIPELINE",
> ```

Let's rename this to:

"CAFFE GOOGLENET DETECTION (WITH LOSS3/CLASSIFIER LAYER ACTIVATION VALUES AND SPECTRAL HASH) PIPELINE"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-components/39)*

**Comment by jrobble** [comment]
I'll leave it to @brosenberg42 to double-check that the merge went well.

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-components/39#-:-KwcUFST7ah-iLx4jQmy:bmuxoaa)*

**Comment by brosenberg42** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[cpp/CaffeDetection/CaffeDetection.cpp, line 386 at r2](https://reviewable.io:443/reviews/openmpf/openmpf-components/39#-Kwel6aXdYH61sc3SNwO:-Kwel6aXdYH61sc3SNwP:b-m3pj7y) ([raw file](https://github.com/openmpf/openmpf-components/blob/a1b777926cba19992f8db93a9fee4dee345b99aa/cpp/CaffeDetection/CaffeDetection.cpp#L386)):*
> ```cpp
>         else {
>             config.bad_hash_file_names.push_back(hash_info_pair.first.file_name);
>         }
> ```

It would be better to put the try-catch up from `computeSpectralHash` here. That way you don't need to check for the error twice (first with the catch and second with `hash_output_pair.second.empty())`). You also need to check if the bad file name already exists in `config.bad_hash_file_names` before adding it or else it will be added multiple times when running video jobs.
So this could be:
```
for (const auto& hash_info_pair : spectral_hash_mats) {
    try {
        detection_properties.emplace(computeSpectralHash(hash_info_pair.second, hash_info_pair.first));
    }
    catch (const cv::Exception &err) {
        LOG4CXX_ERROR(logger_, "OpenCV exception caught while calculating the spectral hash for layer \""
                << hash_info_pair.first.layer_name << "\" in model named \""
                << hash_info_pair.first.model_name << "\": " << err.what());
        
        const std::string &bad_file_name = hash_info_pair.first.file_name;
        if (std::find(config.bad_hash_file_names.begin(), config.bad_hash_file_names.end(), bad_file_name)
                    == config.bad_hash_file_names.end()) {
            config.bad_hash_file_names.push_back(bad_file_name);
        }
    }
}
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-components/39)*

**Comment by clnowacki** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[cpp/CaffeDetection/CaffeDetection.cpp, line 386 at r2](https://reviewable.io:443/reviews/openmpf/openmpf-components/39#-Kwel6aXdYH61sc3SNwO:-KweqFQr6QG4vKrarRoS:b-y8sfpy) ([raw file](https://github.com/openmpf/openmpf-components/blob/a1b777926cba19992f8db93a9fee4dee345b99aa/cpp/CaffeDetection/CaffeDetection.cpp#L386)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

It would be better to put the try-catch up from `computeSpectralHash` here. That way you don't need to check for the error twice (first with the catch and second with `hash_output_pair.second.empty())`). You also need to check if the bad file name already exists in `config.bad_hash_file_names` before adding it or else it will be added multiple times when running video jobs.
So this could be:
```
for (const auto& hash_info_pair : spectral_hash_mats) {
    try {
        detection_properties.emplace(computeSpectralHash(hash_info_pair.second, hash_info_pair.first));
    }
    catch (const cv::Exception &err) {
        LOG4CXX_ERROR(logger_, "OpenCV exception caught while calculating the spectral hash for layer \""
                << hash_info_pair.first.layer_name << "\" in model named \""
                << hash_info_pair.first.model_name << "\": " << err.what());
        
        const std::string &bad_file_name = hash_info_pair.first.file_name;
        if (std::find(config.bad_hash_file_names.begin(), config.bad_hash_file_names.end(), bad_file_name)
                    == config.bad_hash_file_names.end()) {
            config.bad_hash_file_names.push_back(bad_file_name);
        }
    }
}
```
</blockquote></details>

Ok, much better.

---

*[cpp/CaffeDetection/plugin-files/descriptor/descriptor.json, line 231 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-components/39#-Kw_qUYqTqem8RmF2DP0:-Kweqm0fC66RH6XuPfXE:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/d0d67213be2f7c03a80aa26772e1aa11f677a118/cpp/CaffeDetection/plugin-files/descriptor/descriptor.json#L231)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

To be consistent with the naming scheme in other components, let's rename this to:

"CAFFE GOOGLENET DETECTION (WITH LOSS3/CLASSIFIER LAYER ACTIVATION VALUES AND SPECTRAL HASH) ACTION"
</blockquote></details>

Done.

---

*[cpp/CaffeDetection/plugin-files/descriptor/descriptor.json, line 313 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-components/39#-Kw_qhHJp4zVWiGMRPrf:-Kweqm_bxmhb--7S1Bm6:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/d0d67213be2f7c03a80aa26772e1aa11f677a118/cpp/CaffeDetection/plugin-files/descriptor/descriptor.json#L313)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Let's rename this to:

"CAFFE GOOGLENET DETECTION (WITH LOSS3/CLASSIFIER LAYER ACTIVATION VALUES AND SPECTRAL HASH) TASK"
</blockquote></details>

Done.

---

*[cpp/CaffeDetection/plugin-files/descriptor/descriptor.json, line 336 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-components/39#-Kw_qjP3IgfjtGljapJd:-Kweqn0z-nZLMxwEPI6N:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/d0d67213be2f7c03a80aa26772e1aa11f677a118/cpp/CaffeDetection/plugin-files/descriptor/descriptor.json#L336)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Let's rename this to:

"CAFFE GOOGLENET DETECTION (WITH LOSS3/CLASSIFIER LAYER ACTIVATION VALUES AND SPECTRAL HASH) PIPELINE"
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-components/39)*

**Comment by clnowacki** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[cpp/CaffeDetection/CaffeDetection.cpp, line 386 at r2](https://reviewable.io:443/reviews/openmpf/openmpf-components/39#-Kwel6aXdYH61sc3SNwO:-Kwet6RzBo_EctYJLyN2:b-23grlu) ([raw file](https://github.com/openmpf/openmpf-components/blob/a1b777926cba19992f8db93a9fee4dee345b99aa/cpp/CaffeDetection/CaffeDetection.cpp#L386)):*
<details><summary><i>Previously, clnowacki wrote…</i></summary><blockquote>

Ok, much better.
</blockquote></details>

I don't think I need to check whether the file name is already in the list, since we never would have gotten this far if it was found to be bad earlier.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-components/39)*

**Comment by brosenberg42** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[cpp/CaffeDetection/CaffeDetection.cpp, line 386 at r2](https://reviewable.io:443/reviews/openmpf/openmpf-components/39#-Kwel6aXdYH61sc3SNwO:-KwexHIYbcYpO42fOCJw:b9rhw54) ([raw file](https://github.com/openmpf/openmpf-components/blob/a1b777926cba19992f8db93a9fee4dee345b99aa/cpp/CaffeDetection/CaffeDetection.cpp#L386)):*
<details><summary><i>Previously, clnowacki wrote…</i></summary><blockquote>

I don't think I need to check whether the file name is already in the list, since we never would have gotten this far if it was found to be bad earlier.
</blockquote></details>

If it was found to be bad earlier, we will not try to compute the spectral hash for that path, but the earlier check handles cases where the JSON file couldn't be loaded or was missing parameters. This exception would be thrown if the computation of the spectral hash fails.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-components/39)*

**Comment by clnowacki** [comment]
Reviewed 1 of 3 files at r2.
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[cpp/CaffeDetection/CaffeDetection.cpp, line 386 at r2](https://reviewable.io:443/reviews/openmpf/openmpf-components/39#-Kwel6aXdYH61sc3SNwO:-KwfLORCFmIbA5t3RXoB:b-5glvd9) ([raw file](https://github.com/openmpf/openmpf-components/blob/a1b777926cba19992f8db93a9fee4dee345b99aa/cpp/CaffeDetection/CaffeDetection.cpp#L386)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

If it was found to be bad earlier, we will not try to compute the spectral hash for that path, but the earlier check handles cases where the JSON file couldn't be loaded or was missing parameters. This exception would be thrown if the computation of the spectral hash fails.
</blockquote></details>

Ok, I reread your original comment more carefully. It's the part about video jobs that I failed to grasp: it would be added for every frame in the video. I will fix this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-components/39)*

**Comment by brosenberg42** [comment]
:lgtm:

---

Reviewed 2 of 3 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-components/39#-:-KwfZPHv6RTVSStrppvO:bnfp4nl)*

**Pull request merged**
