### PR TITLE
creating transformer sentence tagging component

### PR DESCRIPTION
**Pull request by jrobble**
**Issues:**

- https://github.com/openmpf/openmpf/issues/1692

- - -
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/337)

### CODE REVIEW

**Review by jrobble — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/337)* status: 0 of 12 files reviewed, 6 unresolved discussions (waiting on @hhuangMITRE)

___
*[`python/TransformerTagging/plugin-files/descriptor/descriptor.json` line 26 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/337#-NePhwAR8Ajr4310JSH5:-NePhwAR8Ajr4310JSH6:bo1kjk3) ([raw file](https://github.com/openmpf/openmpf-components/blob/784fd041115d2bb7b02bc5e25dc32b880f5de791/python/TransformerTagging/plugin-files/descriptor/descriptor.json#L26)):*
> ```JSON
>           "description": "Comma-separated list of property names indicating which properties in the feed-forward track or detection to consider translating. If the first property listed is present, then that property will be translated. If it's not, then the next property in the list is considered. At most, one property will be translated.",
>           "type": "STRING",
>           "defaultValue": "TEXT,TRANSCRIPT"
> ```

Add `TRANSLATION`.
___
*[`python/TransformerTagging/tests/test_transformer_tagging.py` line 198 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/337#-NePf5rnA4Q58DLHXFus:-NePf5rnA4Q58DLHXFut:bcsucqz) ([raw file](https://github.com/openmpf/openmpf-components/blob/784fd041115d2bb7b02bc5e25dc32b880f5de791/python/TransformerTagging/tests/test_transformer_tagging.py#L198)):*
> ```Python
>         result = comp.get_detections_from_image(job)
> 
>         self.assertEqual(1, len(result))
> ```

Let's assert the standard things like:

```python
self.assertEqual(SHORT_SAMPLE_TAGS, props["TAGS"])
self.assertEqual(SHORT_SAMPLE_TRIGGER_SENTENCES, props["TEXT TRAVEL TRIGGER SENTENCES"])
self.assertEqual(SHORT_SAMPLE_OFFSET, props["TEXT TRAVEL TRIGGER SENTENCES OFFSET"])
self.assertEqual(SHORT_SAMPLE_SCORE, props["TEXT TRAVEL TRIGGER SENTENCES SCORE"])
```

But, minimally, use a different TAG than what's used in the default corpus.
___
*[`python/TransformerTagging/tests/config/transformer_text_tags_corpus.json` line 1 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/337#-NePg2S434aANKQjXoPs:-NePg2S434aANKQjXoPt:b1nkb1l) ([raw file](https://github.com/openmpf/openmpf-components/blob/784fd041115d2bb7b02bc5e25dc32b880f5de791/python/TransformerTagging/tests/config/transformer_text_tags_corpus.json#L1)):*
> ```JSON
> [
> ```

I don't think this file is necessary. The version in `transformer_tagging_component/` should be enough.
___
*[`python/TransformerTagging/transformer_tagging_component/transformer_tagging_component.py` line 119 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/337#-NePhbJO2wGhSIPD38Ve:-NePhbJO2wGhSIPD38Vf:bo1kjk3) ([raw file](https://github.com/openmpf/openmpf-components/blob/784fd041115d2bb7b02bc5e25dc32b880f5de791/python/TransformerTagging/transformer_tagging_component/transformer_tagging_component.py#L119)):*
> ```Python
>                 properties=job_props,
>                 key='FEED_FORWARD_PROP_TO_PROCESS',
>                 default_value='TEXT,TRANSCRIPT',
> ```

Add `TRANSLATION`.
___
*[`python/TransformerTagging/transformer_tagging_component/transformer_tagging_component.py` line 161 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/337#-NePj1qL0HGoNpXJa5Zz:-NePj1qL0HGoNpXJa5_-:bg7dlh0) ([raw file](https://github.com/openmpf/openmpf-components/blob/784fd041115d2bb7b02bc5e25dc32b880f5de791/python/TransformerTagging/transformer_tagging_component/transformer_tagging_component.py#L161)):*
> ```Python
>             return
> 
>         input_sentences = sent_tokenize(input_text)
> ```

How does this handle this kind of text?

```
This is a sentence
of a good dog.
```

Is that parsed out as one or two sentences?

Initially, I was thinking that we'd want that to be one sentence because that's how we handle single newlines for breaking up large text for Azure translation, but it may actually be more beneficial for sentence matching to error on the side of smaller rather than larger sentences. It needs to handle partial phrases anyway.
___
*[`python/TransformerTagging/transformer_tagging_component/transformer_text_tags_corpus.json` line 55 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/337#-NePfxSj0rtpzWXlahwL:-NePfxSj0rtpzWXlahwM:bv75ll2) ([raw file](https://github.com/openmpf/openmpf-components/blob/784fd041115d2bb7b02bc5e25dc32b880f5de791/python/TransformerTagging/transformer_tagging_component/transformer_text_tags_corpus.json#L55)):*
> ```JSON
>   },
>   {
>     "text": "This sentence is financ.",
> ```

Check spelling: "financ"

Make same change to custom corpus.

**Comment by jrobble** [comment]
*[`python/TransformerTagging/sample_transformer_tagger.py` line 35 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/337#-NeQiCORAhnTQ2Nj6OPC:-NeQiCORAhnTQ2Nj6OPD:b-5kjkwz) ([raw file](https://github.com/openmpf/openmpf-components/blob/784fd041115d2bb7b02bc5e25dc32b880f5de791/python/TransformerTagging/sample_transformer_tagger.py#L35)):*
> ```Python
> def main():
>     wrapper = TransformerWrapper({})
>     detection_props = dict(TEXT="I also have a knife. I have a gun. I took a plane to Florida. I bought some cocaine. "
> ```

We've moved away from using "sample" files like this. It's no longer required since we can do stand-alone testing using the CLI Runner (once the component is Dockerized). If a dev wants to try something out they can modify a unit test.

**Comment by jrobble** [comment]
*[`python/TransformerTagging/tests/data/multiple_tags.txt` line 1 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/337#-NeQtBuZ0qc4wisrwljb:-NeQtBuZ0qc4wisrwljc:bgc0obj) ([raw file](https://github.com/openmpf/openmpf-components/blob/784fd041115d2bb7b02bc5e25dc32b880f5de791/python/TransformerTagging/tests/data/multiple_tags.txt#L1)):*
> ```help
> Vehicles include wagons, bicycles, motor vehicles (motorcycles, cars, trucks, buses, mobility scooters for disabled people), railed vehicles (trains, trams), watercraft (ships, boats, underwater vehicles), amphibious vehicles (screw-propelled vehicles, hovercraft), aircraft (airplanes, helicopters, aerostats) and spacecraft. "An automated teller machine (ATM) is an electronic telecommunications device that enables customers of financial institutions to perform financial transactions, such as cash withdrawals, deposits, funds transfers, balance inquiries or account information inquiries, at any time and without the need for direct interaction with bank staff. The advent of widespread text-messaging has resulted in the cell phone novel, the first literary genre to emerge from the cellular age, via text messaging to a website that collects the novels as a whole. The sword developed from the knife or dagger. A passport holder is normally entitled to enter the country that issued the passport, though some people entitled to a passport may not be full citizens with right of abode (e.g. American nationals or British nationals). "A number of hotels and motels have entered the public consciousness through popular culture.
> ```

This is unused.

**Review by jrobble — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/337)* status: 0 of 12 files reviewed, 6 unresolved discussions (waiting on @hhuangMITRE)

___
*[`python/TransformerTagging/sample_transformer_tagger.py` line 35 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/337#-NeQiCORAhnTQ2Nj6OPC:-NeQv4r13CIdIAJcRnaU:b-dmxzd4) ([raw file](https://github.com/openmpf/openmpf-components/blob/784fd041115d2bb7b02bc5e25dc32b880f5de791/python/TransformerTagging/sample_transformer_tagger.py#L35)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

We've moved away from using "sample" files like this. It's no longer required since we can do stand-alone testing using the CLI Runner (once the component is Dockerized). If a dev wants to try something out they can modify a unit test.
</blockquote></details>

I removed this in my commit.
___
*[`python/TransformerTagging/tests/config/transformer_text_tags_corpus.json` line 1 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/337#-NePg2S434aANKQjXoPs:-NeQv8Nf9GYOuWtN1nSM:b-dmxzd4) ([raw file](https://github.com/openmpf/openmpf-components/blob/784fd041115d2bb7b02bc5e25dc32b880f5de791/python/TransformerTagging/tests/config/transformer_text_tags_corpus.json#L1)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

I don't think this file is necessary. The version in `transformer_tagging_component/` should be enough.
</blockquote></details>

I removed this in my commit.

**Review by mcrensh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/337)* status: 0 of 12 files reviewed, 6 unresolved discussions (waiting on @hhuangMITRE and @jrobble)

___
*[`python/TransformerTagging/plugin-files/descriptor/descriptor.json` line 26 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/337#-NePhwAR8Ajr4310JSH5:-Nezkx-pD36lutj5a_QO:b-7tfmjp) ([raw file](https://github.com/openmpf/openmpf-components/blob/784fd041115d2bb7b02bc5e25dc32b880f5de791/python/TransformerTagging/plugin-files/descriptor/descriptor.json#L26)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Add `TRANSLATION`.
</blockquote></details>

added
___
*[`python/TransformerTagging/tests/test_transformer_tagging.py` line 198 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/337#-NePf5rnA4Q58DLHXFus:-NezkNHS0MuzoKRkl9lU:b-i1nfqv) ([raw file](https://github.com/openmpf/openmpf-components/blob/784fd041115d2bb7b02bc5e25dc32b880f5de791/python/TransformerTagging/tests/test_transformer_tagging.py#L198)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Let's assert the standard things like:

```python
self.assertEqual(SHORT_SAMPLE_TAGS, props["TAGS"])
self.assertEqual(SHORT_SAMPLE_TRIGGER_SENTENCES, props["TEXT TRAVEL TRIGGER SENTENCES"])
self.assertEqual(SHORT_SAMPLE_OFFSET, props["TEXT TRAVEL TRIGGER SENTENCES OFFSET"])
self.assertEqual(SHORT_SAMPLE_SCORE, props["TEXT TRAVEL TRIGGER SENTENCES SCORE"])
```

But, minimally, use a different TAG than what's used in the default corpus.
</blockquote></details>

changed the custom corpus to have different tags and added checks for trigger sentences, offset, and score.
___
*[`python/TransformerTagging/transformer_tagging_component/transformer_tagging_component.py` line 119 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/337#-NePhbJO2wGhSIPD38Ve:-NezkvEP9WCFCP77aNL3:b-7tfmjp) ([raw file](https://github.com/openmpf/openmpf-components/blob/784fd041115d2bb7b02bc5e25dc32b880f5de791/python/TransformerTagging/transformer_tagging_component/transformer_tagging_component.py#L119)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Add `TRANSLATION`.
</blockquote></details>

added
___
*[`python/TransformerTagging/transformer_tagging_component/transformer_tagging_component.py` line 161 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/337#-NePj1qL0HGoNpXJa5Zz:-Nezi2tJD29A4f3EqR2c:b-2nklu1) ([raw file](https://github.com/openmpf/openmpf-components/blob/784fd041115d2bb7b02bc5e25dc32b880f5de791/python/TransformerTagging/transformer_tagging_component/transformer_tagging_component.py#L161)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

How does this handle this kind of text?

```
This is a sentence
of a good dog.
```

Is that parsed out as one or two sentences?

Initially, I was thinking that we'd want that to be one sentence because that's how we handle single newlines for breaking up large text for Azure translation, but it may actually be more beneficial for sentence matching to error on the side of smaller rather than larger sentences. It needs to handle partial phrases anyway.
</blockquote></details>

NLTK treats it as one sentence.
___
*[`python/TransformerTagging/transformer_tagging_component/transformer_text_tags_corpus.json` line 55 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/337#-NePfxSj0rtpzWXlahwL:-Nezii7M1dDxYKJd618R:bmgs3fo) ([raw file](https://github.com/openmpf/openmpf-components/blob/784fd041115d2bb7b02bc5e25dc32b880f5de791/python/TransformerTagging/transformer_tagging_component/transformer_text_tags_corpus.json#L55)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Check spelling: "financ"

Make same change to custom corpus.
</blockquote></details>

The original regex was financ to match both finance and financial. I've changed the spelling to finance and added an entry for financial.
___
*[`python/TransformerTagging/tests/data/multiple_tags.txt` line 1 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/337#-NeQtBuZ0qc4wisrwljb:-NezkiqvE1Vubs3zNNHz:bgeocpn) ([raw file](https://github.com/openmpf/openmpf-components/blob/784fd041115d2bb7b02bc5e25dc32b880f5de791/python/TransformerTagging/tests/data/multiple_tags.txt#L1)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

This is unused.
</blockquote></details>

was planning to add a test for multiple tags but the custom confidence test returns multiple tags.

**Pull request closed without merging**
