### PR TITLE
Backporting Tesseract MAX_PIXELS setting to 4.1 version. (#1190)

### PR DESCRIPTION
**Pull request by hhuangMITRE**
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/194)

### CODE REVIEW

**Review by jrobble — COMMENTED** [review]
> Reviewed 6 of 6 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/194)* status: all files reviewed, 1 unresolved discussion (waiting on @brosenberg42 and @hhuangMITRE)

___
*[cpp/TesseractOCRTextDetection/README.md, line 128 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/194#-MKDXy6Q37t-mA_fipJO:-MKDXy6Q37t-mA_fipJP:b-33x0qw) ([raw file](https://github.com/openmpf/openmpf-components/blob/d8bd78a18a664505e6d905f7d4a7d371f8a93114/cpp/TesseractOCRTextDetection/README.md#L128)):*
> ```Markdown
> Note the OSD language file (`osd.traindata`) is for extraction of script orientation rather than language.
> Users may download additional language/script models from https://github.com/tesseract-ocr/tessdata and place them in the component's `tessdata` directory or `[MODELS_DIR_PATH]/[TESSDATA_MODELS_SUBDIRECTORY]`.
> During processing, if the OSD model detects a certain language but the corresponding language model is missing from the component's `tessdata` directory, then that language will be reported in the `MISSING_LANGUAGE_MODELS` output parameter.
> ```

This PR doesn't add MISSING_LANGUAGE_MODELS support. I updated this PR by removing this line. I'm running a Jenkins build now. You'll get an email when it's done.

**Comment by jrobble** [comment]
___
*[cpp/TesseractOCRTextDetection/TesseractOCRTextDetection.cpp, line 722 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/194#-MKKwXNVAwaxE8EvaiD4:-MKKwXNW1NUUatHoJaFc:b-5rof9r) ([raw file](https://github.com/openmpf/openmpf-components/blob/2fc42a03cad64809251c199a97f12f437cc553d9/cpp/TesseractOCRTextDetection/TesseractOCRTextDetection.cpp#L722)):*
> ```
> to_string(max_size)
> ```

I think we want `max_pixels` here, right?

**Review by hhuangMITRE — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/194)* status: all files reviewed, 1 unresolved discussion (waiting on @brosenberg42 and @jrobble)

___
*[cpp/TesseractOCRTextDetection/TesseractOCRTextDetection.cpp, line 722 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/194#-MKKwXNVAwaxE8EvaiD4:-MKL-rsb-MgtlZqUuZ5y:b-etxbo7) ([raw file](https://github.com/openmpf/openmpf-components/blob/2fc42a03cad64809251c199a97f12f437cc553d9/cpp/TesseractOCRTextDetection/TesseractOCRTextDetection.cpp#L722)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

> ```
> to_string(max_size)
> ```

I think we want `max_pixels` here, right?
</blockquote></details>

Yes, originally, this message would have warned users that the internal Tesseract limit is reached but now we want to also make sure that the component's max_pixels limit isn't violated either. The max_pixels check occurs below:

        // If rescale still exceeds pixel limits, decrease further.

        if (ocr_fset.max_pixels > 0 &&

            (default_rescale * im_width) * (im_height * default_rescale) > ocr_fset.max_pixels) {

            default_rescale = std::sqrt((double)ocr_fset.max_pixels / (double)(im_height * im_width));

        }
We could update the warning message to max_pixels here and print out the log message after both checks are completed.

**Review by hhuangMITRE — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/194)* status: all files reviewed, 1 unresolved discussion (waiting on @brosenberg42 and @jrobble)

___
*[cpp/TesseractOCRTextDetection/TesseractOCRTextDetection.cpp, line 722 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/194#-MKKwXNVAwaxE8EvaiD4:-MKL1QG70ereBHKd6u6x:b-d6w0fs) ([raw file](https://github.com/openmpf/openmpf-components/blob/2fc42a03cad64809251c199a97f12f437cc553d9/cpp/TesseractOCRTextDetection/TesseractOCRTextDetection.cpp#L722)):*
<details><summary><i>Previously, hhuangMITRE (Howard W Huang) wrote…</i></summary><blockquote>

Yes, originally, this message would have warned users that the internal Tesseract limit is reached but now we want to also make sure that the component's max_pixels limit isn't violated either. The max_pixels check occurs below:

        // If rescale still exceeds pixel limits, decrease further.

        if (ocr_fset.max_pixels > 0 &&

            (default_rescale * im_width) * (im_height * default_rescale) > ocr_fset.max_pixels) {

            default_rescale = std::sqrt((double)ocr_fset.max_pixels / (double)(im_height * im_width));

        }
We could update the warning message to max_pixels here and print out the log message after both checks are completed.
</blockquote></details>

I'll update this section shortly.

**Review by hhuangMITRE — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/194)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @brosenberg42 and @jrobble)

___
*[cpp/TesseractOCRTextDetection/TesseractOCRTextDetection.cpp, line 722 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/194#-MKKwXNVAwaxE8EvaiD4:-MKLDXys-rBueTFT33di:bwxwr5b) ([raw file](https://github.com/openmpf/openmpf-components/blob/2fc42a03cad64809251c199a97f12f437cc553d9/cpp/TesseractOCRTextDetection/TesseractOCRTextDetection.cpp#L722)):*
<details><summary><i>Previously, hhuangMITRE (Howard W Huang) wrote…</i></summary><blockquote>

I'll update this section shortly.
</blockquote></details>

I caught myself when I saw the update. The updated log warning looks good, thanks Jeff!
I reran the tests in my local 4.1 MPF vm, everything works as expected.

**Review by jrobble — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/194)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @brosenberg42)

**Pull request merged**
