### PR TITLE
Ocr and scene change

### PR DESCRIPTION
**Pull request by hhuangMITRE**
Pushing Tesseract OCR text detection module and Video Scene Change detection module into repo. Let me know which sections will need revision/further refinement. Thank you!

---
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/63)

### CODE REVIEW

**Comment by jrobble** [comment]
The above commits are from the SUI user. That's a bit odd since there is no SUI user on GitHub; however, in the end it won't matter because all of the commits will be squashed into one commit with your name on it.

---

Reviewed 9 of 81 files at r1.
Review status: 9 of 81 files reviewed, 6 unresolved discussions (waiting on @hhuangMITRE and @jrobble)

---

*[cpp/OCR/README, line 1 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/63#-LEprkVADw-msEopm9Mq:-LEprkVADw-msEopm9Mr:b-rygupq) ([raw file](https://github.com/openmpf/openmpf-components/blob/35b5d652a1041a4e26dcf14de707a757fde1b8e0/cpp/OCR/README#L1)):*
> ```
> # BUILD
> ```

The content of this file is copied from the example image transformer component. Remove all of it and replace it with:

```
# Overview

This repository contains source code and model data for the OpenMPF Tesseract OCR text detection component.
```

---

*[cpp/OCR/src/ImageTransformer.cpp, line 55 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/63#-LEpvMiY8oC-V0HZxt70:-LEpvMiY8oC-V0HZxt71:b-d546ot) ([raw file](https://github.com/openmpf/openmpf-components/blob/35b5d652a1041a4e26dcf14de707a757fde1b8e0/cpp/OCR/src/ImageTransformer.cpp#L55)):*
> ```cpp
>  * Initialize default parameters.
>  */
>  void ImageTransformerComponent::SetDefaultParameters() {
> ```

This is copied from the example image transformer component. The name of this class should be something else.

---

*[cpp/OCR/src/LICENSE, line 1 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/63#-LEpsXKy4c2pf391plwG:-LEpsXKy4c2pf391plwH:b-k13pd4) ([raw file](https://github.com/openmpf/openmpf-components/blob/35b5d652a1041a4e26dcf14de707a757fde1b8e0/cpp/OCR/src/LICENSE#L1)):*
> ```
> /******************************************************************************
> ```

It seems that everything in tessdata may have been copied from the Tesseract project. Looking at their [license](https://github.com/tesseract-ocr/tesseract/blob/master/COPYING), they are Apache 2.0. You need to mention that in this file. The end of this file should look like:

```
this software is being used.



 This software makes use of data files from third party software:

 --------------------------------------------------------------------------

 The "Tesseract OCR" project is licensed under the Apache 2.0 License.
```

Note that if you also use source code from that project, then change "makes use of data files from" to "makes use of source code and data files from".

Does your Tesseract component or scene change component use any other data files, models, or source code you didn't create?

---

*[cpp/SceneChangeDetection/README.md, line 3 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/63#-LEpqueL0i5vcknxVMFM:-LEpqueL0i5vcknxVMFN:b-9ijx4r) ([raw file](https://github.com/openmpf/openmpf-components/blob/35b5d652a1041a4e26dcf14de707a757fde1b8e0/cpp/SceneChangeDetection/README.md#L3)):*
> ```Markdown
> # Overview
> 
> This repository contains source code and models data for the MPF caffe object detection component.
> ```

Please change "MPF caffe object detection" to "OpenMPF video scene change detection". Also, this doesn't seem to contain "models data", so remove that from the description.

---

*[cpp/SceneChangeDetection/sample_caffe_detector.cpp, line 1 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/63#-LEpq2AnDFo6OwAKPlRB:-LEpq2Ap4lY4fDqB1FjH:biywwfu) ([raw file](https://github.com/openmpf/openmpf-components/blob/35b5d652a1041a4e26dcf14de707a757fde1b8e0/cpp/SceneChangeDetection/sample_caffe_detector.cpp#L1)):*
> ```cpp
> /******************************************************************************
> ```

Please rename this file to sample_scene_change_detector. Also, rename variables in this file as appropriate. The original author based it on caffe, but it now has nothing to do with caffe.

---

*[cpp/SceneChangeDetection/plugin-files/descriptor/descriptor.json, line 223 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/63#-LEpvajZCLA00KLrewOA:-LEpvajZCLA00KLrewOB:bvevvhi) ([raw file](https://github.com/openmpf/openmpf-components/blob/35b5d652a1041a4e26dcf14de707a757fde1b8e0/cpp/SceneChangeDetection/plugin-files/descriptor/descriptor.json#L223)):*
> ```JSON
>       "algorithm": "SceneChange",
>       "properties" : []
>         
> ```

Please remove blank lines.

---


*Comments from [Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/63#-:-LEpvvZb-cGRVi2K1_mq:bgyefg7)*

**Comment by brosenberg42** [comment]
*[cpp/TesseractOCRTextDetection/CMakeLists.txt, line 36 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/63#-LFO1mUVBO0I7kYPGi9M:-LFO1mUW1gLyfTMK9YF_:b-eihwws) ([raw file](https://github.com/openmpf/openmpf-components/blob/f0ca4053cc53d5a0d4b8c3680169f62c7b0a6ed5/cpp/TesseractOCRTextDetection/CMakeLists.txt#L36)):*
> ```CMake
> file(MAKE_DIRECTORY ${PACKAGE_DIR}/bin)
> 
> file(COPY ${CMAKE_CURRENT_SOURCE_DIR}/plugin-files/data/tessdata DESTINATION ${PACKAGE_DIR}/bin/)
> ```

Everything under plugin-files gets put in the plugin package. This causes all of the tesseract data to end up in the plugin package twice, once under data and again under bin. The tessdata files are pretty big so having them twice makes the plugin package very big. You should remove this line and move the content of `openmpf-components/cpp/TesseractOCRTextDetection/plugin-files/data/` to `openmpf-components/cpp/TesseractOCRTextDetection/plugin-files/bin/`

---


*Comments from [Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/63)*

**Comment by clnowacki** [comment]
There are no unit tests for either of these components. We use the googletest framework for all of our C++ unit test development, and these tests are run for every component every time we do a Jenkins build. See https://github.com/google/googletest/blob/master/googletest/docs/primer.md for some introductory documentation on googletest. You could start by looking at the tests for the Caffe and Darknet components to get an idea of what you are expected to test, at a minimum.

---

Review status: 4 of 81 files reviewed, 6 unresolved discussions (waiting on @jrobble, @hhuangMITRE, and @clnowacki)

---

*[cpp/SceneChangeDetection/plugin-files/descriptor/descriptor.json, line 3 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/63#-LFXgcLC9VU-Phq4yGY1:-LFXgcLC9VU-Phq4yGY2:bbjig0v) ([raw file](https://github.com/openmpf/openmpf-components/blob/f0ca4053cc53d5a0d4b8c3680169f62c7b0a6ed5/cpp/SceneChangeDetection/plugin-files/descriptor/descriptor.json#L3)):*
> ```JSON
> {
>   "componentName" : "SceneChangeDetection",
>   "componentVersion" : "2.0.0",
> ```

it is likely this component will first go into the 2.2.0 release, so please change these version numbers to 2.2.0

---

*[cpp/SceneChangeDetection/plugin-files/descriptor/descriptor.json, line 7 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/63#-LFXgO3R5oux5si_ANxh:-LFXgO3S0YxXYRyhvmk7:bfa4ias) ([raw file](https://github.com/openmpf/openmpf-components/blob/f0ca4053cc53d5a0d4b8c3680169f62c7b0a6ed5/cpp/SceneChangeDetection/plugin-files/descriptor/descriptor.json#L7)):*
> ```JSON
>   "sourceLanguage" : "c++",
>   "batchLibrary": "${MPF_HOME}/plugins/SceneChangeDetection/lib/libsceneChange.so",
>   "streamLibrary": "${MPF_HOME}/plugins/SceneChangeDetection/lib/libsceneChange.so",
> ```

Please remove the streamLibrary definition here. Since this only a batch component, you should not specify a streaming library.

---

*[cpp/SceneChangeDetection/plugin-files/descriptor/descriptor.json, line 13 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/63#-LFXiGJNBD9A6SMZSBj8:-LFXiGJNBD9A6SMZSBj9:b-fwb304) ([raw file](https://github.com/openmpf/openmpf-components/blob/f0ca4053cc53d5a0d4b8c3680169f62c7b0a6ed5/cpp/SceneChangeDetection/plugin-files/descriptor/descriptor.json#L13)):*
> ```JSON
>   } ],
>   "algorithm" : {
>     "name" : "SceneChange",
> ```

The convention in our other components to make the algorithm name all caps.

---

*[cpp/TesseractOCRTextDetection/CMakeLists.txt, line 80 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/63#-LFcDZ9SA7bHYML0KmNi:-LFcDZ9SA7bHYML0KmNj:byxallv) ([raw file](https://github.com/openmpf/openmpf-components/blob/f0ca4053cc53d5a0d4b8c3680169f62c7b0a6ed5/cpp/TesseractOCRTextDetection/CMakeLists.txt#L80)):*
> ```CMake
> 
> # Build executable
> add_executable(OCR_test main.cpp)
> ```

Please rename this executable to "sample_tesseract_ocr_detector", so that it uses the same naming convention as our other components.

---

*[cpp/TesseractOCRTextDetection/TesseractOCRTextDetection.cpp, line 586 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/63#-LFc8Z7UCr516s4jCwuH:-LFc8Z7UCr516s4jCwuI:brxlch0) ([raw file](https://github.com/openmpf/openmpf-components/blob/f0ca4053cc53d5a0d4b8c3680169f62c7b0a6ed5/cpp/TesseractOCRTextDetection/TesseractOCRTextDetection.cpp#L586)):*
> ```cpp
> 	LOG4CXX_INFO(hw_logger_, text.c_str() );
> 	cout << text << endl;
> }
> ```

One of the parts of the standard logging output format that we use is the line number of the logging statement. This makes it easier to find where the logging statement occurred, and helps with debugging. By putting the only LOG4CXX macro call in this function, the line number that is printed is always the same, which is the line number in this function. You are losing the information that could be potentially useful when trying to figure out what went wrong. Also, having multiple logging functions would be unnecessary if you simply put the LOG4CXX macros inline, since those macros support a wide range of data types for output.

Also, we prefer not to have very verbose logging. All of your logging statements are coming out at the INFO level, whereas most of them should be at the DEBUG level, and some should probably be at the WARN or ERROR level.

---


*Comments from [Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/63#-:-LFcDy2Z4Jrqz_8SsQ2D:b-wqylnv)*

**Comment by jrobble** [comment]
Review status: 4 of 81 files reviewed, 9 unresolved discussions (waiting on @jrobble, @hhuangMITRE, and @clnowacki)

---

*[cpp/SceneChangeDetection/SceneChangeDetection.cpp, line 67 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/63#-LGCGWpf-oDBi_iE6JFs:-LGCGWpg2CVXZX3U4fvw:b-owsc6i) ([raw file](https://github.com/openmpf/openmpf-components/blob/f0ca4053cc53d5a0d4b8c3680169f62c7b0a6ed5/cpp/SceneChangeDetection/SceneChangeDetection.cpp#L67)):*
> ```cpp
> 
> std::string SceneChangeDetection::GetDetectionType() {
>     return "CLASS";
> ```

This should return "SCENE".

---

*[cpp/TesseractOCRTextDetection/TesseractOCRTextDetection.h, line 79 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/63#-LGCHbs8Avnmpkh6osn7:-LGCHbs8Avnmpkh6osn8:b-4o2kak) ([raw file](https://github.com/openmpf/openmpf-components/blob/f0ca4053cc53d5a0d4b8c3680169f62c7b0a6ed5/cpp/TesseractOCRTextDetection/TesseractOCRTextDetection.h#L79)):*
> ```objc
>     std::string check_string(std::string s, OCR_filter_settings ocrset);
> 
>     std::string GetDetectionType() { return "IMAGE_DATA"; }
> ```

This function should probably be implemented in the .cpp file. Also, "IMAGE_DATA" is not descriptive. It should probably be "TEXT".

---

*[cpp/TesseractOCRTextDetection/TesseractOCRTextDetection.cpp, line 1002 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/63#-LGCHOW6DSekO9ZodYCX:-LGCHOW6DSekO9ZodYCY:bvc5klu) ([raw file](https://github.com/openmpf/openmpf-components/blob/f0ca4053cc53d5a0d4b8c3680169f62c7b0a6ed5/cpp/TesseractOCRTextDetection/TesseractOCRTextDetection.cpp#L1002)):*
> ```cpp
> bool TesseractOCRTextDetection::Supports(MPFDetectionDataType data_type) {
> 
> 	if (data_type == MPFDetectionDataType::IMAGE) {
> ```

This can be reduced to:

```
return data_type == MPFDetectionDataType::IMAGE;
```

---


*Comments from [Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/63)*

**Comment by hhuangMITRE** [comment]
___
*[cpp/TesseractOCRTextDetection/TesseractOCRTextDetection.cpp, line 1004 at r8](https://reviewable.io/reviews/openmpf/openmpf-components/63#-LMbas5OE0riRyz1kBMb:-LMcLWJk1Y6ghrEOomNi:b-s4dats) ([raw file](https://github.com/openmpf/openmpf-components/blob/b86ead3521eb9d99e601813b2110aaa810a7f24b/cpp/TesseractOCRTextDetection/TesseractOCRTextDetection.cpp#L1004)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

Calling `boost::locale::conv::utf_to_utf` here, and in the lines below defeats the purpose of using std::wstring. `boost::locale::conv::utf_to_utf` should only be called in two places. Once in `get_tesseract_detections` to convert the results given by the Tesseract binary, and once to convert the final result at `image_location.detection_properties["TEXT"] = boost::locale::conv::utf_to_utf<char>(ocr_detections);`. All other code should be changed to work with `std::wstring`. The `parse_json` function needs to be changed to return `std::map<std::wstring,std::map<std::wstring,std::vector<std::wstring>>>`. The JSON library that is being used returns its results as `std::wstring`, but there is code in `parse_json` that converts from `std::wstring` to `std::string`.

For example, the following is from `parse_json`:
```
wstringstream output;
output << array[i]->Stringify();
wstring ws(output.str());
string str(ws.begin(),ws.end());
str = str.substr(1,str.size()-2);
json_kvs_string[term_str].push_back(str);
```
It can be changed to:
```
wstring temp = array[i]->Stringify();
temp = temp.substr(1, temp.size() - 2);
json_kvs_string[term].push_back(temp);
```
</blockquote></details>

Oh I see, I'll convert the text-tagging into using wstring as well, thanks!

After this change, the text-tags returned by each function will be in wstring format, will I need to convert them back into string format when storing them in the detection property ("TAGS") similar to how we're storing ("TEXT") results?

**Comment by hhuangMITRE** [comment]
___
*[cpp/SceneChangeDetection/CMakeLists.txt, line 45 at r5](https://reviewable.io/reviews/openmpf/openmpf-components/63#-LJE8T663BfGFfX2XxYu:-LOstD0tDbaZ0_yWBmgh:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/f08516930bcaead0bd32b0fb1a010a6c12c4cc6c/cpp/SceneChangeDetection/CMakeLists.txt#L45)):*
<details><summary><i>Previously, clnowacki wrote…</i></summary><blockquote>

It doesn't appear that you need the config4cpp package in your code. If not, these 4 lines should e removed.
</blockquote></details>

Done.

**Comment by hhuangMITRE** [comment]
___
*[cpp/SceneChangeDetection/plugin-files/config/Log4cxxConfig.xml, line 32 at r5](https://reviewable.io/reviews/openmpf/openmpf-components/63#-LJESXAmCLkWW476TLtt:-LOyZaUK-XMoqchRQznM:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/f08516930bcaead0bd32b0fb1a010a6c12c4cc6c/cpp/SceneChangeDetection/plugin-files/config/Log4cxxConfig.xml#L32)):*
<details><summary><i>Previously, clnowacki wrote…</i></summary><blockquote>

You don't need the word "video" in the name of this log file, since the scan change component can only process video.
</blockquote></details>

Done.

**Comment by brosenberg42** [comment]
___
*[cpp/SceneChangeDetection/plugin-files/descriptor/descriptor.json, line 90 at r13](https://reviewable.io/reviews/openmpf/openmpf-components/63#-LQJxf5MCypkR87RJsLG:-LQJxf5N21bbe-ptiL8v:b1v0bw7) ([raw file](https://github.com/openmpf/openmpf-components/blob/25ba57a90ef34cc08db348633a31a5c974e871f8/cpp/SceneChangeDetection/plugin-files/descriptor/descriptor.json#L90)):*
> ```JSON
>           "type": "INT",
>           "propertiesKey": "detection.track.minimum.length",
>           "defaultValue": 15
> ```

Please remove `"defaultValue": 15`. You can't have both propertiesKey and defaultValue set. This is why your Jenkins builds currently fail.

**Pull request merged**
