### PR TITLE
Make DlibFace component use frame skipper

### PR DESCRIPTION
**Pull request by brosenberg42**
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/15)

### CODE REVIEW

**Comment by jrobble** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-components/15)*

**Comment by jrobble** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-components/15)*

**Comment by brosenberg42** [comment]
> For the most part, I think we can just copy + paste the code for this one. 

Wouldn't it be better to just have the sample binaries call a function in the testUtils library? The only part that is Dlib specific is when the component is created. We could add a function to testUtils that takes the component and command line args as parameters.

**Comment by jrobble** [comment]
> Wouldn't it be better to just have the sample binaries call a function in the testUtils library

Yeah, that would be better. Off the top of my head, the only thing in the component-specific code that might change are the values in the job properties map. The function in the testUtils library should take that map as a parameter.

**Comment by jrobble** [comment]
Additionally, as part of testing feed-forward, we'll probably want a way to construct the job objects with feed-forward track objects. That can be an additional parameter too.

**Pull request closed without merging**
