### PR TITLE
added OcvFrameReader

### PR DESCRIPTION
**Pull request by clnowacki**
This is pull request is for review of the new OpenCV based frame reader component for streaming detection processing. I haven't updated my dev VM to OpenCV 3.2 yet, so the CMakeLists.txt file still says OpenCV 3.1, but I don't expect there will be any issues with this code and OpenCV 3.2.

---
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/11)

### CODE REVIEW

**Comment by jrobble** [comment]
:lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, 6 unresolved discussions.

---

*[cpp/OcvFrameReader/CMakeLists.txt, line 35 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-components/11#-KpFzIEtTWv_B2YAH6TF:-KpFzIEtTWv_B2YAH6TG:bf42i27) ([raw file](https://github.com/openmpf/openmpf-components/blob/cf02c4ac94c57ed7d40654aabf4910de6ce1226d/cpp/OcvFrameReader/CMakeLists.txt#L35)):*
> ```CMake
> include(../ComponentSetup.cmake)
> 
> find_package(OpenCV 3.1 EXACT REQUIRED PATHS /opt/opencv-3.1.0
> ```

Just a friendly reminder that this should be updated to 3.2 before this code lands.

---

*[cpp/OcvFrameReader/OcvFrameReader.cpp, line 55 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-components/11#-KpG4-Q3oKLh4hrQulCx:-KpG4-Q4iAAyv1LtkoEC:bb85yrh) ([raw file](https://github.com/openmpf/openmpf-components/blob/cf02c4ac94c57ed7d40654aabf4910de6ce1226d/cpp/OcvFrameReader/OcvFrameReader.cpp#L55)):*
> ```cpp
> 
>     Mat first;
>     success = video_capture_.read(first);
> ```

Shouldn't the first frame be stored and later processed?

---

*[cpp/OcvFrameReader/OcvFrameReader.cpp, line 61 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-components/11#-KpG1RLWw2DF5OqD5RmV:-KpG1RLWw2DF5OqD5RmW:bin7hb3) ([raw file](https://github.com/openmpf/openmpf-components/blob/cf02c4ac94c57ed7d40654aabf4910de6ce1226d/cpp/OcvFrameReader/OcvFrameReader.cpp#L61)):*
> ```cpp
>     stream_properties["FRAME_ROWS"] = std::to_string(first.rows);
>     stream_properties["FRAME_COLS"] = std::to_string(first.cols);
>     stream_properties["FRAME_NUM_PIXELS"] = std::to_string(first.total());
> ```

If the resolution changes, won't the above three properties change? It seems like we may have to check the frame size each time we read a frame from the video capture.

---

*[cpp/OcvFrameReader/OcvFrameReader.cpp, line 94 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-components/11#-KpG4fyvu3z-tJITbYPZ:-KpG4fyvu3z-tJITbYP_:bg79k43) ([raw file](https://github.com/openmpf/openmpf-components/blob/cf02c4ac94c57ed7d40654aabf4910de6ce1226d/cpp/OcvFrameReader/OcvFrameReader.cpp#L94)):*
> ```cpp
>     }
> 
>     int frame_num_cols_ = 
> ```

This is a class data member, so you can remove the "int".

---

*[cpp/OcvFrameReader/OcvFrameReader.cpp, line 108 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-components/11#-KpFxr2GjmDFIOcRgEeq:-KpFxr2GjmDFIOcRgEer:b-9q0quz) ([raw file](https://github.com/openmpf/openmpf-components/blob/cf02c4ac94c57ed7d40654aabf4910de6ce1226d/cpp/OcvFrameReader/OcvFrameReader.cpp#L108)):*
> ```cpp
>     }
> 
>     frame_byte_size_ = frame_num_cols_*frame_num_rows_*elem_size;
> ```

Won't the frame byte size change when the camera resolution changes?

---

*[cpp/OcvFrameReader/OcvFrameReader.h, line 85 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-components/11#-KpG5BmKVMiBkSsQM4B3:-KpG5BmKVMiBkSsQM4B4:bnkxae4) ([raw file](https://github.com/openmpf/openmpf-components/blob/cf02c4ac94c57ed7d40654aabf4910de6ce1226d/cpp/OcvFrameReader/OcvFrameReader.h#L85)):*
> ```objc
>                                      // needed for mapping the shared
>                                      // storage file into memory.
>     int frame_buffer_file_descriptor_;
> ```

The MPFFrameStore has the following data members:

```
std::string buffer_name_;
int storage_handle_;
uint8_t* start_addr_;
size_t buffer_byte_size_;
```

Do they also need to part of this class? This class has an instance of MPFFrameStore, so it seems redundant.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-components/11#-:-KpFzFwJY4w2O0YKuMD9:bnfp4nl)*

**Comment by jrobble** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-components/11)*

**Comment by brosenberg42** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[cpp/OcvFrameReader/OcvFrameReader.h, line 49 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-components/11#-KpPjdKRa6rykypGfQzB:-KpPjdKRa6rykypGfQzC:bvz4evr) ([raw file](https://github.com/openmpf/openmpf-components/blob/cf02c4ac94c57ed7d40654aabf4910de6ce1226d/cpp/OcvFrameReader/OcvFrameReader.h#L49)):*
> ```objc
>   public:
>     OcvFrameReader() = default;
>     ~OcvFrameReader() {
> ```

Should this be virtual?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-components/11)*

**Comment by clnowacki** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[cpp/OcvFrameReader/OcvFrameReader.cpp, line 55 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-components/11#-KpG4-Q3oKLh4hrQulCx:-KpQ9WCAEESrNCuAX7aD:b9xt5qp) ([raw file](https://github.com/openmpf/openmpf-components/blob/cf02c4ac94c57ed7d40654aabf4910de6ce1226d/cpp/OcvFrameReader/OcvFrameReader.cpp#L55)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Shouldn't the first frame be stored and later processed?
</blockquote></details>

I don't really think it needs to be. After all, it will take some amount of time to create and map the frame buffer, so there will be intervening frames that are skipped. The "first frame" is really an arbitrary construct, determined by the time at which we are ready to start processing frames.

---

*[cpp/OcvFrameReader/OcvFrameReader.h, line 49 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-components/11#-KpPjdKRa6rykypGfQzB:-KpPy9fcLnt5y1zJW8QR:bppvyzc) ([raw file](https://github.com/openmpf/openmpf-components/blob/cf02c4ac94c57ed7d40654aabf4910de6ce1226d/cpp/OcvFrameReader/OcvFrameReader.h#L49)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

Should this be virtual?
</blockquote></details>

Well, it could be, but it's not necessary. The destructor in the base class is virtual, so this one is too.

---

*[cpp/OcvFrameReader/OcvFrameReader.h, line 85 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-components/11#-KpG5BmKVMiBkSsQM4B3:-KpQ8LZE_SAwnH84u54F:br11z9t) ([raw file](https://github.com/openmpf/openmpf-components/blob/cf02c4ac94c57ed7d40654aabf4910de6ce1226d/cpp/OcvFrameReader/OcvFrameReader.h#L85)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

The MPFFrameStore has the following data members:

```
std::string buffer_name_;
int storage_handle_;
uint8_t* start_addr_;
size_t buffer_byte_size_;
```

Do they also need to part of this class? This class has an instance of MPFFrameStore, so it seems redundant.
</blockquote></details>

Yes, the frame_buffer_start_addr,  frame_buffer_byte_size and the frame_buffer_file_descriptor are redundant.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-components/11)*

**Comment by jrobble** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[cpp/OcvFrameReader/OcvFrameReader.cpp, line 55 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-components/11#-KpG4-Q3oKLh4hrQulCx:-KpQFCjx9_yAvLgnJSOH:bwmnavt) ([raw file](https://github.com/openmpf/openmpf-components/blob/cf02c4ac94c57ed7d40654aabf4910de6ce1226d/cpp/OcvFrameReader/OcvFrameReader.cpp#L55)):*
<details><summary><i>Previously, clnowacki wrote…</i></summary><blockquote>

I don't really think it needs to be. After all, it will take some amount of time to create and map the frame buffer, so there will be intervening frames that are skipped. The "first frame" is really an arbitrary construct, determined by the time at which we are ready to start processing frames.
</blockquote></details>

From a developer's POV, I understand what you're saying, but I think the end users will want us to process it. Generally, they are not ok with discarding information. We could return the contents of the first frame in a Mat reference or something.

I can imagine a situation where we're streaming video from a file and discarding the first frame is more important that discarding the first frame from a camera feed. We might eventually run batch jobs through streaming as part of a unified architecture.

Also, how long are we talking about when setting up the map and frame buffer?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-components/11)*

**Comment by jrobble** [comment]
Please update "Copyright 2016" to "Copyright 2017" in all of your class files.

---

Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-components/11#-:-KxFD4yBkYMHutOHR00k:bsbimhb)*

**Comment by jrobble** [comment]
Actually, check the copyright in all of your files.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-components/11#-:-KxFE2C3ENeWJ4KRiSa9:b-61rse7)*

**Comment by jrobble** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[cpp/OcvFrameReader/CMakeLists.txt, line 35 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-components/11#-KpFzIEtTWv_B2YAH6TF:-KxJF6jqrx-2lzmQo0O6:b-79qay0) ([raw file](https://github.com/openmpf/openmpf-components/blob/cf02c4ac94c57ed7d40654aabf4910de6ce1226d/cpp/OcvFrameReader/CMakeLists.txt#L35)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Just a friendly reminder that this should be updated to 3.2 before this code lands.
</blockquote></details>

Now 3.3!

---

*[cpp/OcvFrameReader/OcvFrameReader.cpp, line 55 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-components/11#-KpG4-Q3oKLh4hrQulCx:-KxJFERq9NPZviIPQcWE:b8rcynf) ([raw file](https://github.com/openmpf/openmpf-components/blob/cf02c4ac94c57ed7d40654aabf4910de6ce1226d/cpp/OcvFrameReader/OcvFrameReader.cpp#L55)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

From a developer's POV, I understand what you're saying, but I think the end users will want us to process it. Generally, they are not ok with discarding information. We could return the contents of the first frame in a Mat reference or something.

I can imagine a situation where we're streaming video from a file and discarding the first frame is more important that discarding the first frame from a camera feed. We might eventually run batch jobs through streaming as part of a unified architecture.

Also, how long are we talking about when setting up the map and frame buffer?
</blockquote></details>

The users said that discarding the first frame is fine. Let's go with that for now.

---

*[cpp/OcvFrameReader/OcvFrameReader.cpp, line 61 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-components/11#-KpG1RLWw2DF5OqD5RmV:-KxJFPzVIlZGKrifCjUz:bc649sz) ([raw file](https://github.com/openmpf/openmpf-components/blob/cf02c4ac94c57ed7d40654aabf4910de6ce1226d/cpp/OcvFrameReader/OcvFrameReader.cpp#L61)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

If the resolution changes, won't the above three properties change? It seems like we may have to check the frame size each time we read a frame from the video capture.
</blockquote></details>

New information has come to light. Users will be providing separate SD and HD streams, so we don't need to be concerned with resolution changes.

---

*[cpp/OcvFrameReader/OcvFrameReader.cpp, line 108 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-components/11#-KpFxr2GjmDFIOcRgEeq:-KxJFTuRGQ6DZMeq0ZG_:bc649sz) ([raw file](https://github.com/openmpf/openmpf-components/blob/cf02c4ac94c57ed7d40654aabf4910de6ce1226d/cpp/OcvFrameReader/OcvFrameReader.cpp#L108)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Won't the frame byte size change when the camera resolution changes?
</blockquote></details>

New information has come to light. Users will be providing separate SD and HD streams, so we don't need to be concerned with resolution changes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-components/11)*

**Comment by jrobble** [comment]
I think you can just close this PR since your last commit essentially nullifies all changes this PR would make to the develop branch. In other words, OcvFrameReader is not in openmpf/openmpf-components/cpp, so deleting it does nothing.

---

Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-components/11#-:-L-3Fm3vLPb8vVWSHEFo:bp2w7rk)*

**Comment by clnowacki** [comment]
Changes to this repo in this pull request have been removed.

**Pull request closed without merging**
