### PR TITLE
Change Caffe component to use the ModelsIniParser utility

### PR DESCRIPTION
**Pull request by clnowacki**
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/57)

### CODE REVIEW

**Comment by brosenberg42** [comment]
The code changes look good. 
Can ModelFileParser.h, ModelFileParser.cpp, and ModelFileParserException.h be removed from the CaffeDetection directory? If so, can you also remove Config4CPP from CaffeDetection/CMakeLists.txt?

---

Reviewed 20 of 20 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/openmpf/openmpf-components/57#-:-L9C5ifr2y2XgBFKDX1j:b-bjou27)*

**Comment by clnowacki** [comment]
Yes, you're right. I forgot to remove those things. Thx

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/openmpf/openmpf-components/57#-:-L9CC1zyEON653ttgzVN:bn81264)*

**Comment by brosenberg42** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/openmpf/openmpf-components/57#-:-L9FfST04TOwB_8Rduki:bnfp4nl)*

**Comment by jrobble** [comment]
Reviewed 20 of 20 files at r1, 4 of 4 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[cpp/CaffeDetection/CaffeDetection.h, line 160 at r2](https://beta.reviewable.io/reviews/openmpf/openmpf-components/57#-L9G3WRXEaTFoW_RtHIK:-L9G3WRXEaTFoW_RtHIL:bqgdond) ([raw file](https://github.com/openmpf/openmpf-components/blob/d7f8f8b6b71256f6969ac13c88393b12d0046c24/cpp/CaffeDetection/CaffeDetection.h#L160)):*
> ```objc
> 
>         CaffeJobConfig(const MPF::COMPONENT::Properties &props,
>                        const MPF::COMPONENT::ModelsIniParser<ModelSettings> &models,
> ```

Let's call this `model_parser` rather than `models`, since that's more descriptive of what it really is.

---

*[cpp/CaffeDetection/CaffeDetection.cpp, line 453 at r2](https://beta.reviewable.io/reviews/openmpf/openmpf-components/57#-L9G3jqc2uO-VU7HAwpV:-L9G3jqc2uO-VU7HAwpW:bqgdond) ([raw file](https://github.com/openmpf/openmpf-components/blob/d7f8f8b6b71256f6969ac13c88393b12d0046c24/cpp/CaffeDetection/CaffeDetection.cpp#L453)):*
> ```cpp
> 
> CaffeDetection::CaffeJobConfig::CaffeJobConfig(const Properties &props,
>                                                const MPF::COMPONENT::ModelsIniParser<ModelSettings> &models,
> ```

Let's call this `model_parser` rather than `models`, since that's more descriptive of what it really is.

---

*[cpp/CaffeDetection/plugin-files/models/models.ini, line 13 at r2](https://beta.reviewable.io/reviews/openmpf/openmpf-components/57#-L9G3x4c9diW-UuiZl9g:-L9G3x4e7en_bnrC3b23:b-2e8waf) ([raw file](https://github.com/openmpf/openmpf-components/blob/d7f8f8b6b71256f6969ac13c88393b12d0046c24/cpp/CaffeDetection/plugin-files/models/models.ini#L13)):*
> ```INI
> model_txt = yahoo_nsfw.prototxt
> model_bin = yahoo_nsfw.caffemodel
> synset_txt = yahoo_nsfw.txt
> ```

For consistency, let's not use spaces around the `=`.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/openmpf/openmpf-components/57)*

**Comment by jrobble** [comment]
Works as intended.

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/openmpf/openmpf-components/57#-:-L9GBfty8m6718CWYHLf:b-ywfxhk)*

**Comment by jrobble** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/openmpf/openmpf-components/57)*

**Pull request merged**
