### PR TITLE
Feat/wfm trigger

### PR DESCRIPTION
**Pull request by brosenberg42**
**Issues:**
- https://github.com/openmpf/openmpf/issues/1574
- https://github.com/openmpf/openmpf/issues/1642
- https://github.com/openmpf/openmpf/issues/1643

**Related PRs:**
- https://github.com/openmpf/openmpf/pull/1644
- https://github.com/openmpf/openmpf-components/pull/336
- https://github.com/openmpf/openmpf-contrib-components/pull/88
- https://github.com/openmpf/openmpf-cpp-component-sdk/pull/121
- https://github.com/openmpf/openmpf-python-component-sdk/pull/71
- https://github.com/openmpf/openmpf-java-component-sdk/pull/63
- https://github.com/openmpf/openmpf-docker/pull/197

- - -
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/336)

### CODE REVIEW

**Review by jrobble — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/336)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @brosenberg42)

**Review by jrobble — CHANGES_REQUESTED** [review]
> Reviewed 50 of 50 files at r2, 2 of 2 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/336)* status: all files reviewed, 2 unresolved discussions (waiting on @brosenberg42)

*[a discussion](https://reviewable.io/reviews/openmpf/openmpf-components/336#-NhZVE354sOtcqpUMSlO:-NhZVE354sOtcqpUMSlP:b-f2ulje) (no related file):*
In the README for Whisper we have:

> `WHISPER_MODE`: Determines whether Whisper will perform language detection, speech-to-text transcription, or speech translation. English-only models can only transcribe English audio. Set to `LANGUAGE_DETECTION` for spoken language detection, `TRANSCRIPTION` for speech-to-text transcription, and `SPEECH_TRANSLATION` for speech translation.

Update to:

> `WHISPER_MODE`: Determines whether Whisper will perform language detection, speech-to-text transcription, or speech translation. If multiple languages are spoken in a single piece of media, language detection will detect only one of them. English-only models can only transcribe English audio. Set to `LANGUAGE_DETECTION` for spoken language detection, `TRANSCRIPTION` for speech-to-text transcription, and `SPEECH_TRANSLATION` for speech translation.

___
___
*[`python/AzureSpeechDetection/README.md` line 39 at r3](https://reviewable.io/reviews/openmpf/openmpf-components/336#-Nh8KnGnAAhLJ9lVxi-i:-Nh8KnGnAAhLJ9lVxi-j:b-sc42or) ([raw file](https://github.com/openmpf/openmpf-components/blob/811b81abc06c533f2997e6fa51fcabe5ff2cab3c/python/AzureSpeechDetection/README.md#L39)):*
> ```Markdown
> | Property Key                   | Description                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
> |--------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
> | `SPEAKER_ID`              | A unique speaker identifier, of the form "`<start_offset>-<stop_offset>-<#>`, where `<start_offset>` and `<stop_offset>` are integers indicating the segment range (in frame counts for video jobs, milliseconds for audio jobs) for sub-jobs when a job has been segmented by the Workflow Manager. The final `#` portion of the ID is a 1-indexed counter for speaker identity within the indicated segment range. When jobs are not segmented, or not submitted through the Workflow Manager at all, `stop_offset` may instead be `EOF`, indicating that the job extends to the end of the file. |
> ```

Increment the `outputChangedCounter` due to this change. The OpenMPF major version number change will result in jobs being re-run anyway, but good to get in the habit.


<!-- Sent from Reviewable.io -->

**Review by brosenberg42 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/336)* status: 54 of 56 files reviewed, 2 unresolved discussions (waiting on @brosenberg42 and @jrobble)

*[a discussion](https://reviewable.io/reviews/openmpf/openmpf-components/336#-NhZVE354sOtcqpUMSlO:-NiEiCbdBoU2aDFicPSp:b-896fix) (no related file):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

In the README for Whisper we have:

> `WHISPER_MODE`: Determines whether Whisper will perform language detection, speech-to-text transcription, or speech translation. English-only models can only transcribe English audio. Set to `LANGUAGE_DETECTION` for spoken language detection, `TRANSCRIPTION` for speech-to-text transcription, and `SPEECH_TRANSLATION` for speech translation.

Update to:

> `WHISPER_MODE`: Determines whether Whisper will perform language detection, speech-to-text transcription, or speech translation. If multiple languages are spoken in a single piece of media, language detection will detect only one of them. English-only models can only transcribe English audio. Set to `LANGUAGE_DETECTION` for spoken language detection, `TRANSCRIPTION` for speech-to-text transcription, and `SPEECH_TRANSLATION` for speech translation.
</blockquote></details>

Done.

___
___
*[`python/AzureSpeechDetection/README.md` line 39 at r3](https://reviewable.io/reviews/openmpf/openmpf-components/336#-Nh8KnGnAAhLJ9lVxi-i:-NiEiNI59_xAyvUwuVTa:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/811b81abc06c533f2997e6fa51fcabe5ff2cab3c/python/AzureSpeechDetection/README.md#L39)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Increment the `outputChangedCounter` due to this change. The OpenMPF major version number change will result in jobs being re-run anyway, but good to get in the habit.
</blockquote></details>

Done.

**Review by jrobble — APPROVED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/336)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @brosenberg42)

**Review by jrobble — APPROVED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/336)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @brosenberg42)

**Pull request merged**
