### PR TITLE
Update TikaTextDetection component to no longer autoinclude blank metadata track in PDF processing.

### PR DESCRIPTION
**Pull request by hhuangMITRE**
Also, update Tika components with new PDF test.

**Issues:**
- https://github.com/openmpf/openmpf/issues/1317
- https://github.com/openmpf/openmpf/issues/1379
- https://github.com/openmpf/openmpf/issues/1382
- https://github.com/openmpf/openmpf/issues/1383

---
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/271)

### CODE REVIEW

**Review by jrobble — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1, 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/271)* status: all files reviewed, 1 unresolved discussion (waiting on @hhuangMITRE)

*[a discussion](https://reviewable.io/reviews/openmpf/openmpf-components/271#-MfF5NXCADEil3nD9Ts-:-MfF5NXD0bfJ6zBldJ9f:bcvijs7) (no related file):*
Using the web UI, I ran a job with `test-first-page-images.pdf` and `test-tika-image-extraction.pdf` at the same time. The JSON output shows:

```
   "errors": [
      {
         "mediaId": 1,
         "details": [
            {
               "source": "TIKAIMAGE",
               "code": "COULD_NOT_READ_MEDIA",
               "message": "Error processing file at : /home/mpf/git/openmpf-projects/openmpf/trunk/install/share/artifacts/1369"
            }
         ]
      }
   ],
```

The component log shows:

```
2021-07-22 17:19:56,730 INFO [main] o.m.m.c.e.d.MPFDetectionMessenger - Detection request received with job ID 1369 for media file /home/mpf/git/openmpf-projects/openmpf/trunk/install/share/remote-media/test-tika-image-extraction.pdf
2021-07-22 17:19:56,731 INFO [main] o.m.m.d.t.TikaImageDetectionComponent - [Job 1369:test-tika-image-extraction.pdf] Starting job.
2021-07-22 17:19:58,097 INFO [main] o.m.m.d.t.TikaImageDetectionComponent - [Job 1369:test-tika-image-extraction.pdf] Processing complete. Generated 4 generic tracks.
2021-07-22 17:19:58,139 INFO [main] o.m.m.c.e.d.MPFDetectionMessenger - Detection response sent for job ID 1369
2021-07-22 17:19:58,143 INFO [main] o.m.m.c.e.d.MPFDetectionMessenger - Detection request received with message length = 550
2021-07-22 17:19:58,143 INFO [main] o.m.m.c.e.d.MPFDetectionMessenger - Detection request received with job ID 1369 for media file /home/mpf/git/openmpf-projects/openmpf/trunk/install/share/remote-media/test-first-page-images.pdf
2021-07-22 17:19:58,143 INFO [main] o.m.m.d.t.TikaImageDetectionComponent - [Job 1369:test-first-page-images.pdf] Starting job.
2021-07-22 17:19:58,778 WARN [main] o.m.m.d.t.TikaImageDetectionComponent - File /home/mpf/git/openmpf-projects/openmpf/trunk/install/share/artifacts/1369/tika-extracted/image0.jpg already exists. Can't write new file.
2021-07-22 17:19:58,851 WARN [main] o.m.m.d.t.TikaImageDetectionComponent - File /home/mpf/git/openmpf-projects/openmpf/trunk/install/share/artifacts/1369/tika-extracted/image1.jpg already exists. Can't write new file.
2021-07-22 17:19:58,855 ERROR [main] o.m.m.d.t.TikaImageDetectionComponent - Error processing file at : /home/mpf/git/openmpf-projects/openmpf/trunk/install/share/artifacts/1369
org.apache.tika.exception.TikaException: Unable to extract PDF content
	at org.apache.tika.parser.pdf.PDF2XHTML.process(PDF2XHTML.java:148) ~[mpf-tika-image-detection-component-6.2.jar:?]
	at org.apache.tika.parser.pdf.PDFParser.parse(PDFParser.java:171) ~[mpf-tika-image-detection-component-6.2.jar:?]
	at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:280) ~[tika-core-1.18.jar:1.18]
	at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:280) ~[tika-core-1.18.jar:1.18]
	at org.apache.tika.parser.AutoDetectParser.parse(AutoDetectParser.java:143) ~[tika-core-1.18.jar:1.18]
	at org.mitre.mpf.detection.tika.TikaImageDetectionComponent.parseDocument(TikaImageDetectionComponent.java:108) [mpf-tika-image-detection-component-6.2.jar:?]
	at org.mitre.mpf.detection.tika.TikaImageDetectionComponent.getDetections(TikaImageDetectionComponent.java:163) [mpf-tika-image-detection-component-6.2.jar:?]
	at org.mitre.mpf.component.executor.detection.MPFDetectionMessenger.onMessage(MPFDetectionMessenger.java:164) [mpf-java-component-executor-6.2.jar:?]
	at org.mitre.mpf.component.executor.detection.MPFDetectionMain.processMessages(MPFDetectionMain.java:122) [mpf-java-component-executor-6.2.jar:?]
	at org.mitre.mpf.component.executor.detection.MPFDetectionMain.main(MPFDetectionMain.java:79) [mpf-java-component-executor-6.2.jar:?]
Caused by: java.io.IOException: File /home/mpf/git/openmpf-projects/openmpf/trunk/install/share/artifacts/1369/tika-extracted/image0.jpg already exists. Can't write file.
	at org.mitre.mpf.detection.tika.EmbeddedContentExtractor.parseEmbedded(EmbeddedContentExtractor.java:164) ~[mpf-tika-image-detection-component-6.2.jar:?]
	at org.apache.tika.parser.pdf.PDF2XHTML.extractImages(PDF2XHTML.java:273) ~[mpf-tika-image-detection-component-6.2.jar:?]
	at org.apache.tika.parser.pdf.PDF2XHTML.endPage(PDF2XHTML.java:167) ~[mpf-tika-image-detection-component-6.2.jar:?]
	at org.apache.pdfbox.text.PDFTextStripper.processPage(PDFTextStripper.java:393) ~[pdfbox-2.0.9.jar:2.0.9]
	at org.apache.tika.parser.pdf.PDF2XHTML.processPage(PDF2XHTML.java:156) ~[mpf-tika-image-detection-component-6.2.jar:?]
	at org.apache.pdfbox.text.PDFTextStripper.processPages(PDFTextStripper.java:319) ~[pdfbox-2.0.9.jar:2.0.9]
	at org.apache.pdfbox.text.PDFTextStripper.writeText(PDFTextStripper.java:266) ~[pdfbox-2.0.9.jar:2.0.9]
	at org.apache.tika.parser.pdf.PDF2XHTML.process(PDF2XHTML.java:126) ~[mpf-tika-image-detection-component-6.2.jar:?]
	... 9 more
```

The issue is that the component uses the `/home/mpf/git/openmpf-projects/openmpf/trunk/install/share/artifacts/1369/tika-extracted` dir for both pieces of media since they are part of the same job.

Note that it's possible for the component to be run with the same piece of media twice in the same job, so we can't use the name of the media for the sub-directory. The media id generated by the WFM is always unique, so one option would be to use that for the subdirectory name; however, the problem is that the WFM does not provide the media id to the component.

The WFM could provide the media id in the media metadata, but then if a job producer manually provides the media metadata they would have to provide the value themselves, which is strange, or the WFM would have to add it. Thing is, the CLI Runner code would have to add it too, and we don't want to add too much WFM-like logic to that. Just seems messy.

There is also the potential use case where there are two stages in a pipeline that generate derivative media, such as deriving new media from derivative media, and then we'd have to add a task id sub-directory within the media id sub-directory (similar to what the WFM does for artifact extraction currently).

All of that said, please use a GUID for each piece of media (component sub-job) so you end up with:

`artifacts/<job-id>/tika-extracted/<GUID-for-sub-job>`

You can use `UUID.randomUUID()`. We use that in the WFM in a few places.

---

**Review by jrobble — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/271)* status: all files reviewed, 1 unresolved discussion (waiting on @hhuangMITRE)

*[a discussion](https://reviewable.io/reviews/openmpf/openmpf-components/271#-MfF5NXCADEil3nD9Ts-:-MfdgAb11rGvTrEPVwTV:b-jr2fu0) (no related file):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Using the web UI, I ran a job with `test-first-page-images.pdf` and `test-tika-image-extraction.pdf` at the same time. The JSON output shows:

```
   "errors": [
      {
         "mediaId": 1,
         "details": [
            {
               "source": "TIKAIMAGE",
               "code": "COULD_NOT_READ_MEDIA",
               "message": "Error processing file at : /home/mpf/git/openmpf-projects/openmpf/trunk/install/share/artifacts/1369"
            }
         ]
      }
   ],
```

The component log shows:

```
2021-07-22 17:19:56,730 INFO [main] o.m.m.c.e.d.MPFDetectionMessenger - Detection request received with job ID 1369 for media file /home/mpf/git/openmpf-projects/openmpf/trunk/install/share/remote-media/test-tika-image-extraction.pdf
2021-07-22 17:19:56,731 INFO [main] o.m.m.d.t.TikaImageDetectionComponent - [Job 1369:test-tika-image-extraction.pdf] Starting job.
2021-07-22 17:19:58,097 INFO [main] o.m.m.d.t.TikaImageDetectionComponent - [Job 1369:test-tika-image-extraction.pdf] Processing complete. Generated 4 generic tracks.
2021-07-22 17:19:58,139 INFO [main] o.m.m.c.e.d.MPFDetectionMessenger - Detection response sent for job ID 1369
2021-07-22 17:19:58,143 INFO [main] o.m.m.c.e.d.MPFDetectionMessenger - Detection request received with message length = 550
2021-07-22 17:19:58,143 INFO [main] o.m.m.c.e.d.MPFDetectionMessenger - Detection request received with job ID 1369 for media file /home/mpf/git/openmpf-projects/openmpf/trunk/install/share/remote-media/test-first-page-images.pdf
2021-07-22 17:19:58,143 INFO [main] o.m.m.d.t.TikaImageDetectionComponent - [Job 1369:test-first-page-images.pdf] Starting job.
2021-07-22 17:19:58,778 WARN [main] o.m.m.d.t.TikaImageDetectionComponent - File /home/mpf/git/openmpf-projects/openmpf/trunk/install/share/artifacts/1369/tika-extracted/image0.jpg already exists. Can't write new file.
2021-07-22 17:19:58,851 WARN [main] o.m.m.d.t.TikaImageDetectionComponent - File /home/mpf/git/openmpf-projects/openmpf/trunk/install/share/artifacts/1369/tika-extracted/image1.jpg already exists. Can't write new file.
2021-07-22 17:19:58,855 ERROR [main] o.m.m.d.t.TikaImageDetectionComponent - Error processing file at : /home/mpf/git/openmpf-projects/openmpf/trunk/install/share/artifacts/1369
org.apache.tika.exception.TikaException: Unable to extract PDF content
	at org.apache.tika.parser.pdf.PDF2XHTML.process(PDF2XHTML.java:148) ~[mpf-tika-image-detection-component-6.2.jar:?]
	at org.apache.tika.parser.pdf.PDFParser.parse(PDFParser.java:171) ~[mpf-tika-image-detection-component-6.2.jar:?]
	at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:280) ~[tika-core-1.18.jar:1.18]
	at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:280) ~[tika-core-1.18.jar:1.18]
	at org.apache.tika.parser.AutoDetectParser.parse(AutoDetectParser.java:143) ~[tika-core-1.18.jar:1.18]
	at org.mitre.mpf.detection.tika.TikaImageDetectionComponent.parseDocument(TikaImageDetectionComponent.java:108) [mpf-tika-image-detection-component-6.2.jar:?]
	at org.mitre.mpf.detection.tika.TikaImageDetectionComponent.getDetections(TikaImageDetectionComponent.java:163) [mpf-tika-image-detection-component-6.2.jar:?]
	at org.mitre.mpf.component.executor.detection.MPFDetectionMessenger.onMessage(MPFDetectionMessenger.java:164) [mpf-java-component-executor-6.2.jar:?]
	at org.mitre.mpf.component.executor.detection.MPFDetectionMain.processMessages(MPFDetectionMain.java:122) [mpf-java-component-executor-6.2.jar:?]
	at org.mitre.mpf.component.executor.detection.MPFDetectionMain.main(MPFDetectionMain.java:79) [mpf-java-component-executor-6.2.jar:?]
Caused by: java.io.IOException: File /home/mpf/git/openmpf-projects/openmpf/trunk/install/share/artifacts/1369/tika-extracted/image0.jpg already exists. Can't write file.
	at org.mitre.mpf.detection.tika.EmbeddedContentExtractor.parseEmbedded(EmbeddedContentExtractor.java:164) ~[mpf-tika-image-detection-component-6.2.jar:?]
	at org.apache.tika.parser.pdf.PDF2XHTML.extractImages(PDF2XHTML.java:273) ~[mpf-tika-image-detection-component-6.2.jar:?]
	at org.apache.tika.parser.pdf.PDF2XHTML.endPage(PDF2XHTML.java:167) ~[mpf-tika-image-detection-component-6.2.jar:?]
	at org.apache.pdfbox.text.PDFTextStripper.processPage(PDFTextStripper.java:393) ~[pdfbox-2.0.9.jar:2.0.9]
	at org.apache.tika.parser.pdf.PDF2XHTML.processPage(PDF2XHTML.java:156) ~[mpf-tika-image-detection-component-6.2.jar:?]
	at org.apache.pdfbox.text.PDFTextStripper.processPages(PDFTextStripper.java:319) ~[pdfbox-2.0.9.jar:2.0.9]
	at org.apache.pdfbox.text.PDFTextStripper.writeText(PDFTextStripper.java:266) ~[pdfbox-2.0.9.jar:2.0.9]
	at org.apache.tika.parser.pdf.PDF2XHTML.process(PDF2XHTML.java:126) ~[mpf-tika-image-detection-component-6.2.jar:?]
	... 9 more
```

The issue is that the component uses the `/home/mpf/git/openmpf-projects/openmpf/trunk/install/share/artifacts/1369/tika-extracted` dir for both pieces of media since they are part of the same job.

Note that it's possible for the component to be run with the same piece of media twice in the same job, so we can't use the name of the media for the sub-directory. The media id generated by the WFM is always unique, so one option would be to use that for the subdirectory name; however, the problem is that the WFM does not provide the media id to the component.

The WFM could provide the media id in the media metadata, but then if a job producer manually provides the media metadata they would have to provide the value themselves, which is strange, or the WFM would have to add it. Thing is, the CLI Runner code would have to add it too, and we don't want to add too much WFM-like logic to that. Just seems messy.

There is also the potential use case where there are two stages in a pipeline that generate derivative media, such as deriving new media from derivative media, and then we'd have to add a task id sub-directory within the media id sub-directory (similar to what the WFM does for artifact extraction currently).

All of that said, please use a GUID for each piece of media (component sub-job) so you end up with:

`artifacts/<job-id>/tika-extracted/<GUID-for-sub-job>`

You can use `UUID.randomUUID()`. We use that in the WFM in a few places.

</blockquote></details>

Here's the [issue](https://github.com/openmpf/openmpf/issues/1379). Please resolve it in this PR. Make sure to add the issue to the PR description under `Issues`.

---

**Review by jrobble — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/271)* status: all files reviewed, 1 unresolved discussion (waiting on @hhuangMITRE)

*[a discussion](https://reviewable.io/reviews/openmpf/openmpf-components/271#-MfF5NXCADEil3nD9Ts-:-Mfdh0SD49eiFxIhlF8D:b-ajteey) (no related file):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Here's the [issue](https://github.com/openmpf/openmpf/issues/1379). Please resolve it in this PR. Make sure to add the issue to the PR description under `Issues`.
</blockquote></details>

Also, please add a unit test for it.

---

**Review by hhuangMITRE — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/271)* status: 7 of 13 files reviewed, 1 unresolved discussion (waiting on @jrobble)

*[a discussion](https://reviewable.io/reviews/openmpf/openmpf-components/271#-MfF5NXCADEil3nD9Ts-:-MfiAbAU4O5jmP2CUG-9:b-57b5n8) (no related file):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Also, please add a unit test for it.
</blockquote></details>

Done, thanks for catching this error and updating the unit tests. I've submitted the UUID identifier update + tika 1.27 pom update. 

---

**Review by jrobble — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r3, 13 of 13 files at r4.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/271)* status: all files reviewed, 5 unresolved discussions (waiting on @hhuangMITRE)

___
*[java/TikaImageDetection/src/main/java/org/apache/tika/parser/pdf/ImageGraphicsEngine.java, line 1 at r4](https://reviewable.io/reviews/openmpf/openmpf-components/271#-MfiyDoCDpnWgHSGCGM-:-MfiyDoD9eRMgGBjjDol:bnz4osk) ([raw file](https://github.com/openmpf/openmpf-components/blob/f8a8c0f0d926dcecc9d590884c46ffa1a832de70/java/TikaImageDetection/src/main/java/org/apache/tika/parser/pdf/ImageGraphicsEngine.java#L1)):*
> ```Java
> /******************************************************************************
> ```

Since we modified this file, mention it in the `LICENSE` file.
___
*[java/TikaImageDetection/src/main/java/org/apache/tika/parser/pdf/PDF2XHTML.java, line 1 at r4](https://reviewable.io/reviews/openmpf/openmpf-components/271#-Mfizt5J1qXq-EZaTxi_:-Mfizt5J1qXq-EZaTxia:bktsvvo) ([raw file](https://github.com/openmpf/openmpf-components/blob/b76a6f9be228968020380f5ba8108ef899c811ec/java/TikaImageDetection/src/main/java/org/apache/tika/parser/pdf/PDF2XHTML.java#L1)):*
> ```Java
> /******************************************************************************
> ```

These header block comments were reverted back to the non-MITRE ones. Does that mean you removed your modifications to this file? If so, remove it from `LICENSE`. If not, keep the MITRE header blocks.
___
*[java/TikaImageDetection/src/main/java/org/mitre/mpf/detection/tika/EmbeddedContentExtractor.java, line 71 at r4](https://reviewable.io/reviews/openmpf/openmpf-components/271#-Mfj00lyAJ-nflAiljBZ:-Mfj00lz4Irf4K_C0sKP:b4srf52) ([raw file](https://github.com/openmpf/openmpf-components/blob/f8a8c0f0d926dcecc9d590884c46ffa1a832de70/java/TikaImageDetection/src/main/java/org/mitre/mpf/detection/tika/EmbeddedContentExtractor.java#L71)):*
> ```Java
>         current = new ArrayList<String>();
> 
>         String unique_id = UUID.randomUUID().toString();
> ```

Generally, we don't use underscores for variable names in Java. Please change this to use camelCase.
___
*[java/TikaImageDetection/src/test/java/org/mitre/mpf/detection/tika/TestTikaImageDetectionComponent.java, line 111 at r4](https://reviewable.io/reviews/openmpf/openmpf-components/271#-Mfj3xrU7xfbM__TuBdX:-Mfj3xrVBMZ1dp0myI-m:b-txq35c) ([raw file](https://github.com/openmpf/openmpf-components/blob/f8a8c0f0d926dcecc9d590884c46ffa1a832de70/java/TikaImageDetection/src/test/java/org/mitre/mpf/detection/tika/TestTikaImageDetectionComponent.java#L111)):*
> ```Java
>         String uuid2 = tracks2.get(0).getDetectionProperties().get("SAVED_IMAGES").split("/")[5];
> 
>         assertTrue(uuid1 != uuid2);
> ```

String comparison in Java should always be done using `.equals()`. I was going to say to change this to:

```
assertFalse(uuid1.equals(uuid2));
```

However, IntelliJ is telling me that the following is better, so use this:

```
assertNotEquals(uuid1, uuid2);
```

That uses `.equals()` under the hood.
___
*[java/TikaImageDetection/src/test/java/org/mitre/mpf/detection/tika/TestTikaImageDetectionComponent.java, line 226 at r4](https://reviewable.io/reviews/openmpf/openmpf-components/271#-Mfj8b1L8ca3gjfViLLc:-Mfj8b1M8cg1PYPIzYKw:b8enulv) ([raw file](https://github.com/openmpf/openmpf-components/blob/f8a8c0f0d926dcecc9d590884c46ffa1a832de70/java/TikaImageDetection/src/test/java/org/mitre/mpf/detection/tika/TestTikaImageDetectionComponent.java#L226)):*
When I try to open the file in CentOS 7 by double-clicking on it (which uses Image Viewer), I got the error:

> Error interpreting JPEG image file (Not a JPEG file: starts with 0x89 0x50)

This happens for image0.jpg and image2.jpg. Changing the extension to .png works.

This problem doesn't happen if you open the images in Shotwell Viewer, which probably looks at the magic bytes.

The `file` command, which looks at the magic bytes, says it's a .png:

```
file --mime-type --brief /home/mpf/git/openmpf-projects/openmpf/trunk/install/share/artifacts/1384/tika-extracted/cc5bf550-eda2-4da7-9310-d1ca0184baaf/image0.jpg

image/png
```

**Review by hhuangMITRE — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/271)* status: 21 of 27 files reviewed, 5 unresolved discussions (waiting on @jrobble)

___
*[java/TikaImageDetection/src/main/java/org/apache/tika/parser/pdf/ImageGraphicsEngine.java, line 1 at r4](https://reviewable.io/reviews/openmpf/openmpf-components/271#-MfiyDoCDpnWgHSGCGM-:-MfnidBVByCnWgBbuU52:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/f8a8c0f0d926dcecc9d590884c46ffa1a832de70/java/TikaImageDetection/src/main/java/org/apache/tika/parser/pdf/ImageGraphicsEngine.java#L1)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Since we modified this file, mention it in the `LICENSE` file.
</blockquote></details>

Done.
___
*[java/TikaImageDetection/src/main/java/org/apache/tika/parser/pdf/PDF2XHTML.java, line 1 at r4](https://reviewable.io/reviews/openmpf/openmpf-components/271#-Mfizt5J1qXq-EZaTxi_:-Mfnb05O0vDaqQWBHqDS:b7r6jx9) ([raw file](https://github.com/openmpf/openmpf-components/blob/b76a6f9be228968020380f5ba8108ef899c811ec/java/TikaImageDetection/src/main/java/org/apache/tika/parser/pdf/PDF2XHTML.java#L1)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

These header block comments were reverted back to the non-MITRE ones. Does that mean you removed your modifications to this file? If so, remove it from `LICENSE`. If not, keep the MITRE header blocks.
</blockquote></details>

Yep, the src code was refactored into ImageGraphicsEngine.java so I've transferred the changes over there and reverted the header blocks here (no change from original src code now). I've updated `LICENSE` to mention the new changed file.
___
*[java/TikaImageDetection/src/main/java/org/mitre/mpf/detection/tika/EmbeddedContentExtractor.java, line 71 at r4](https://reviewable.io/reviews/openmpf/openmpf-components/271#-Mfj00lyAJ-nflAiljBZ:-MfnbCrTBcptumWVxYub:b67ul1x) ([raw file](https://github.com/openmpf/openmpf-components/blob/f8a8c0f0d926dcecc9d590884c46ffa1a832de70/java/TikaImageDetection/src/main/java/org/mitre/mpf/detection/tika/EmbeddedContentExtractor.java#L71)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Generally, we don't use underscores for variable names in Java. Please change this to use camelCase.
</blockquote></details>

Thanks for catching that, was in Python mode when I made the edit.
___
*[java/TikaImageDetection/src/test/java/org/mitre/mpf/detection/tika/TestTikaImageDetectionComponent.java, line 111 at r4](https://reviewable.io/reviews/openmpf/openmpf-components/271#-Mfj3xrU7xfbM__TuBdX:-Mfnhly77LYghrRyIQhn:baww4fv) ([raw file](https://github.com/openmpf/openmpf-components/blob/f8a8c0f0d926dcecc9d590884c46ffa1a832de70/java/TikaImageDetection/src/test/java/org/mitre/mpf/detection/tika/TestTikaImageDetectionComponent.java#L111)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

String comparison in Java should always be done using `.equals()`. I was going to say to change this to:

```
assertFalse(uuid1.equals(uuid2));
```

However, IntelliJ is telling me that the following is better, so use this:

```
assertNotEquals(uuid1, uuid2);
```

That uses `.equals()` under the hood.
</blockquote></details>

Done. I also moved this test to the bottom as it made more sense to first test out PDF#1, PDF#2, then both combined. 
___
*[java/TikaImageDetection/src/test/java/org/mitre/mpf/detection/tika/TestTikaImageDetectionComponent.java, line 226 at r4](https://reviewable.io/reviews/openmpf/openmpf-components/271#-Mfj8b1L8ca3gjfViLLc:-MfniR31BttecrASdso4:bsabjpx) ([raw file](https://github.com/openmpf/openmpf-components/blob/f8a8c0f0d926dcecc9d590884c46ffa1a832de70/java/TikaImageDetection/src/test/java/org/mitre/mpf/detection/tika/TestTikaImageDetectionComponent.java#L226)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

When I try to open the file in CentOS 7 by double-clicking on it (which uses Image Viewer), I got the error:

> Error interpreting JPEG image file (Not a JPEG file: starts with 0x89 0x50)

This happens for image0.jpg and image2.jpg. Changing the extension to .png works.

This problem doesn't happen if you open the images in Shotwell Viewer, which probably looks at the magic bytes.

The `file` command, which looks at the magic bytes, says it's a .png:

```
file --mime-type --brief /home/mpf/git/openmpf-projects/openmpf/trunk/install/share/artifacts/1384/tika-extracted/cc5bf550-eda2-4da7-9310-d1ca0184baaf/image0.jpg

image/png
```


</blockquote></details>

Fixed, there was some issues with when I used Word to create a multipage PDF (from the OpenMPF one pager + custom text). I recreated the document so that the issues no longer exist and updated the unit tests for both Tika components.

**Review by jrobble — CHANGES_REQUESTED** [review]
> Reviewed 5 of 6 files at r5.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/271)* status: 26 of 27 files reviewed, 3 unresolved discussions (waiting on @hhuangMITRE and @jrobble)

___
*[java/TikaImageDetection/src/main/java/org/mitre/mpf/detection/tika/EmbeddedContentExtractor.java, line 71 at r5](https://reviewable.io/reviews/openmpf/openmpf-components/271#-Mg7JXmW49na_P9vM360:-Mg7JXmW49na_P9vM361:bu69aev) ([raw file](https://github.com/openmpf/openmpf-components/blob/7f2d256ae35ece9888ac7349caaa93b1fb37f75e/java/TikaImageDetection/src/main/java/org/mitre/mpf/detection/tika/EmbeddedContentExtractor.java#L71)):*
> ```Java
>         current = new ArrayList<String>();
> 
>         String uniqueID = UUID.randomUUID().toString();
> ```

We follow the Google style guides. [Here's](https://google.github.io/styleguide/javaguide.html#s5.3-camel-case) the Java section on camel case. Note that acronyms and abbreviations use lower-case letters after the first one.
___
*[java/TikaImageDetection/src/test/java/org/mitre/mpf/detection/tika/TestTikaImageDetectionComponent.java, line 166 at r5](https://reviewable.io/reviews/openmpf/openmpf-components/271#-Mg7NQsw6dcd74Jyjyta:-Mg7NQsy1beXJRHihYjJ:bf5b0yz) ([raw file](https://github.com/openmpf/openmpf-components/blob/7f2d256ae35ece9888ac7349caaa93b1fb37f75e/java/TikaImageDetection/src/test/java/org/mitre/mpf/detection/tika/TestTikaImageDetectionComponent.java#L166)):*
> ```Java
>     @Test
>     public void testGetDetectionsFirstPageImagesOnly() throws IOException, MPFComponentDetectionError {
>         String mediaPath = this.getClass().getResource("/data/test-first-page-images.pdf").getPath();
> ```

Honestly, this is kind of a strange test media for this component since the only image that gets extracted from it is the orange banner and the other stuff related to the diagram is ignored. `test-first-page-images.pdf` (note the plural) is misleading since there is only one image extracted.
___
*[java/TikaTextDetection/src/test/java/org/mitre/mpf/detection/tika/TestTikaTextDetectionComponent.java, line 102 at r5](https://reviewable.io/reviews/openmpf/openmpf-components/271#-Mg7IyxW2aIZfpBNupBk:-Mg7IyxW2aIZfpBNupBl:b80f5v7) ([raw file](https://github.com/openmpf/openmpf-components/blob/7f2d256ae35ece9888ac7349caaa93b1fb37f75e/java/TikaTextDetection/src/test/java/org/mitre/mpf/detection/tika/TestTikaTextDetectionComponent.java#L102)):*
> ```Java
> 
>     @Test
>     public void testGetDetectionsPDFFile() throws MPFComponentDetectionError {
> ```

As mentioned in another comment, in Java acronyms and abbreviations use lower-case letters after the first one.

**Review by jrobble — COMMENTED** [review]
> Reviewed 1 of 6 files at r5.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/271)* status: all files reviewed, 3 unresolved discussions (waiting on @hhuangMITRE)

**Review by hhuangMITRE — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/271)* status: 21 of 28 files reviewed, 3 unresolved discussions (waiting on @jrobble)

___
*[java/TikaImageDetection/src/main/java/org/mitre/mpf/detection/tika/EmbeddedContentExtractor.java, line 71 at r5](https://reviewable.io/reviews/openmpf/openmpf-components/271#-Mg7JXmW49na_P9vM360:-Mg7q5in0g6xlgvmoIkd:bq2ztar) ([raw file](https://github.com/openmpf/openmpf-components/blob/7f2d256ae35ece9888ac7349caaa93b1fb37f75e/java/TikaImageDetection/src/main/java/org/mitre/mpf/detection/tika/EmbeddedContentExtractor.java#L71)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

We follow the Google style guides. [Here's](https://google.github.io/styleguide/javaguide.html#s5.3-camel-case) the Java section on camel case. Note that acronyms and abbreviations use lower-case letters after the first one.
</blockquote></details>

Thanks Jeff for the resource/reminder! I went through and also fixed some other camel case issues I noticed (`LOG`-> `log`, `ID`->`id`, `PDF`->`pdf`) in both tika components.
___
*[java/TikaImageDetection/src/test/java/org/mitre/mpf/detection/tika/TestTikaImageDetectionComponent.java, line 166 at r5](https://reviewable.io/reviews/openmpf/openmpf-components/271#-Mg7NQsw6dcd74Jyjyta:-Mg7qUa8CQOaQaNXd_TR:bcvtcjq) ([raw file](https://github.com/openmpf/openmpf-components/blob/7f2d256ae35ece9888ac7349caaa93b1fb37f75e/java/TikaImageDetection/src/test/java/org/mitre/mpf/detection/tika/TestTikaImageDetectionComponent.java#L166)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Honestly, this is kind of a strange test media for this component since the only image that gets extracted from it is the orange banner and the other stuff related to the diagram is ignored. `test-first-page-images.pdf` (note the plural) is misleading since there is only one image extracted.
</blockquote></details>

Yeah, this test case originally had two jpgs and a png format (due to the Word conversion breaking up the images in the original PDF). I wanted to make sure the component can extract all of them properly + ignore any extraneous text.

I think the original PDF test can incorporate these checks, so I've added a PNG image into the original PDF unit test and removed the redundant, single image test case and associated PDF.

Once other document formats are supported, I plan to add a .docx test case and a pptx test case (and update the multi-document test too), so there would be a unit test per document format.
___
*[java/TikaTextDetection/src/test/java/org/mitre/mpf/detection/tika/TestTikaTextDetectionComponent.java, line 102 at r5](https://reviewable.io/reviews/openmpf/openmpf-components/271#-Mg7IyxW2aIZfpBNupBk:-Mg7wCgqAoREa5U45_jk:bj3eodx) ([raw file](https://github.com/openmpf/openmpf-components/blob/7f2d256ae35ece9888ac7349caaa93b1fb37f75e/java/TikaTextDetection/src/test/java/org/mitre/mpf/detection/tika/TestTikaTextDetectionComponent.java#L102)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

As mentioned in another comment, in Java acronyms and abbreviations use lower-case letters after the first one.
</blockquote></details>

Fixed, thanks!

**Review by jrobble — APPROVED** [review]
> Reviewed 7 of 7 files at r6.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/271)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @hhuangMITRE)

___
*[java/TikaImageDetection/src/test/java/org/mitre/mpf/detection/tika/TestTikaImageDetectionComponent.java, line 166 at r5](https://reviewable.io/reviews/openmpf/openmpf-components/271#-Mg7NQsw6dcd74Jyjyta:-MgCT6AkAGP5Ir2oy62S:b-t8j34n) ([raw file](https://github.com/openmpf/openmpf-components/blob/7f2d256ae35ece9888ac7349caaa93b1fb37f75e/java/TikaImageDetection/src/test/java/org/mitre/mpf/detection/tika/TestTikaImageDetectionComponent.java#L166)):*
<details><summary><i>Previously, hhuangMITRE (Howard W Huang) wrote…</i></summary><blockquote>

Yeah, this test case originally had two jpgs and a png format (due to the Word conversion breaking up the images in the original PDF). I wanted to make sure the component can extract all of them properly + ignore any extraneous text.

I think the original PDF test can incorporate these checks, so I've added a PNG image into the original PDF unit test and removed the redundant, single image test case and associated PDF.

Once other document formats are supported, I plan to add a .docx test case and a pptx test case (and update the multi-document test too), so there would be a unit test per document format.
</blockquote></details>

I like your test cases for ignoring extraneous text and handling .jpg and .png images.

Also, I agree that it's best to add tests for the new formats once they're supported.

**Pull request merged**
