### PR TITLE
Updated caffe readme

### PR DESCRIPTION
**Pull request by clnowacki**
Caffe component README has been updated to explain how to add models, pipelines, and spectral hash input files.

---
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/40)

### CODE REVIEW

**Comment by jrobble** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[cpp/CaffeDetection/README.md, line 40 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-components/40#-Kw_k-0uTwYRk4zSGK_x:-Kw_k-0uTwYRk4zSGK_y:b-gf0imv) ([raw file](https://github.com/openmpf/openmpf-components/blob/2af12d4620e7a8993b3b2733be07aa8c14090379/cpp/CaffeDetection/README.md#L40)):*
> ```Markdown
> The Caffe component supports the calculation of the spectral hash for a given input image, or every frame of an input video. The spectral hash is computed according to the method outlined in ["Spectral Hashing" (Y. Weiss, et. al.)](http://papers.nips.cc/paper/3383-spectral-hashing.pdf).
> 
> The Caffe component requires a set of input parameters for the spectral hash computation. These are defined in a JSON-formatted input file. An example of a spectral hash parameter file is provided with the Caffe component source code in `plugin-files/config/bvlc_googlenet_spectral_hash.json`. The parameters in that file were derived from the GoogLeNet model training dataset (ILSVRC 2012). On a deployment machine, the correct full path name for this file is ${MPF_HOME}/plugins/CaffeDetection/config/bvlc_googlenet_spectral_hash.json.
> ```

Put `${MPF_HOME}/plugins/CaffeDetection/config` in tick marks like the other paths in this file.

---

*[cpp/CaffeDetection/README.md, line 47 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-components/40#-Kw_kKhZwdghW3_lZNay:-Kw_kKhZwdghW3_lZNaz:b-z9qq40) ([raw file](https://github.com/openmpf/openmpf-components/blob/2af12d4620e7a8993b3b2733be07aa8c14090379/cpp/CaffeDetection/README.md#L47)):*
Let's add more detail:

> Create an input JSON file similar to `plugin-files/config/bvlc_googlenet_spectral_hash.json`. Place your file in the same directory.

---

*[cpp/CaffeDetection/README.md, line 51 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-components/40#-Kw_joT0hHKnZCVLzdP8:-Kw_joT1U1TwGu7DTDQu:b-95d3yb) ([raw file](https://github.com/openmpf/openmpf-components/blob/2af12d4620e7a8993b3b2733be07aa8c14090379/cpp/CaffeDetection/README.md#L51)):*
Put `${MPF_HOME}/plugins/CaffeDetection/config` in tick marks like the other paths in this file.

Use lowercase action:

> creating your new action.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-components/40)*

**Comment by jrobble** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-components/40)*

**Comment by clnowacki** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[cpp/CaffeDetection/README.md, line 40 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-components/40#-Kw_k-0uTwYRk4zSGK_x:-Kw_zYbVsS-xQhmA5-_L:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/2af12d4620e7a8993b3b2733be07aa8c14090379/cpp/CaffeDetection/README.md#L40)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Put `${MPF_HOME}/plugins/CaffeDetection/config` in tick marks like the other paths in this file.
</blockquote></details>

Done.

---

*[cpp/CaffeDetection/README.md, line 47 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-components/40#-Kw_kKhZwdghW3_lZNay:-Kw_zqMRNyHIkoPVPlVR:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/2af12d4620e7a8993b3b2733be07aa8c14090379/cpp/CaffeDetection/README.md#L47)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Let's add more detail:

> Create an input JSON file similar to `plugin-files/config/bvlc_googlenet_spectral_hash.json`. Place your file in the same directory.
</blockquote></details>

Done.

---

*[cpp/CaffeDetection/README.md, line 51 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-components/40#-Kw_joT0hHKnZCVLzdP8:-Kwa--E9Qtu85IYeGpdm:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/2af12d4620e7a8993b3b2733be07aa8c14090379/cpp/CaffeDetection/README.md#L51)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Put `${MPF_HOME}/plugins/CaffeDetection/config` in tick marks like the other paths in this file.

Use lowercase action:

> creating your new action.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-components/40)*

**Comment by clnowacki** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-components/40)*

**Comment by clnowacki** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-components/40)*

**Pull request merged**
