### PR TITLE
Feature: Update Tika and text components to process derivative images extracted from PDFs.

### PR DESCRIPTION
**Pull request by hhuangMITRE**
**Issues:**

- https://github.com/openmpf/openmpf/issues/792 
- https://github.com/openmpf/openmpf/issues/803
- https://github.com/openmpf/openmpf/issues/1303
- https://github.com/openmpf/openmpf/issues/1304
- https://github.com/openmpf/openmpf/issues/808
- https://github.com/openmpf/openmpf/issues/1372

**Related PRs:**

- https://github.com/openmpf/openmpf/pull/1365
- https://github.com/openmpf/openmpf.github.io/pull/136

---
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/266)

### CODE REVIEW

**Review by jrobble — CHANGES_REQUESTED** [review]
> Reviewed 2 of 13 files at r1, 17 of 17 files at r2.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/266)* status: all files reviewed, 6 unresolved discussions (waiting on @hhuangMITRE)

___
*[java/TikaImageDetection/src/main/java/org/mitre/mpf/detection/tika/EmbeddedContentExtractor.java, line 57 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/266#-MfnVsHb88uqvW3VzyE4:-MfnVsHb88uqvW3VzyE5:bwzpyx) ([raw file](https://github.com/openmpf/openmpf-components/blob/e83a99249dcf47a6230f4b2e34e82af2c6d3a0dd/java/TikaImageDetection/src/main/java/org/mitre/mpf/detection/tika/EmbeddedContentExtractor.java#L57)):*
> ```Java
>     private int id, pagenum;
>     private ArrayList<ArrayList<String>> imageMap;
>     private LinkedHashMap<String, TreeSet<String>> imagePageMap;
> ```

@hhuangmitre : Please leave a comment stating what `imagePageMap` contains. What is the key? What is the value a set of?
___
*[java/TikaImageDetection/src/main/java/org/mitre/mpf/detection/tika/EmbeddedContentExtractor.java, line 119 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/266#-MhtCATB-weNxVBC3xH4:-MhtCATB-weNxVBC3xH5:bx7fwzt) ([raw file](https://github.com/openmpf/openmpf-components/blob/201fd48b26c2e9a24d020d8bd127e3dbf34905a8/java/TikaImageDetection/src/main/java/org/mitre/mpf/detection/tika/EmbeddedContentExtractor.java#L119)):*
> ```Java
>             imageMap.add(current);
>             if (separatePages) {
>                 outputDir = Paths.get(path + "/tika-extracted/page-" + (pagenum + 1)); // TODO: Shouldn't this use the UUID?
> ```

@hhuangmitre : Please address this.
___
*[java/TikaImageDetection/src/main/java/org/mitre/mpf/detection/tika/ImageExtractionContentHandler.java, line 49 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/266#-MhtHUgB4282SsVeOSS7:-MhtHNNyEAzTBSZsag-v:bvwqk9h) ([raw file](https://github.com/openmpf/openmpf-components/blob/201fd48b26c2e9a24d020d8bd127e3dbf34905a8/java/TikaImageDetection/src/main/java/org/mitre/mpf/detection/tika/ImageExtractionContentHandler.java#L49)):*
> ```Java
> 
>     public void startElement (String uri, String localName, String qName, Attributes atts) {
>         if (pageTag.equals(qName) && (atts.getValue("class").equals("page"))) { // TODO: NPE on jrobble-test.odp
> ```

@hhuangmitre : Please look into this. I will send you the file separately.
___
*[java/TikaImageDetection/src/main/java/org/mitre/mpf/detection/tika/TikaImageDetectionComponent.java, line 166 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/266#-MfnV_sg2HRu_RlqRHbf:-MfnV_sg2HRu_RlqRHbg:b-x4o22n) ([raw file](https://github.com/openmpf/openmpf-components/blob/e83a99249dcf47a6230f4b2e34e82af2c6d3a0dd/java/TikaImageDetection/src/main/java/org/mitre/mpf/detection/tika/TikaImageDetectionComponent.java#L166)):*
> ```Java
> 
>         List<MPFGenericTrack> tracks = new LinkedList<MPFGenericTrack>();
>         int page = 0;
> ```

`page` is not used anywhere, so I removed it.
___
*[java/TikaImageDetection/src/main/java/org/mitre/mpf/detection/tika/TikaImageDetectionComponent.java, line 131 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/266#-MhtCJc32QMiufPUhlkM:-MhtCJc32QMiufPUhlkN:bvd8vo0) ([raw file](https://github.com/openmpf/openmpf-components/blob/201fd48b26c2e9a24d020d8bd127e3dbf34905a8/java/TikaImageDetection/src/main/java/org/mitre/mpf/detection/tika/TikaImageDetectionComponent.java#L131)):*
> ```Java
>         Map<String,String> properties = mpfGenericJob.getJobProperties();
>         boolean separatePages = false;
>         boolean emptyPages = false; // TODO: This is not read anywhere
> ```

@hhuangmitre : Please address this. Did you intend to use `emptyPages` for something?
___
*[java/TikaTextDetection/Dockerfile, line 39 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/266#-MfndQ8H-XF3rvNSX2N_:-MfndQ8H-XF3rvNSX2Na:bvyl445) ([raw file](https://github.com/openmpf/openmpf-components/blob/e83a99249dcf47a6230f4b2e34e82af2c6d3a0dd/java/TikaTextDetection/Dockerfile#L39)):*
> ```Dockerfile
> COPY . .
> 
> ARG RUN_TESTS=true
> ```

I changed this so that it's false by default, like in other components. The `Jenkinsfile` will set it to true here:

```
            sh 'docker build -f openmpf_build/Dockerfile .. --build-arg RUN_TESTS=true ' +
                    "$commonBuildArgs $labelArgs -t openmpf_build:$inProgressTag"
```

It's false by default so we don't run the tests when doing local builds.

**Review by hhuangMITRE — COMMENTED** [review]
Assuming we land the derivative branch changes first, I've fixed the UUID issues and cleaned up the unused job parameter. Let me know if any further updates are requested. Thanks!

> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/266#-:-MiO9yl0D5T6RHcWY7L4:bpxkmej)* status: 14 of 17 files reviewed, 4 unresolved discussions (waiting on @brosenberg42 and @jrobble)

___
*[java/TikaImageDetection/src/main/java/org/mitre/mpf/detection/tika/EmbeddedContentExtractor.java, line 57 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/266#-MfnVsHb88uqvW3VzyE4:-MiO9-Er9m7Xbp1DFLii:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/e83a99249dcf47a6230f4b2e34e82af2c6d3a0dd/java/TikaImageDetection/src/main/java/org/mitre/mpf/detection/tika/EmbeddedContentExtractor.java#L57)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

@hhuangmitre : Please leave a comment stating what `imagePageMap` contains. What is the key? What is the value a set of?
</blockquote></details>

Done.
___
*[java/TikaImageDetection/src/main/java/org/mitre/mpf/detection/tika/EmbeddedContentExtractor.java, line 119 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/266#-MhtCATB-weNxVBC3xH4:-MiO92Pu8DxRnndvjV58:b-v9e0n) ([raw file](https://github.com/openmpf/openmpf-components/blob/201fd48b26c2e9a24d020d8bd127e3dbf34905a8/java/TikaImageDetection/src/main/java/org/mitre/mpf/detection/tika/EmbeddedContentExtractor.java#L119)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

@hhuangmitre : Please address this.
</blockquote></details>

Done. This change is also included in the PDF image extraction PR, but I'm also placing the fix here if we land this first. 
___
*[java/TikaImageDetection/src/main/java/org/mitre/mpf/detection/tika/ImageExtractionContentHandler.java, line 49 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/266#-MhtHUgB4282SsVeOSS7:-MiO9KOb9pZPvMhPhxTk:bgyta0k) ([raw file](https://github.com/openmpf/openmpf-components/blob/201fd48b26c2e9a24d020d8bd127e3dbf34905a8/java/TikaImageDetection/src/main/java/org/mitre/mpf/detection/tika/ImageExtractionContentHandler.java#L49)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

@hhuangmitre : Please look into this. I will send you the file separately.
</blockquote></details>

Done. This issue was resolved in the image extraction PR. Let me know if you want me to move that change over here, thanks!
___
*[java/TikaImageDetection/src/main/java/org/mitre/mpf/detection/tika/TikaImageDetectionComponent.java, line 131 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/266#-MhtCJc32QMiufPUhlkM:-MiO9e1D7jqW3yZJV-mH:bx8rp7g) ([raw file](https://github.com/openmpf/openmpf-components/blob/201fd48b26c2e9a24d020d8bd127e3dbf34905a8/java/TikaImageDetection/src/main/java/org/mitre/mpf/detection/tika/TikaImageDetectionComponent.java#L131)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

@hhuangmitre : Please address this. Did you intend to use `emptyPages` for something?
</blockquote></details>

I believe this originally was meant for the page-per-track version of the component. During development, I wasn't fully sure if we needed this property anymore as we are reporting by image-per-track with these changes (and reporting empty pages would create confusion). I've decided to remove this job property as a result.

**Review by jrobble — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/266)* status: 16 of 17 files reviewed, 1 unresolved discussion (waiting on @brosenberg42, @hhuangMITRE, and @jrobble)

___
*[java/TikaImageDetection/README.md, line 3 at r3](https://reviewable.io/reviews/openmpf/openmpf-components/266#-Mj0WlG-DcIjZPTMMk9b:-Mj0WlG-DcIjZPTMMk9c:b7zpvte) ([raw file](https://github.com/openmpf/openmpf-components/blob/25909cea11a4164bedc401beaf63df819f197d69/java/TikaImageDetection/README.md#L3)):*
> ```Markdown
> # Overview
> 
> This directory contains source code for the OpenMPF Tika image detection component.
> ```

Please update this:
- Still mentions `ALLOW_EMPTY_PAGES `.
- Still mentions creating a track for each occurrence of the image. Instead, we're now listing all occurrences in the same track under `PAGE_NUM`, which can be a list. 
- Use tick marks around `ORGANIZE_BY_PAGE`.
- `IMAGES_FILES` is now `DERIVATIVE_MEDIA_PATH`.
- `PAGE` is now`PAGE_NUM`.

- In your other PR, mention that .odp files are supported, and list any other files types that are supported.
___
*[java/TikaImageDetection/src/main/java/org/mitre/mpf/detection/tika/EmbeddedContentExtractor.java, line 119 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/266#-MhtCATB-weNxVBC3xH4:-Mj0Jt3v1TB6R2OQdEW5:b-s44ei9) ([raw file](https://github.com/openmpf/openmpf-components/blob/201fd48b26c2e9a24d020d8bd127e3dbf34905a8/java/TikaImageDetection/src/main/java/org/mitre/mpf/detection/tika/EmbeddedContentExtractor.java#L119)):*
<details><summary><i>Previously, hhuangMITRE (Howard W Huang) wrote…</i></summary><blockquote>

Done. This change is also included in the PDF image extraction PR, but I'm also placing the fix here if we land this first. 
</blockquote></details>

Ok. The plan is to land this first.
___
*[java/TikaImageDetection/src/main/java/org/mitre/mpf/detection/tika/ImageExtractionContentHandler.java, line 49 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/266#-MhtHUgB4282SsVeOSS7:-Mj0YD2SChDMNkZ1N4p4:b3e4o5s) ([raw file](https://github.com/openmpf/openmpf-components/blob/201fd48b26c2e9a24d020d8bd127e3dbf34905a8/java/TikaImageDetection/src/main/java/org/mitre/mpf/detection/tika/ImageExtractionContentHandler.java#L49)):*
<details><summary><i>Previously, hhuangMITRE (Howard W Huang) wrote…</i></summary><blockquote>

Done. This issue was resolved in the image extraction PR. Let me know if you want me to move that change over here, thanks!
</blockquote></details>

I think it's fine to leave in the PR for now. I left a note to myself there.
___
*[java/TikaImageDetection/src/main/java/org/mitre/mpf/detection/tika/TikaImageDetectionComponent.java, line 131 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/266#-MhtCJc32QMiufPUhlkM:-Mj0K8id9YJWevenOwdM:b2we0sa) ([raw file](https://github.com/openmpf/openmpf-components/blob/201fd48b26c2e9a24d020d8bd127e3dbf34905a8/java/TikaImageDetection/src/main/java/org/mitre/mpf/detection/tika/TikaImageDetectionComponent.java#L131)):*
<details><summary><i>Previously, hhuangMITRE (Howard W Huang) wrote…</i></summary><blockquote>

I believe this originally was meant for the page-per-track version of the component. During development, I wasn't fully sure if we needed this property anymore as we are reporting by image-per-track with these changes (and reporting empty pages would create confusion). I've decided to remove this job property as a result.
</blockquote></details>

Ok. Yeah, I think it's best to remove it.

**Review by jrobble — COMMENTED** [review]
> Reviewed 1 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/266)* status: all files reviewed, 1 unresolved discussion (waiting on @brosenberg42 and @hhuangMITRE)

**Review by jrobble — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/266)* status: all files reviewed, 1 unresolved discussion (waiting on @brosenberg42 and @hhuangMITRE)

___
*[java/TikaImageDetection/README.md, line 3 at r3](https://reviewable.io/reviews/openmpf/openmpf-components/266#-Mj0WlG-DcIjZPTMMk9b:-Mj0YallCSqqQcMJ3rDA:b-tl6sqi) ([raw file](https://github.com/openmpf/openmpf-components/blob/25909cea11a4164bedc401beaf63df819f197d69/java/TikaImageDetection/README.md#L3)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Please update this:
- Still mentions `ALLOW_EMPTY_PAGES `.
- Still mentions creating a track for each occurrence of the image. Instead, we're now listing all occurrences in the same track under `PAGE_NUM`, which can be a list. 
- Use tick marks around `ORGANIZE_BY_PAGE`.
- `IMAGES_FILES` is now `DERIVATIVE_MEDIA_PATH`.
- `PAGE` is now`PAGE_NUM`.

- In your other PR, mention that .odp files are supported, and list any other files types that are supported.
</blockquote></details>

@hhuangmitre , forgot to tag you.

**Review by hhuangMITRE — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/266)* status: 16 of 17 files reviewed, 1 unresolved discussion (waiting on @brosenberg42 and @jrobble)

___
*[java/TikaImageDetection/README.md, line 3 at r3](https://reviewable.io/reviews/openmpf/openmpf-components/266#-Mj0WlG-DcIjZPTMMk9b:-MjARfm4EJK-Xtbq9feI:b-48k1ub) ([raw file](https://github.com/openmpf/openmpf-components/blob/25909cea11a4164bedc401beaf63df819f197d69/java/TikaImageDetection/README.md#L3)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

@hhuangmitre , forgot to tag you.
</blockquote></details>

Thanks Jeff! I've updated the `README` for both branches. I will merge this content into the image extraction PR after the derivative media update lands.

**Review by jrobble — COMMENTED** [review]
> Reviewed 6 of 8 files at r5, 7 of 7 files at r6, 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/266)* status: all files reviewed, 1 unresolved discussion (waiting on @brosenberg42 and @jrobble)

**Review by brosenberg42 — APPROVED** [review]
> Reviewed 6 of 8 files at r5.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/266)* status: all files reviewed, 1 unresolved discussion (waiting on @jrobble)

**Comment by jrobble** [comment]
*[`java/TikaImageDetection/src/main/java/org/mitre/mpf/detection/tika/PageNumberExtractionContentHandler.java` line 50 at r7](https://reviewable.io/reviews/openmpf/openmpf-components/266#-N5u1naRCN_WgZ7e1wCC:-N6F5uWJAh41-iW7Yj2w:b-pcie7g) ([raw file](https://github.com/openmpf/openmpf-components/blob/2710dd049a70807ce0c575f3c55641a0b008150b/java/TikaImageDetection/src/main/java/org/mitre/mpf/detection/tika/PageNumberExtractionContentHandler.java#L50)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

Does this need to be addressed?
</blockquote></details>

I test this and it's fixed in my recent updates.

**Review by jrobble — COMMENTED** [review]
> Reviewed 11 of 11 files at r8.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/266)* status: all files reviewed, 1 unresolved discussion (waiting on @brosenberg42)

**Review by brosenberg42 — APPROVED** [review]
> Reviewed 2 of 7 files at r6, 10 of 11 files at r8, 1 of 1 files at r9.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/266)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @hhuangMITRE)

**Review by brosenberg42 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r10.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/266)* status: 25 of 26 files reviewed, 4 unresolved discussions (waiting on @hhuangMITRE and @jrobble)

___
*[`java/TikaTextDetection/src/main/java/org/mitre/mpf/detection/tika/TextExtractionContentHandler.java` line 50 at r10](https://reviewable.io/reviews/openmpf/openmpf-components/266#-N6Okyc5ASeIJqhjcqG9:-N6Okyc5ASeIJqhjcqGA:blerzwl) ([raw file](https://github.com/openmpf/openmpf-components/blob/217a97ddf5b92cb15274ac20f7c72372528a2232/java/TikaTextDetection/src/main/java/org/mitre/mpf/detection/tika/TextExtractionContentHandler.java#L50)):*
> ```Java
>     private StringBuilder _sectionText;
> 
>     private final Map<Integer, List<StringBuilder>> _pageToSections = new LinkedHashMap<>();
> ```

This should be `HashMap`
___
*[`java/TikaTextDetection/src/main/java/org/mitre/mpf/detection/tika/TextExtractionContentHandler.java` line 99 at r10](https://reviewable.io/reviews/openmpf/openmpf-components/266#-N6OjPn-A8picAplAWn0:-N6OjPn-A8picAplAWn1:bfnmkv) ([raw file](https://github.com/openmpf/openmpf-components/blob/217a97ddf5b92cb15274ac20f7c72372528a2232/java/TikaTextDetection/src/main/java/org/mitre/mpf/detection/tika/TextExtractionContentHandler.java#L99)):*
> ```Java
>     private void createPage() {
>         _sectionText = new StringBuilder();
>         _pageToSections.put(_pageNumber, new LinkedList<>());
> ```

This should be an ArrayList. It is accessed by index in TikaTextDetectionComponent.getDetections resulting in O(n^2) behavior. Also, in general, there are very few cases where LinkedList should be used. LinkedList is slower and takes up 3x the space (it's doubly linked) of an ArrayList.
___
*[`java/TikaTextDetection/src/main/java/org/mitre/mpf/detection/tika/TextExtractionContentHandler.java` line 106 at r10](https://reviewable.io/reviews/openmpf/openmpf-components/266#-N6OuvAeBroN4HwtcDhC:-N6OuvAeBroN4HwtcDhD:bbt9fat) ([raw file](https://github.com/openmpf/openmpf-components/blob/217a97ddf5b92cb15274ac20f7c72372528a2232/java/TikaTextDetection/src/main/java/org/mitre/mpf/detection/tika/TextExtractionContentHandler.java#L106)):*
> ```Java
>         _pageNumber = 0;
>         _pageToSections.clear();
>         createPage();
> ```

Should `_allText` be cleared too?
___
*[`java/TikaTextDetection/src/main/java/org/mitre/mpf/detection/tika/TextExtractionContentHandler.java` line 111 at r10](https://reviewable.io/reviews/openmpf/openmpf-components/266#-N6OnZ5yCdcg0gf_i0jP:-N6OnZ5yCdcg0gf_i0jQ:bygyzpt) ([raw file](https://github.com/openmpf/openmpf-components/blob/217a97ddf5b92cb15274ac20f7c72372528a2232/java/TikaTextDetection/src/main/java/org/mitre/mpf/detection/tika/TextExtractionContentHandler.java#L111)):*
> ```Java
>     private void newSection() {
>         // Skip blank sections.
>         if (_sectionText.toString().isBlank()) {
> ```

In the case where this is true because the section is just white space, won't the white space be carried over in to the next section?

**Review by jrobble — COMMENTED** [review]
> Reviewed 1 of 1 files at r9, 2 of 3 files at r10, 11 of 11 files at r11.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/266)* status: all files reviewed, 4 unresolved discussions (waiting on @brosenberg42)

___
*[`java/TikaTextDetection/src/main/java/org/mitre/mpf/detection/tika/TextExtractionContentHandler.java` line 50 at r10](https://reviewable.io/reviews/openmpf/openmpf-components/266#-N6Okyc5ASeIJqhjcqG9:-N6PgBIgB1DWnTv09B6U:b8mrp93) ([raw file](https://github.com/openmpf/openmpf-components/blob/217a97ddf5b92cb15274ac20f7c72372528a2232/java/TikaTextDetection/src/main/java/org/mitre/mpf/detection/tika/TextExtractionContentHandler.java#L50)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

This should be `HashMap`
</blockquote></details>

Done. Thanks for the sanity check. I ended up changing this to `HashMap` because of how we access by key.
___
*[`java/TikaTextDetection/src/main/java/org/mitre/mpf/detection/tika/TextExtractionContentHandler.java` line 99 at r10](https://reviewable.io/reviews/openmpf/openmpf-components/266#-N6OjPn-A8picAplAWn0:-N6PgjnJ532CZP8JXOzI:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/217a97ddf5b92cb15274ac20f7c72372528a2232/java/TikaTextDetection/src/main/java/org/mitre/mpf/detection/tika/TextExtractionContentHandler.java#L99)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

This should be an ArrayList. It is accessed by index in TikaTextDetectionComponent.getDetections resulting in O(n^2) behavior. Also, in general, there are very few cases where LinkedList should be used. LinkedList is slower and takes up 3x the space (it's doubly linked) of an ArrayList.
</blockquote></details>

Done.
___
*[`java/TikaTextDetection/src/main/java/org/mitre/mpf/detection/tika/TextExtractionContentHandler.java` line 106 at r10](https://reviewable.io/reviews/openmpf/openmpf-components/266#-N6OuvAeBroN4HwtcDhC:-N6UJosd8GLf41NFqE6n:b-k614gh) ([raw file](https://github.com/openmpf/openmpf-components/blob/217a97ddf5b92cb15274ac20f7c72372528a2232/java/TikaTextDetection/src/main/java/org/mitre/mpf/detection/tika/TextExtractionContentHandler.java#L106)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

Should `_allText` be cleared too?
</blockquote></details>

Yes, thanks.
___
*[`java/TikaTextDetection/src/main/java/org/mitre/mpf/detection/tika/TextExtractionContentHandler.java` line 111 at r10](https://reviewable.io/reviews/openmpf/openmpf-components/266#-N6OnZ5yCdcg0gf_i0jP:-N6UJux2DkBjPvlCBATI:b-r0jg2b) ([raw file](https://github.com/openmpf/openmpf-components/blob/217a97ddf5b92cb15274ac20f7c72372528a2232/java/TikaTextDetection/src/main/java/org/mitre/mpf/detection/tika/TextExtractionContentHandler.java#L111)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

In the case where this is true because the section is just white space, won't the white space be carried over in to the next section?
</blockquote></details>

Yes, but it gets trimmed out later.

**Review by jrobble — COMMENTED** [review]
> Reviewed 6 of 6 files at r12.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/266)* status: all files reviewed, 4 unresolved discussions (waiting on @brosenberg42)

**Review by jrobble — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/266)* status: all files reviewed, 5 unresolved discussions (waiting on @brosenberg42 and @hhuangMITRE)

*[a discussion](https://reviewable.io/reviews/openmpf/openmpf-components/266#-N6W1w0EALKwyijtjtzv:-N6W1w0EALKwyijtjtzw:b-jahs4z) (no related file):*
@hhuangmitre :

1. Please verify that the changes in https://github.com/openmpf/openmpf-components/pull/274 have been applied here properly. We can then close that PR.

2. Please sanity-check the changes Brian and I made to determine if we changed / omitted anything important that should be corrected.

3. Please remove the code where we add leading "0"s to `PAGE_NUM` and `SECTION_NUM`. I noticed that was done in TikaTextDetection but not TikaImageDetection. In retrospect, that may mess up the job consumers. Sorry to flip-flop on this. A better solution to enforcing track order in the JSON is to allow the components to provide a track index, but that's out of scope for this task.

4. Please apply your local changes not reflected in this PR yet.

___

**Review by hhuangMITRE — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/266)* status: 32 of 34 files reviewed, 5 unresolved discussions (waiting on @brosenberg42 and @jrobble)

*[a discussion](https://reviewable.io/reviews/openmpf/openmpf-components/266#-N6W1w0EALKwyijtjtzv:-N6khW5A7pcn62uVp-_R:bfchfbw) (no related file):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

@hhuangmitre :

1. Please verify that the changes in https://github.com/openmpf/openmpf-components/pull/274 have been applied here properly. We can then close that PR.

2. Please sanity-check the changes Brian and I made to determine if we changed / omitted anything important that should be corrected.

3. Please remove the code where we add leading "0"s to `PAGE_NUM` and `SECTION_NUM`. I noticed that was done in TikaTextDetection but not TikaImageDetection. In retrospect, that may mess up the job consumers. Sorry to flip-flop on this. A better solution to enforcing track order in the JSON is to allow the components to provide a track index, but that's out of scope for this task.

4. Please apply your local changes not reflected in this PR yet.
</blockquote></details>

@jrobble 
Hi Jeff,

I've reviewed the code and gone through the action items:
1. Verified that the changes in #274 have been applied properly. Key change for processing `.odp` files was transferred. I've closed the PR now. 
2. Did a sanity check and local test of the changes in #266. Looks good.
3. Removed code for adding leading zeros to `PAGE_NUM` and `SECTION_NUM`. This was a light change so I've included it as a follow-up commit for this branch.
4. I've done a sweep through my old VM environment and looked for any other changes that were missed. I found the PR update for Tika 2.0.0 that was intended to land in Milestone #2. I've reviewed and transferred those changes into a follow-up PR, now updated to Tika 2.4.1. The changes are stored in PR #298, addressing issue #1384 (update Tika to 2.4.1) and set to merge into the current branch (or right after it lands).

The Tika 2.4.1 branch updates the PDF parser code + the JPEG output file extension in test cases (mainly to swap `.jpg` ->`.jpeg` extensions).

Please note that Optimaize Language Detection is still at version 1.28.1 after the Tika 2.4.1 update. Notes + docs for Apache Tika v2 do not list the library anymore, but I will keep looking. 

___

**Review by jrobble — APPROVED** [review]
> Reviewed 23 of 23 files at r15.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/266)* status: all files reviewed, 4 unresolved discussions (waiting on @brosenberg42)

**Pull request merged**
