### PR TITLE
Azure Speech Component

### PR DESCRIPTION
**Pull request by cdglasz**
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/160)

### CODE REVIEW

**Comment by jrobble** [comment]
___
*[python/AzureSpeechDetection/Dockerfile, line 32 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/160#-MA3rYn39Wn-VadDI-f7:-MA3rYn39Wn-VadDI-f8:b-nu1aig) ([raw file](https://github.com/openmpf/openmpf-components/blob/91b620393575db9c4a23cb543c0a8f630de5eabb/python/AzureSpeechDetection/Dockerfile#L32)):*
> ```Dockerfile
> 
> # Manually install packages before COPY so they don't need to be re-installed every time the source code changes.
> RUN pip install --no-cache-dir 'azure-storage-blob>=12.3'
> ```

The latest Docker build failed with:

```
Building azure_speech_detection
Step 1/13 : ARG BUILD_REGISTRY
Step 2/13 : ARG BUILD_TAG=latest
Step 3/13 : FROM ${BUILD_REGISTRY}openmpf_python_executor:${BUILD_TAG}
# Executing 1 build trigger
 ---> Using cache
 ---> f84c71620ad4
Step 4/13 : RUN pip install --no-cache-dir 'azure-storage-blob>=12.3'
 ---> Running in 958827a412cd
/bin/sh: pip: command not found
Service 'azure_speech_detection' failed to build: The command '/bin/sh -c pip install --no-cache-dir 'azure-storage-blob>=12.3'' returned a non-zero code: 127
```

Please take a look at how `pip` is used [here](https://github.com/openmpf/openmpf-components/blob/master/python/EastTextDetection/Dockerfile#L32) in the EAST master branch and update this PR accordingly.

I think the problem is that the `pip` line is different in develop, as seen [here](https://github.com/openmpf/openmpf-components/blob/develop/python/EastTextDetection/Dockerfile#L32), and you started by targeting develop.

**Comment by jrobble** [comment]
___
*[python/AzureSpeechDetection/tests/test_acs_speech.py, line 39 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/160#-MAS0-ryC0fqihWQsECp:-MAS0-ryC0fqihWQsECq:byv4qgf) ([raw file](https://github.com/openmpf/openmpf-components/blob/3ffa454bbb4d492cb8916be382c5307d99ef7d26/python/AzureSpeechDetection/tests/test_acs_speech.py#L39)):*
The most recent Docker build fails with:

```
Step 9/13 : RUN if [ "${RUN_TESTS,,}" == true ]; then         LD_LIBRARY_PATH="$MPF_HOME/lib" "$COMPONENT_VIRTUALENV/bin/python" /home/mpf/component_src/tests/test_acs_speech.py;     fi
 ---> Running in fd6a9a2bae9f
Traceback (most recent call last):
  File "/home/mpf/component_src/tests/test_acs_speech.py", line 39, in <module>
    from mock import patch, Mock
ImportError: No module named mock
```

According to [this](https://pypi.org/project/mock/):

> mock is now part of the Python standard library, available as unittest.mock in Python 3.3 onwards.

Since OpenMPF 4.1 uses Python 2.7, I believe you need to install `mock`.

**Comment by brosenberg42** [comment]
___
*[python/AzureSpeechDetection/plugin-files/descriptor/descriptor.json, line 3 at r3](https://reviewable.io/reviews/openmpf/openmpf-components/160#-MATdMO20DR3fh7PE_UG:-MAVkMfoDlpvLBnft7_M:b-3lijgz) ([raw file](https://github.com/openmpf/openmpf-components/blob/7bec2a5d535214c306e5e3121592e150098ab6c8/python/AzureSpeechDetection/plugin-files/descriptor/descriptor.json#L3)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Please change the `componentVersion` and `middlewareVersion` to `5.0`. Note that we're dropping the last digit, so don't use `5.0.0`.
</blockquote></details>

Don't make this change. This PR is for 4.1

**Comment by jrobble** [comment]
___
*[python/AzureSpeechDetection/plugin-files/descriptor/descriptor.json, line 3 at r3](https://reviewable.io/reviews/openmpf/openmpf-components/160#-MATdMO20DR3fh7PE_UG:-MAWTE_g4j3nOIGBhNDK:bm7rf5) ([raw file](https://github.com/openmpf/openmpf-components/blob/7bec2a5d535214c306e5e3121592e150098ab6c8/python/AzureSpeechDetection/plugin-files/descriptor/descriptor.json#L3)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

Don't make this change. This PR is for 4.1
</blockquote></details>

Brian is right. Wait until your next PR to make this change.

**Pull request merged**
