### PR TITLE
OpenCV4 upgrade with CUDA 

### PR DESCRIPTION
**Pull request by brosenberg42**
Associated PRs:
- https://github.com/openmpf/openmpf/pull/1136
- https://github.com/openmpf/openmpf-docker/pull/108
- https://github.com/openmpf/openmpf-cpp-component-sdk/pull/89
- https://github.com/openmpf/openmpf-python-component-sdk/pull/37
- https://github.com/openmpf/openmpf-components/pull/174
- https://github.com/openmpf/openmpf-contrib-components/pull/63

Issues:
- https://github.com/openmpf/openmpf/issues/1101
- https://github.com/openmpf/openmpf/issues/1073

---
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/174)

### CODE REVIEW

**Review by jrobble — CHANGES_REQUESTED** [review]
> Reviewed 28 of 28 files at r1.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/174)* status: all files reviewed, 5 unresolved discussions (waiting on @brosenberg42)

___
*[cpp/DarknetDetection/Dockerfile, line 73 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/174#-MOJ0M-G51glR9h3Uyhz:-MOJ0M-H4Jexl0SMzIre:b-93pc20) ([raw file](https://github.com/openmpf/openmpf-components/blob/20a7e12e1b7f4af1a8c14029e0d7141e40bf152b/cpp/DarknetDetection/Dockerfile#L73)):*
> ```Dockerfile
> 
> ####################################################
> FROM darknet_component as sample_executable
> ```

What's the motivation for adding this? Just to make manual testing easier before we land the CLI Runner update?
___
*[cpp/DarknetDetection/sample_darknet_detector.cpp, line 42 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/174#-MOJ0lnPE3sdpGZ_jQEs:-MOJ0lnPE3sdpGZ_jQEt:bulhenb) ([raw file](https://github.com/openmpf/openmpf-components/blob/20a7e12e1b7f4af1a8c14029e0d7141e40bf152b/cpp/DarknetDetection/sample_darknet_detector.cpp#L42)):*
> ```cpp
> 
> int main(int argc, char* argv[]) {
>     if (argc == 2) {
> ```

Should we document this usage in the usage print out?
___
*[cpp/DlibFaceDetection/CMakeLists.txt, line 34 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/174#-MOJ12oU3lXtUdu5PzjD:-MOJ12oU3lXtUdu5PzjE:b-49xxe) ([raw file](https://github.com/openmpf/openmpf-components/blob/20a7e12e1b7f4af1a8c14029e0d7141e40bf152b/cpp/DlibFaceDetection/CMakeLists.txt#L34)):*
> ```CMake
> 
> set(USE_AVX_INSTRUCTIONS ON)
> set(DLIB_USE_CUDA OFF)
> ```

I'm assuming it didn't use CUDA before. Was version 19.20 trying to build with CUDA by default?
___
*[cpp/OcvDnnDetection/sample_ocv_dnn_classifier.cpp, line 40 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/174#-MOJ2LJU5DchgZkGkj1x:-MOJ2LJU5DchgZkGkj1y:bulhenb) ([raw file](https://github.com/openmpf/openmpf-components/blob/20a7e12e1b7f4af1a8c14029e0d7141e40bf152b/cpp/OcvDnnDetection/sample_ocv_dnn_classifier.cpp#L40)):*
> ```cpp
>     if (argc == 2) {
>         std::string arg1 = argv[1];
>         if (arg1 == "gpu-info") {
> ```

Should we document this usage in the usage print out?
___
*[cpp/TesseractOCRTextDetection/Dockerfile, line 35 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/174#-MOJt-4kC_7_Vc2NGn1n:-MOJt-4kC_7_Vc2NGn1o:b-9ktq5) ([raw file](https://github.com/openmpf/openmpf-components/blob/88cfd00aa084bd2a711a24bac4388080b68cbc52/cpp/TesseractOCRTextDetection/Dockerfile#L35)):*
> ```Dockerfile
>     && yum --enablerepo=remi install -y ImageMagick ImageMagick-c++ \
>          ImageMagick-c++-devel ImageMagick-devel ImageMagick-libs \
>          libgif libjpeg libpng libtiff zlib ghostscript \
> ```

What motivated you to remove this?

**Review by jrobble — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/174)* status: all files reviewed, 5 unresolved discussions (waiting on @brosenberg42)

**Review by brosenberg42 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/174)* status: 26 of 34 files reviewed, 5 unresolved discussions (waiting on @brosenberg42 and @jrobble)

___
*[cpp/DarknetDetection/Dockerfile, line 73 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/174#-MOJ0M-G51glR9h3Uyhz:-MOWn3hQ6jtzwc9OSLjl:b-o0atdy) ([raw file](https://github.com/openmpf/openmpf-components/blob/20a7e12e1b7f4af1a8c14029e0d7141e40bf152b/cpp/DarknetDetection/Dockerfile#L73)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

What's the motivation for adding this? Just to make manual testing easier before we land the CLI Runner update?
</blockquote></details>

It was added before CLI runner task was even given to us. I added so I could test on the GPU server.
___
*[cpp/DarknetDetection/sample_darknet_detector.cpp, line 42 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/174#-MOJ0lnPE3sdpGZ_jQEs:-MOYESOl0QPDROK3K1xr:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/20a7e12e1b7f4af1a8c14029e0d7141e40bf152b/cpp/DarknetDetection/sample_darknet_detector.cpp#L42)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Should we document this usage in the usage print out?
</blockquote></details>

Done.
___
*[cpp/DlibFaceDetection/CMakeLists.txt, line 34 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/174#-MOJ12oU3lXtUdu5PzjD:-MOY4e1R5MiDVsxt9HX4:b-cm30gb) ([raw file](https://github.com/openmpf/openmpf-components/blob/20a7e12e1b7f4af1a8c14029e0d7141e40bf152b/cpp/DlibFaceDetection/CMakeLists.txt#L34)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

I'm assuming it didn't use CUDA before. Was version 19.20 trying to build with CUDA by default?
</blockquote></details>

I get a build error without that line. I didn't think it was worth my time to figure how to get it running on gpu since no one uses it.
___
*[cpp/OcvDnnDetection/sample_ocv_dnn_classifier.cpp, line 40 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/174#-MOJ2LJU5DchgZkGkj1x:-MOYEQQjBwEpAYJWmOYo:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/20a7e12e1b7f4af1a8c14029e0d7141e40bf152b/cpp/OcvDnnDetection/sample_ocv_dnn_classifier.cpp#L40)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Should we document this usage in the usage print out?
</blockquote></details>

Done.
___
*[cpp/TesseractOCRTextDetection/Dockerfile, line 35 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/174#-MOJt-4kC_7_Vc2NGn1n:-MOWor7w1QiIb5Oy2eSb:bb6xfjm) ([raw file](https://github.com/openmpf/openmpf-components/blob/88cfd00aa084bd2a711a24bac4388080b68cbc52/cpp/TesseractOCRTextDetection/Dockerfile#L35)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

What motivated you to remove this?
</blockquote></details>

It was never used. The build started failing because of `yum-config-manager --setopt=skip_missing_names_on_install=False --save;`

**Review by jrobble — APPROVED** [review]
> Reviewed 8 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/174)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[cpp/DlibFaceDetection/CMakeLists.txt, line 34 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/174#-MOJ12oU3lXtUdu5PzjD:-MObTlVM53tF5A3ylvnB:b-pbdqz3) ([raw file](https://github.com/openmpf/openmpf-components/blob/20a7e12e1b7f4af1a8c14029e0d7141e40bf152b/cpp/DlibFaceDetection/CMakeLists.txt#L34)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

I get a build error without that line. I didn't think it was worth my time to figure how to get it running on gpu since no one uses it.
</blockquote></details>

Agreed.

**Pull request merged**
