### PR TITLE
Add health check to ocv face

### PR DESCRIPTION
**Pull request by brosenberg42**
**Issues:**

- https://github.com/openmpf/openmpf/issues/1731

**Related PRs:**

- https://github.com/openmpf/openmpf/pull/1742
- https://github.com/openmpf/openmpf-docker/pull/202
- https://github.com/openmpf/openmpf-components/pull/347

- - -
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/347)

### CODE REVIEW

**Review by jrobble — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/347)* status: all files reviewed, 1 unresolved discussion (waiting on @brosenberg42)

___
*[`cpp/OcvFaceDetection/plugin-files/meds_faces_image.png` line 0 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/347#-NnigvvXCA2Zfo55kTOB:-NnigvvXCA2Zfo55kTOC:b-gjw4e9) ([raw file](https://github.com/openmpf/openmpf-components/blob/10b31885445b2e0f0054670a13368a4a8738105a/cpp/OcvFaceDetection/plugin-files/meds_faces_image.png#L0)):*
Let's add a `NOTICE` like we have in`/test/data/test_imgs/NOTICE`.

Also, consider creating a separate dir called `/plugin-files/data/health` with the image, `NOTICE`, and .ini file in it.

**Review by jrobble — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/347)* status: all files reviewed, 1 unresolved discussion (waiting on @brosenberg42)

___
*[`cpp/OcvFaceDetection/plugin-files/meds_faces_image.png` line  at r1](https://reviewable.io/reviews/openmpf/openmpf-components/347#-NnigvvXCA2Zfo55kTOB:-NnpcufS9S1NXkej36g2:b-g1134k) ([raw file](https://github.com/openmpf/openmpf-components/blob/10b31885445b2e0f0054670a13368a4a8738105a/cpp/OcvFaceDetection/plugin-files/meds_faces_image.png#L)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Let's add a `NOTICE` like we have in`/test/data/test_imgs/NOTICE`.

Also, consider creating a separate dir called `/plugin-files/data/health` with the image, `NOTICE`, and .ini file in it.
</blockquote></details>

I thought about this some more.

Instead of `/plugin-files/data/health`, maybe we should standardize on `/plugin-files/health`.

**Review by brosenberg42 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/347)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @brosenberg42 and @jrobble)

___
*[`cpp/OcvFaceDetection/plugin-files/meds_faces_image.png` line  at r1](https://reviewable.io/reviews/openmpf/openmpf-components/347#-NnigvvXCA2Zfo55kTOB:-NnscqSuEeTvaV1fNr4s:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/10b31885445b2e0f0054670a13368a4a8738105a/cpp/OcvFaceDetection/plugin-files/meds_faces_image.png#L)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

I thought about this some more.

Instead of `/plugin-files/data/health`, maybe we should standardize on `/plugin-files/health`.
</blockquote></details>

Done.

**Review by jrobble — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/347)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @brosenberg42)

**Pull request merged**
