### PR TITLE
Change inclusive overlap threshold to exclusive

### PR DESCRIPTION
**Pull request by cdglasz**
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/202)

### CODE REVIEW

**Review by jrobble — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/202)* status: all files reviewed, 2 unresolved discussions (waiting on @cdglasz)

___
*[python/EastTextDetection/east_component/east_component.py, line 58 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/202#-MLiURjT2m_ixy9jdsD2:-MLiURjT2m_ixy9jdsD3:blot6wx) ([raw file](https://github.com/openmpf/openmpf-components/blob/29dc208e0613b1477e61242a431b698d70c259cd/python/EastTextDetection/east_component/east_component.py#L58)):*
> ```Python
>         # Get the threshold values for filtering bounding boxes
>         min_confidence = float(props.get('CONFIDENCE_THRESHOLD','0.8'))
>         overlap_threshold = float(props.get('MERGE_OVERLAP_THRESHOLD','0.01'))
> ```

The default in the descriptor for this is 0.0.
___
*[python/EastTextDetection/tests/sample_east_text_detector.py, line 67 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/202#-MLiU7iA2Lqq6exJpmEW:-MLiU7iB906waq1i2SyD:blot6wx) ([raw file](https://github.com/openmpf/openmpf-components/blob/29dc208e0613b1477e61242a431b698d70c259cd/python/EastTextDetection/tests/sample_east_text_detector.py#L67)):*
> ```Python
>     parser.add_argument('--max-side-length', type=int, default=-1)
>     parser.add_argument('--confidence-threshold', type=float, default=0.8)
>     parser.add_argument('--merge-overlap-threshold', type=float, default=0.01)
> ```

The default in the descriptor for this is 0.0.

**Review by cdglasz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/202)* status: 5 of 7 files reviewed, 2 unresolved discussions (waiting on @jrobble)

___
*[python/EastTextDetection/east_component/east_component.py, line 58 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/202#-MLiURjT2m_ixy9jdsD2:-MLiiiyaCvNukW4mkAZ9:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/29dc208e0613b1477e61242a431b698d70c259cd/python/EastTextDetection/east_component/east_component.py#L58)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

The default in the descriptor for this is 0.0.
</blockquote></details>

Done.
___
*[python/EastTextDetection/tests/sample_east_text_detector.py, line 67 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/202#-MLiU7iA2Lqq6exJpmEW:-MLiijMa4aNu5WeJ6KdX:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/29dc208e0613b1477e61242a431b698d70c259cd/python/EastTextDetection/tests/sample_east_text_detector.py#L67)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

The default in the descriptor for this is 0.0.
</blockquote></details>

Done.

**Review by jrobble — APPROVED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/202)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by jrobble — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/202)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
