### PR TITLE
Add rollup functionality to CLIP Detection component

### PR DESCRIPTION
**Pull request by ZachCafego**
**Issues:**

- https://github.com/openmpf/openmpf/issues/1696

- - -
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/335)

### CODE REVIEW

**Review by jrobble — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/335)* status: all files reviewed, 3 unresolved discussions (waiting on @ZachCafego)

___
*[`python/ClipDetection/clip_component/clip_component.py` line 31 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/335#-NZiF1x91L2GK6hC15v1:-NZiF1xA9RZLiOXv8LWg:b-31e1qw) ([raw file](https://github.com/openmpf/openmpf-components/blob/7ec3d1d3cabfc13fc0d562634a30cc0278069597/python/ClipDetection/clip_component/clip_component.py#L31)):*
> ```Python
> import csv
> from pkg_resources import resource_filename
> from typing import Iterable, Mapping, TypedDict
> ```

VScode says Iterable and TypedDict are not used.
___
*[`python/ClipDetection/clip_component/clip_component.py` line 90 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/335#-NZiIEI2-ARejiNhYuM3:-NZiIEI2-ARejiNhYuM4:b-h6noyd) ([raw file](https://github.com/openmpf/openmpf-components/blob/7ec3d1d3cabfc13fc0d562634a30cc0278069597/python/ClipDetection/clip_component/clip_component.py#L90)):*
> ```Python
>         self._triton_server_url = None
>     
>     def get_classifications(self, images, job_properties: Mapping[str, str]) -> mpf.ImageLocation:
> ```

This should be `-> Iterable[mpf.ImageLocation]:`
___
*[`python/ClipDetection/clip_component/clip_component.py` line 95 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/335#-NZiGiKE-OjeKSvio6Me:-NZiGiKE-OjeKSvio6Mf:b-mlznpe) ([raw file](https://github.com/openmpf/openmpf-components/blob/7ec3d1d3cabfc13fc0d562634a30cc0278069597/python/ClipDetection/clip_component/clip_component.py#L95)):*
> ```Python
>         self._check_class_list(kwargs['classification_path'], kwargs['classification_list'])
> 
>         self._preprocessor = ImagePreprocessor(kwargs['enable_cropping'])
> ```

Do the following in `__init__`:

```
self._preprocessor = None
```

**Review by jrobble — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/335)* status: all files reviewed, 4 unresolved discussions (waiting on @ZachCafego)

___
*[`python/ClipDetection/clip_component/clip_component.py` line 69 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/335#-NZiGBAt54OOqLikDFWa:-NZiGBAt54OOqLikDFWb:bqpibfk) ([raw file](https://github.com/openmpf/openmpf-components/blob/7ec3d1d3cabfc13fc0d562634a30cc0278069597/python/ClipDetection/clip_component/clip_component.py#L69)):*
> ```Python
>         
>         except Exception as e:
>             logger.exception(f"Failed to complete job {image_job.job_name} due to the following exception:")
> ```

Components developed more recently do:

```python
        except Exception as e:
            logger.exception(f'Job failed due to: {e}')
            raise
```

**Review by ZachCafego — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/335)* status: 2 of 3 files reviewed, 4 unresolved discussions (waiting on @jrobble)

___
*[`python/ClipDetection/clip_component/clip_component.py` line 31 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/335#-NZiF1x91L2GK6hC15v1:-NZlD8wt8Wjg5GBbUmvI:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/7ec3d1d3cabfc13fc0d562634a30cc0278069597/python/ClipDetection/clip_component/clip_component.py#L31)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

VScode says Iterable and TypedDict are not used.
</blockquote></details>

Done.
___
*[`python/ClipDetection/clip_component/clip_component.py` line 69 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/335#-NZiGBAt54OOqLikDFWa:-NZlDCTmBumgYtxkFHWL:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/7ec3d1d3cabfc13fc0d562634a30cc0278069597/python/ClipDetection/clip_component/clip_component.py#L69)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Components developed more recently do:

```python
        except Exception as e:
            logger.exception(f'Job failed due to: {e}')
            raise
```
</blockquote></details>

Done.
___
*[`python/ClipDetection/clip_component/clip_component.py` line 90 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/335#-NZiIEI2-ARejiNhYuM3:-NZlDEXaBWL_bAfbpayT:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/7ec3d1d3cabfc13fc0d562634a30cc0278069597/python/ClipDetection/clip_component/clip_component.py#L90)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

This should be `-> Iterable[mpf.ImageLocation]:`
</blockquote></details>

Done.
___
*[`python/ClipDetection/clip_component/clip_component.py` line 95 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/335#-NZiGiKE-OjeKSvio6Me:-NZlDFlRCYxq3A5y-U4b:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/7ec3d1d3cabfc13fc0d562634a30cc0278069597/python/ClipDetection/clip_component/clip_component.py#L95)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Do the following in `__init__`:

```
self._preprocessor = None
```
</blockquote></details>

Done.

**Review by jrobble — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/335)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ZachCafego)

**Pull request merged**
