### PR TITLE
Updating TikaTextDetection component to separate documents and PowerPoint files by paragraphs.

### PR DESCRIPTION
**Pull request by hhuangMITRE**
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/245)

### CODE REVIEW

**Review by jrobble — CHANGES_REQUESTED** [review]
Please change this to merge into master.

---

Please mention in the README that, unlike *.pptx files,  *.odp files can't be parsed by page. As a user, I thought a *.odp file would be treated like a PowerPoint file.

> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/245#-:-MYlIRQz9J5wgd3pRLHV:bvr71zg)* status: all files reviewed, 8 unresolved discussions (waiting on @hhuangMITRE)

___
*[java/TikaTextDetection/src/main/java/org/mitre/mpf/detection/tika/TextExtractionContentHandler.java, line 36 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/245#-MYkkV4i7-dSrX_Lj2Pw:-MYkkV4i7-dSrX_Lj2Px:bhil8el) ([raw file](https://github.com/openmpf/openmpf-components/blob/80286fdae62e4359f75fbc94b621e93dc02739b3/java/TikaTextDetection/src/main/java/org/mitre/mpf/detection/tika/TextExtractionContentHandler.java#L36)):*
> ```Java
> 
> public class TextExtractionContentHandler extends ToTextContentHandler {
>     private String pageTag = "div";
> ```

"div" and "p" can be `private static`. 
___
*[java/TikaTextDetection/src/main/java/org/mitre/mpf/detection/tika/TextExtractionContentHandler.java, line 115 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/245#-MYknbU627GywhW1SlsK:-MYknbU627GywhW1SlsL:b2o2cjr) ([raw file](https://github.com/openmpf/openmpf-components/blob/80286fdae62e4359f75fbc94b621e93dc02739b3/java/TikaTextDetection/src/main/java/org/mitre/mpf/detection/tika/TextExtractionContentHandler.java#L115)):*
> ```Java
>         sectionMap.clear();
>         pageMap.add(sectionMap);
>         sectionMap.add(new StringBuilder());
> ```

For sanity, let's keep the order of these operations as close to those in `startPage()` as possible.
___
*[java/TikaTextDetection/src/main/java/org/mitre/mpf/detection/tika/TextExtractionContentHandler.java, line 119 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/245#-MYkmQ4lCOyarwXhLA0T:-MYkmQ4lCOyarwXhLA0U:bdx05ec) ([raw file](https://github.com/openmpf/openmpf-components/blob/80286fdae62e4359f75fbc94b621e93dc02739b3/java/TikaTextDetection/src/main/java/org/mitre/mpf/detection/tika/TextExtractionContentHandler.java#L119)):*
> ```Java
> 
>     protected void newSection() throws SAXException {
>         if (skipBlankParagraphs && sectionMap.get(sectionNumber).toString().trim().length() == 0){
> ```

Instead of `.length() == 0`, please use `.isEmpty()`. I counted three instances of this in your code. Please change them all.
___
*[java/TikaTextDetection/src/main/java/org/mitre/mpf/detection/tika/TikaTextDetectionComponent.java, line 165 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/245#-MYkpfb4B4j9eX1-zMeB:-MYkcLE714TSsNFx7z7r:b3tmpde) ([raw file](https://github.com/openmpf/openmpf-components/blob/80286fdae62e4359f75fbc94b621e93dc02739b3/java/TikaTextDetection/src/main/java/org/mitre/mpf/detection/tika/TikaTextDetectionComponent.java#L165)):*
> ```Java
>                         // By default, trim out detected text.
>                         textDetect = textDetect.trim();
>                         genericDetectionProperties.put("TEXT", textDetect);
> ```

Should this line be moved below the `if (textDetect.length() == 0) {` check? You only generate the track if the section is not empty.
___
*[java/TikaTextDetection/src/main/java/org/mitre/mpf/detection/tika/TikaTextDetectionComponent.java, line 201 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/245#-MYkqKKNAYLo1bo9nWBO:-MYkqKKNAYLo1bo9nWBP:b-20kgqo) ([raw file](https://github.com/openmpf/openmpf-components/blob/80286fdae62e4359f75fbc94b621e93dc02739b3/java/TikaTextDetection/src/main/java/org/mitre/mpf/detection/tika/TikaTextDetectionComponent.java#L201)):*
> ```Java
> 
>                     genericDetectionProperties.put("PAGE_NUM", String.format("%0" + String.valueOf(pageIDLen) + "d", p + 1));
>                     genericDetectionProperties.put("PARAGRAPH_NUM", String.format("%0" + String.valueOf(pageIDLen) + "d", s + 1));
> ```

In two places in the code you use `pageIDLen` to determine the number of digits to represent the section number. That will not work as intended if the number of sections on a given page exceeds the number of pages. For example, 10 sections on 1 page.
___
*[java/TikaTextDetection/src/test/java/org/mitre/mpf/detection/tika/TestTikaTextDetectionComponent.java, line 88 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/245#-MYkrrWg7Dt3Pxf9rDmW:-MYkrrWg7Dt3Pxf9rDmX:b-3csgv6) ([raw file](https://github.com/openmpf/openmpf-components/blob/80286fdae62e4359f75fbc94b621e93dc02739b3/java/TikaTextDetection/src/test/java/org/mitre/mpf/detection/tika/TestTikaTextDetectionComponent.java#L88)):*
> ```Java
>         testTrack = tracks.get(3);
>         assertEquals("Expected language does not match.", "Japanese", testTrack.getDetectionProperties().get("TEXT_LANGUAGE"));
> ```

Assert empty text on slide 5.
___
*[java/TikaTextDetection/src/test/java/org/mitre/mpf/detection/tika/TestTikaTextDetectionComponent.java, line 114 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/245#-MYktFfK-_1Wga--L0mT:-MYktFfK-_1Wga--L0mU:b-blbssc) ([raw file](https://github.com/openmpf/openmpf-components/blob/80286fdae62e4359f75fbc94b621e93dc02739b3/java/TikaTextDetection/src/test/java/org/mitre/mpf/detection/tika/TestTikaTextDetectionComponent.java#L114)):*
> ```Java
> 
>     @Test
>     public void testGetDetectionsPowerPointFile() throws MPFComponentDetectionError {
> ```

Can this test be combined with `testGetDetectionsGeneric()`? It seems redundant.

I think we should rename the existing `testGetDetectionsGeneric()`test to `testGetDetectionsPowerPointFile()`.
___
*[java/TikaTextDetection/src/test/resources/data/test-tika-detection.docx, line 0 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/245#-MYkjqXu-8PDtukdwSle:-MYkjqXv0gO2uq4JhPde:b-7n0mym) ([raw file](https://github.com/openmpf/openmpf-components/blob/80286fdae62e4359f75fbc94b621e93dc02739b3/java/TikaTextDetection/src/test/resources/data/test-tika-detection.docx#L0)):*
This part is a little off:

```
Testing, this is the first section of page 2. This test will determine if multiple sections of text can be properly sectioned with the TikaTextDetection component. Testing, this is the first section of page 1. This test will determine if multiple sections of text can be properly sectioned with the TikaTextDetection component. 
```

> first section of page 1

Should be

> first section of page 2

Same issue with other paragraphs on page 2.

**Review by hhuangMITRE — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/245)* status: 1 of 6 files reviewed, 8 unresolved discussions (waiting on @jrobble)

___
*[java/TikaTextDetection/src/main/java/org/mitre/mpf/detection/tika/TextExtractionContentHandler.java, line 36 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/245#-MYkkV4i7-dSrX_Lj2Pw:-MYpdjFo346QVi5vsvcy:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/80286fdae62e4359f75fbc94b621e93dc02739b3/java/TikaTextDetection/src/main/java/org/mitre/mpf/detection/tika/TextExtractionContentHandler.java#L36)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

"div" and "p" can be `private static`. 
</blockquote></details>

Done.
___
*[java/TikaTextDetection/src/main/java/org/mitre/mpf/detection/tika/TextExtractionContentHandler.java, line 115 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/245#-MYknbU627GywhW1SlsK:-MYpdm3N5Q3eYXT4NGaz:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/80286fdae62e4359f75fbc94b621e93dc02739b3/java/TikaTextDetection/src/main/java/org/mitre/mpf/detection/tika/TextExtractionContentHandler.java#L115)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

For sanity, let's keep the order of these operations as close to those in `startPage()` as possible.
</blockquote></details>

Done.
___
*[java/TikaTextDetection/src/main/java/org/mitre/mpf/detection/tika/TextExtractionContentHandler.java, line 119 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/245#-MYkmQ4lCOyarwXhLA0T:-MYpdnsUBG8E_dXBRT9c:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/80286fdae62e4359f75fbc94b621e93dc02739b3/java/TikaTextDetection/src/main/java/org/mitre/mpf/detection/tika/TextExtractionContentHandler.java#L119)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Instead of `.length() == 0`, please use `.isEmpty()`. I counted three instances of this in your code. Please change them all.
</blockquote></details>

Done.
___
*[java/TikaTextDetection/src/main/java/org/mitre/mpf/detection/tika/TikaTextDetectionComponent.java, line 165 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/245#-MYkpfb4B4j9eX1-zMeB:-MYpds2rDNpYmrsj5qz6:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/80286fdae62e4359f75fbc94b621e93dc02739b3/java/TikaTextDetection/src/main/java/org/mitre/mpf/detection/tika/TikaTextDetectionComponent.java#L165)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Should this line be moved below the `if (textDetect.length() == 0) {` check? You only generate the track if the section is not empty.
</blockquote></details>

Done.
___
*[java/TikaTextDetection/src/main/java/org/mitre/mpf/detection/tika/TikaTextDetectionComponent.java, line 201 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/245#-MYkqKKNAYLo1bo9nWBO:-MYpeB7o5MwaTht7DvWh:b-b07qtd) ([raw file](https://github.com/openmpf/openmpf-components/blob/80286fdae62e4359f75fbc94b621e93dc02739b3/java/TikaTextDetection/src/main/java/org/mitre/mpf/detection/tika/TikaTextDetectionComponent.java#L201)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

In two places in the code you use `pageIDLen` to determine the number of digits to represent the section number. That will not work as intended if the number of sections on a given page exceeds the number of pages. For example, 10 sections on 1 page.
</blockquote></details>

Thanks for catching that. Updated to check length of page and section IDs. 

Also, should I rename `"PARAGRAPH_NUM"` to `"SECTION_NUM"`? 
___
*[java/TikaTextDetection/src/test/java/org/mitre/mpf/detection/tika/TestTikaTextDetectionComponent.java, line 88 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/245#-MYkrrWg7Dt3Pxf9rDmW:-MYpegKTDENG_CCHQ-ZA:b-plbi09) ([raw file](https://github.com/openmpf/openmpf-components/blob/80286fdae62e4359f75fbc94b621e93dc02739b3/java/TikaTextDetection/src/test/java/org/mitre/mpf/detection/tika/TestTikaTextDetectionComponent.java#L88)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Assert empty text on slide 5.
</blockquote></details>

Done. Swapped to use`.isEmpty()` with `assertTrue` check.
___
*[java/TikaTextDetection/src/test/java/org/mitre/mpf/detection/tika/TestTikaTextDetectionComponent.java, line 114 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/245#-MYktFfK-_1Wga--L0mT:-MYperWIDmoNMTEqddl5:b-jvgq5i) ([raw file](https://github.com/openmpf/openmpf-components/blob/80286fdae62e4359f75fbc94b621e93dc02739b3/java/TikaTextDetection/src/test/java/org/mitre/mpf/detection/tika/TestTikaTextDetectionComponent.java#L114)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Can this test be combined with `testGetDetectionsGeneric()`? It seems redundant.

I think we should rename the existing `testGetDetectionsGeneric()`test to `testGetDetectionsPowerPointFile()`.
</blockquote></details>

Done. The test was completely redundant with the `testGetDetectionsGeneric()` so I removed it and renamed the  first test to `testGetDetectionsGeneric()`. 
___
*[java/TikaTextDetection/src/test/resources/data/test-tika-detection.docx, line  at r1](https://reviewable.io/reviews/openmpf/openmpf-components/245#-MYkjqXu-8PDtukdwSle:-MYpfAZB0EYIIKf1dzX-:b-yw3w4j) ([raw file](https://github.com/openmpf/openmpf-components/blob/80286fdae62e4359f75fbc94b621e93dc02739b3/java/TikaTextDetection/src/test/resources/data/test-tika-detection.docx#L)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

This part is a little off:

```
Testing, this is the first section of page 2. This test will determine if multiple sections of text can be properly sectioned with the TikaTextDetection component. Testing, this is the first section of page 1. This test will determine if multiple sections of text can be properly sectioned with the TikaTextDetection component. 
```

> first section of page 1

Should be

> first section of page 2

Same issue with other paragraphs on page 2.
</blockquote></details>

Thanks for catching that. I've updated the test document.

**Review by jrobble — CHANGES_REQUESTED** [review]
> Reviewed 5 of 6 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/245)* status: all files reviewed, 3 unresolved discussions (waiting on @hhuangMITRE)

___
*[java/TikaTextDetection/src/main/java/org/mitre/mpf/detection/tika/TikaTextDetectionComponent.java, line 133 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/245#-MZE6Zib1X3811KkjFui:-MZE6Zib1X3811KkjFuj:bjb3vzg) ([raw file](https://github.com/openmpf/openmpf-components/blob/80286fdae62e4359f75fbc94b621e93dc02739b3/java/TikaTextDetection/src/main/java/org/mitre/mpf/detection/tika/TikaTextDetectionComponent.java#L133)):*
> ```Java
>             try {
>                 identifier.loadModels();
>             } catch (IOException e) {
> ```

I assume that this no longer throws an exception in the latest version of Tika?
___
*[java/TikaTextDetection/src/main/java/org/mitre/mpf/detection/tika/TikaTextDetectionComponent.java, line 201 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/245#-MYkqKKNAYLo1bo9nWBO:-MZDv5PS6Z7OEWA8Mfrx:b-wcoevn) ([raw file](https://github.com/openmpf/openmpf-components/blob/80286fdae62e4359f75fbc94b621e93dc02739b3/java/TikaTextDetection/src/main/java/org/mitre/mpf/detection/tika/TikaTextDetectionComponent.java#L201)):*
<details><summary><i>Previously, hhuangMITRE (Howard W Huang) wrote…</i></summary><blockquote>

Thanks for catching that. Updated to check length of page and section IDs. 

Also, should I rename `"PARAGRAPH_NUM"` to `"SECTION_NUM"`? 
</blockquote></details>

Yeah, I think `SECTION_NUM` is more generic. Some of these "paragraphs" are just lines. I wouldn't call a single bullet point, or cell in a table, a paragraph. That's just how Tika parses them out.
___
*[java/TikaTextDetection/src/main/java/org/mitre/mpf/detection/tika/TikaTextDetectionComponent.java, line 133 at r3](https://reviewable.io/reviews/openmpf/openmpf-components/245#-MZDumoL8IoBgU-c0k2g:-MZDumoL8IoBgU-c0k2h:b-hw0i53) ([raw file](https://github.com/openmpf/openmpf-components/blob/cad57a16621670b06769bbf5c1062c56e08f1b96/java/TikaTextDetection/src/main/java/org/mitre/mpf/detection/tika/TikaTextDetectionComponent.java#L133)):*
> ```Java
> 
>             int maxIDLength = (int) (java.lang.Math.log10(pageOutput.size())) + 1;
>             int paragraphIDLength = (int) (java.lang.Math.log10(pageOutput.get(0).size())) + 1;
> ```

This assumes that the first page has the most sections. For example, this doesn't work properly if the first page has 1 section and the second page has 100 sections.

**Review by hhuangMITRE — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/245)* status: 5 of 7 files reviewed, 3 unresolved discussions (waiting on @jrobble)

___
*[java/TikaTextDetection/src/main/java/org/mitre/mpf/detection/tika/TikaTextDetectionComponent.java, line 133 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/245#-MZE6Zib1X3811KkjFui:-MZELvAD6XlulGlgKvdD:bbqgqc) ([raw file](https://github.com/openmpf/openmpf-components/blob/80286fdae62e4359f75fbc94b621e93dc02739b3/java/TikaTextDetection/src/main/java/org/mitre/mpf/detection/tika/TikaTextDetectionComponent.java#L133)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

I assume that this no longer throws an exception in the latest version of Tika?
</blockquote></details>

Yep, in the latest version, `loadModels()` no longer throws the `IOException`. There was a compilation error after the Tika update so I double checked the code documentation and found the updated behavior. There is one overloaded method that still throws `IOExceptions` but that one requires users to [request particular language detections](https://tika.apache.org/1.22/api/org/apache/tika/langdetect/OptimaizeLangDetector.html#loadModels--).
___
*[java/TikaTextDetection/src/main/java/org/mitre/mpf/detection/tika/TikaTextDetectionComponent.java, line 201 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/245#-MYkqKKNAYLo1bo9nWBO:-MZEN9vI482kpHsA8VUu:bv9it9v) ([raw file](https://github.com/openmpf/openmpf-components/blob/80286fdae62e4359f75fbc94b621e93dc02739b3/java/TikaTextDetection/src/main/java/org/mitre/mpf/detection/tika/TikaTextDetectionComponent.java#L201)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Yeah, I think `SECTION_NUM` is more generic. Some of these "paragraphs" are just lines. I wouldn't call a single bullet point, or cell in a table, a paragraph. That's just how Tika parses them out.
</blockquote></details>

Done. I agree it's appropriate after trying out the new sectioning behavior.
___
*[java/TikaTextDetection/src/main/java/org/mitre/mpf/detection/tika/TikaTextDetectionComponent.java, line 133 at r3](https://reviewable.io/reviews/openmpf/openmpf-components/245#-MZDumoL8IoBgU-c0k2g:-MZENQLh1Atk3BsIE6ps:bhbpiwc) ([raw file](https://github.com/openmpf/openmpf-components/blob/cad57a16621670b06769bbf5c1062c56e08f1b96/java/TikaTextDetection/src/main/java/org/mitre/mpf/detection/tika/TikaTextDetectionComponent.java#L133)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

This assumes that the first page has the most sections. For example, this doesn't work properly if the first page has 1 section and the second page has 100 sections.
</blockquote></details>

Done. Updated to check across pages.

**Review by jrobble — APPROVED** [review]
> Reviewed 1 of 2 files at r4, 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/245)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @hhuangMITRE)

**Pull request merged**
