### PR TITLE
1770 change keyword tagging component to use perl for regex syntax 

### PR DESCRIPTION
**Pull request by fpc0002**
**Issues:**

https://github.com/openmpf/openmpf/issues/1770

- - -
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/375)

### CODE REVIEW

**Review by jrobble — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/375)* status: all files reviewed, 1 unresolved discussion (waiting on @fpc0002)

___
*[`cpp/KeywordTagging/plugin-files/config/text-tags.json` line 89 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/375#-O-CvxnnCwM53ZUHZmDY:-O-CvxnnCwM53ZUHZmDZ:b-skcxun) ([raw file](https://github.com/openmpf/openmpf-components/blob/fd1aca6405990e12c6973e95e09ff6a0120c1c12/cpp/KeywordTagging/plugin-files/config/text-tags.json#L89)):*
> ```JSON
> 			{"pattern": "₪"},
> 			{"pattern": "сом"},
> 			{"pattern": "⃀"},
> ```

As discussed, add support for SSN and the relevant unit tests.

**Review by jrobble — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/375)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @fpc0002)

**Review by jrobble — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/375)* status: all files reviewed, 1 unresolved discussion (waiting on @fpc0002)

___
*[`cpp/KeywordTagging/test/test_keyword_tagging.cpp` line 948 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/375#-O-MjeWR8VQtE0mm7s8k:-O-MjeWR8VQtE0mm7s8l:b-7lbf3l) ([raw file](https://github.com/openmpf/openmpf-components/blob/288d682ae84db2e7d218d2eb08e40c75719c6b80/cpp/KeywordTagging/test/test_keyword_tagging.cpp#L948)):*
> ```cpp
> }
> 
> TEST(KEYWORDTAGGING, SSNTest) {
> ```

Please merge develop into this. It will require updating this unit test with uppercase tags.

**Review by fpc0002 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/375)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @jrobble)

___
*[`cpp/KeywordTagging/plugin-files/config/text-tags.json` line 89 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/375#-O-CvxnnCwM53ZUHZmDY:-O-N1dERE1XK2_F9gj8E:bb6un1j) ([raw file](https://github.com/openmpf/openmpf-components/blob/fd1aca6405990e12c6973e95e09ff6a0120c1c12/cpp/KeywordTagging/plugin-files/config/text-tags.json#L89)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

As discussed, add support for SSN and the relevant unit tests.
</blockquote></details>

Done
___
*[`cpp/KeywordTagging/test/test_keyword_tagging.cpp` line 948 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/375#-O-MjeWR8VQtE0mm7s8k:-O-N1es6A1u3xnlB8Zgj:bb6un1j) ([raw file](https://github.com/openmpf/openmpf-components/blob/288d682ae84db2e7d218d2eb08e40c75719c6b80/cpp/KeywordTagging/test/test_keyword_tagging.cpp#L948)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Please merge develop into this. It will require updating this unit test with uppercase tags.
</blockquote></details>

Done

**Review by jrobble — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/375)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @fpc0002)

**Pull request merged**
