### PR TITLE
Updating TesseractOCRTextDetection component to specify custom tessda…

### PR DESCRIPTION
**Pull request by hhuangMITRE**
…ta subdirectory.

---
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/188)

### CODE REVIEW

**Comment by brosenberg42** [comment]
There is something wrong with this related to caching models. I don't think it checks `TESSDATA_MODELS_SUBDIRECTORY` after the first job runs.  
First, I ran a normal job and it completed as expected. Then, I changed the name of the tessdata directory without changing `TESSDATA_MODELS_SUBDIRECTORY` and ran another job. The job completed successfully even though the tessdata directory was gone. Then, I restarted the component and ran a job. That job failed as expected.

**Comment by brosenberg42** [comment]
This does not fix the problem. I was explaining how I determined that it is using values from the previous job, even though I changed TESSDATA_MODELS_SUBDIRECTORY. The problem is that changing TESSDATA_MODELS_SUBDIRECTORY does nothing for every job other than the first job the component processes.

**Review by hhuangMITRE — COMMENTED** [review]
Yeah, I also agree with that. I realized that if users wanted to swap to 'tessdata_fast' or 'tessdata_best' then changing the TESSDATA_MODELS_SUBDIRECTORY should force the component to load up a new version of each language file. I've made a change to how we're caching models to take that into account and running some updated unit test to ensure that model reload must occur under these conditions. I'm about to push in the updates now. Thanks!

> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/188#-:-MJDCTDo9zeUznpDlYId:b-hdpcr0)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @brosenberg42 and @jrobble)

**Review by jrobble — APPROVED** [review]
> Reviewed 2 of 5 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/188)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @brosenberg42)

**Pull request merged**
