### PR TITLE
Cnowacki/resize error

### PR DESCRIPTION
**Pull request by clnowacki**
**Issues:**

- https://github.com/openmpf/openmpf/issues/1337
- https://github.com/openmpf/openmpf/issues/1353

**Related PRs:**

- https://github.com/openmpf/openmpf/pull/1352

---
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/260)

### CODE REVIEW

**Review by jrobble — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2, 51 of 53 files at r4.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/260)* status: 51 of 53 files reviewed, 1 unresolved discussion (waiting on @clnowacki and @jrobble)

*[a discussion](https://reviewable.io/reviews/openmpf/openmpf-components/260#-MdImAHE9b_JXEA9se0F:-MdImAHE9b_JXEA9se0G:b-pnlsrr) (no related file):*
You merged develop into this branch, but it targets master. That pulled in the new AzureReadDetection component, which should only exist in develop.

You wanted to merge master into this branch instead. 

---

**Review by jrobble — COMMENTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/260)* status: 52 of 53 files reviewed, 1 unresolved discussion (waiting on @clnowacki and @jrobble)

**Comment by clnowacki** [comment]
> You merged develop into this branch, but it targets master. That pulled in the new AzureReadDetection component, which should only exist in develop.
> 
> You wanted to merge master into this branch instead.

I think that was a mistake -- shouldn't I be trying to merge to develop instead of master? This is not a hot fix. Should I just change the PR to target develop?

**Review by jrobble — COMMENTED** [review]
In general, we've been trying to land small changes to master instead of develop to get them to the user quicker. This was something that was impacting the user in production, so I think landing to master makes the most sense.

> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/260#-:-MdJTWPCA_J_OuxoLWjX:bo8vi09)* status: 52 of 53 files reviewed, 1 unresolved discussion (waiting on @clnowacki and @jrobble)

**Comment by clnowacki** [comment]
Closing this pull request to recreate it properly to merge to master.

**Pull request closed without merging**
