### PR TITLE
Hf merge develop/tesseract specify tessdata models

### PR DESCRIPTION
**Pull request by hhuangMITRE**
Redid branch PR and merged 4.1 into `develop` instead of `master`.

---
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/193)

### CODE REVIEW

**Review by jrobble — CHANGES_REQUESTED** [review]
The code looks good. I haven't run anything. @brosenberg42 should be the one to approve this PR since he approved the last one.

> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/193#-:-MK6t7rODvyJIul_mrbe:b-ar80g)* status: all files reviewed, 1 unresolved discussion (waiting on @hhuangMITRE)

___
*[cpp/TesseractOCRTextDetection/README.md, line 121 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/193#-MK6szseEDQ3oh9qo3x8:-MK6szseEDQ3oh9qo3x9:b-cctur1) ([raw file](https://github.com/openmpf/openmpf-components/blob/826e34d7de8e97fb5ae147f38279ba642c14c558/cpp/TesseractOCRTextDetection/README.md#L121)):*
> ```Markdown
> `$MPF_HOME/plugins/TesseractOCRTextDetection/tessdata` directory and script models
> are stored in `tessdata/script` subdirectory. Users can set a new tessdata directory by
> modifying the MODELS_DIR_PATH and TESSDATA_MODELS_SUBDIRECTORY job properties. Once set,
> ```

Use backticks around `MODELS_DIR_PATH` and `TESSDATA_MODELS_SUBDIRECTORY`.

**Review by hhuangMITRE — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/193)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @jrobble)

___
*[cpp/TesseractOCRTextDetection/README.md, line 121 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/193#-MK6szseEDQ3oh9qo3x8:-MKBHAZy3rky5liSirge:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/826e34d7de8e97fb5ae147f38279ba642c14c558/cpp/TesseractOCRTextDetection/README.md#L121)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Use backticks around `MODELS_DIR_PATH` and `TESSDATA_MODELS_SUBDIRECTORY`.
</blockquote></details>

Done.

**Review by jrobble — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/193)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @brosenberg42)

**Comment by jrobble** [comment]
@brosenberg42 informed me that this change should land to master first so that we can generate a hotfix image for 5.0. I took the liberty of recreating the PR with your most recent updates: https://github.com/openmpf/openmpf-components/pull/195. Closing this PR. Sorry for the confusion.

**Pull request closed without merging**
