### PR TITLE
Clarify the difference between Docker and non-Docker behaviors.

### PR DESCRIPTION
**Pull request by jrobble**
**Issues:**

- https://github.com/openmpf/openmpf/issues/1351

**Related PRs:**

- https://github.com/openmpf/openmpf.github.io/pull/130
- https://github.com/openmpf/openmpf-contrib-components/pull/73

---
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/259)

### CODE REVIEW

**Review by clnowacki — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/259)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @brosenberg42)

**Review by brosenberg42 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/259)* status: all files reviewed, 2 unresolved discussions (waiting on @jrobble)

___
*[README.md, line 50 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/259#-McKMI9j7z7fi0SYl3g3:-McKMI9j7z7fi0SYl3g4:b-vu5xim) ([raw file](https://github.com/openmpf/openmpf-components/blob/a83c10e405903ea04d011fbea6e43e72b153344f/README.md#L50)):*
> ```Markdown
> - [How to Create a Java Component](https://openmpf.github.io/docs/site/Java-Batch-Component-API/index.html#getting-started)
> 
> ### Building a Component Using Docker
> ```

I think we should indicate that this applies to component of all languages.
___
*[README.md, line 55 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/259#-McKMt6lEIYONtSXCPHu:-McKMt6lEIYONtSXCPHv:br57m8d) ([raw file](https://github.com/openmpf/openmpf-components/blob/a83c10e405903ea04d011fbea6e43e72b153344f/README.md#L55)):*
> ```Markdown
> - Run the following command where "openmpf_component_name" is the name of the component image you want to generate. For a list of component image names, refer to [docker-compose.components.yml](https://github.com/openmpf/openmpf-docker/blob/master/docker-compose.components.yml):
> ```
> DOCKER_BUILDKIT=1 docker build . -t openmpf_component_name
> ```

The other sections mention installing the appropriate SDK. I think we should add `--build-arg BUILD_REGISTRY=openmpf/ --build-arg BUILD_TAG=<version>` to this command. That way the base image will be automatically pulled and we don't have to mention anything about getting the base images.

**Review by jrobble — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/259)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @brosenberg42 and @clnowacki)

___
*[README.md, line 50 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/259#-McKMI9j7z7fi0SYl3g3:-McVA-fn-HImU7pEjYS9:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/a83c10e405903ea04d011fbea6e43e72b153344f/README.md#L50)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

I think we should indicate that this applies to component of all languages.
</blockquote></details>

Done.
___
*[README.md, line 55 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/259#-McKMt6lEIYONtSXCPHu:-McV9zqvBs3mEunDIDCw:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/a83c10e405903ea04d011fbea6e43e72b153344f/README.md#L55)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

The other sections mention installing the appropriate SDK. I think we should add `--build-arg BUILD_REGISTRY=openmpf/ --build-arg BUILD_TAG=<version>` to this command. That way the base image will be automatically pulled and we don't have to mention anything about getting the base images.
</blockquote></details>

Done.

**Review by brosenberg42 — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/259)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jrobble)

**Pull request merged**
