### PR TITLE
Hf merge master/tesseract specify tessdata models.

### PR DESCRIPTION
**Pull request by hhuangMITRE**
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/192)

### CODE REVIEW

**Comment by hhuangMITRE** [comment]
Just leaving a note here, based on the initial discussion, I assumed we are merging into `master`  first followed by `develop`. Let me know if that is the case or if this is strictly a `develop` only merge. Thanks!

**Comment by jrobble** [comment]
There are three commits in develop for openmpf-components that aren't in master. Since develop and mater are out of sync please land this change to develop.

It's really only useful to land changes to master and then develop if the develop branch has not yet deviated from master. In this case we landed the form recognizer to develop already, so they are out of sync. That was a new feature that should really only be in develop right now.

**Comment by hhuangMITRE** [comment]
Understood, thanks. In that case, I'm closing this PR down for the merge to `master` branch and resubmitting the merge to `develop` shortly.

**Comment by jrobble** [comment]
___
*[cpp/TesseractOCRTextDetection/test/test_tesseract_ocr_detection.cpp, line 284 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/192#-MK63hdzDLQCkkaVgh0T:-MK63hdzDLQCkkaVgh0U:b-f1la1t) ([raw file](https://github.com/openmpf/openmpf-components/blob/86a721cb588dbe68de164880b9ee33a314a00c97/cpp/TesseractOCRTextDetection/test/test_tesseract_ocr_detection.cpp#L284)):*
> ```cpp
>     {
>         auto custom_properties_copy = custom_properties;
>         // When set to parallel processing, ensure that model reload occurs and fails due to missing model files.
> ```

Please mention in the comment that parallel processing doesn't use the cache, so the model files aren't available since they were removed.

**Comment by hhuangMITRE** [comment]
___
*[cpp/TesseractOCRTextDetection/test/test_tesseract_ocr_detection.cpp, line 284 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/192#-MK63hdzDLQCkkaVgh0T:-MK6N5FZ--b3j0sOp6-5:bevam5x) ([raw file](https://github.com/openmpf/openmpf-components/blob/86a721cb588dbe68de164880b9ee33a314a00c97/cpp/TesseractOCRTextDetection/test/test_tesseract_ocr_detection.cpp#L284)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Please mention in the comment that parallel processing doesn't use the cache, so the model files aren't available since they were removed.
</blockquote></details>

Done. Also updated the README. See PR for `develop` merge PR (https://reviewable.io/reviews/openmpf/openmpf-components/193#)

**Pull request closed without merging**
