### PR TITLE
Updated for OpenCV 3.3.

### PR DESCRIPTION
**Pull request by jrobble**
Fixed Caffe component to use BGR over RGB. Removed transpose property.

---
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/26)

### CODE REVIEW

**Comment by clnowacki** [comment]
Reviewed 6 of 7 files at r1.
Review status: 6 of 7 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[cpp/CaffeDetection/plugin-files/descriptor/descriptor.json, line 179 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-components/26#-KuJhQTQiUh8d6vTikfM:-KuJhQTQiUh8d6vTikfN:b-yi1xht) ([raw file](https://github.com/openmpf/openmpf-components/blob/415fec918e752dcebf09bc561f71c9a313d10907/cpp/CaffeDetection/plugin-files/descriptor/descriptor.json#L179)):*
> ```JSON
>         {
>           "name": "SUBTRACT_BLUE_VALUE",
>           "description": "After the input image is resized and cropped, subtract this value from the blue color channel for all of the pixels. The range is [0, 255]. The default value (0) is for the default model (googlenet).",
> ```

Should we make these all type FLOAT instead of INT, since that is what the algorithm expects? Might the user want to enter values like 120.4?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-components/26)*

**Comment by jrobble** [comment]
*[cpp/CaffeDetection/plugin-files/descriptor/descriptor.json, line 179 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-components/26#-KuJhQTQiUh8d6vTikfM:-KuKIm_P69_JJoEvdmpS:bhv2sp4) ([raw file](https://github.com/openmpf/openmpf-components/blob/415fec918e752dcebf09bc561f71c9a313d10907/cpp/CaffeDetection/plugin-files/descriptor/descriptor.json#L179)):*
<details><summary><i>Previously, clnowacki wrote…</i></summary><blockquote>

Should we make these all type FLOAT instead of INT, since that is what the algorithm expects? Might the user want to enter values like 120.4?
</blockquote></details>

Honestly, I don't know if a user would ever enter decimal values, but in theory I don't see why not. Since the blob uses CV_32F internally, decimal values will be preserved after the subtraction.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-components/26)*

**Comment by clnowacki** [comment]
Review status: 6 of 7 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[cpp/CaffeDetection/plugin-files/descriptor/descriptor.json, line 179 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-components/26#-KuJhQTQiUh8d6vTikfM:-KuKMGcHmjr5HbpCNJuk:b-beygxn) ([raw file](https://github.com/openmpf/openmpf-components/blob/415fec918e752dcebf09bc561f71c9a313d10907/cpp/CaffeDetection/plugin-files/descriptor/descriptor.json#L179)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Honestly, I don't know if a user would ever enter decimal values, but in theory I don't see why not. Since the blob uses CV_32F internally, decimal values will be preserved after the subtraction.
</blockquote></details>

I'm not exactly sure that I understand your comment. But if the user tries to enter a non-integral value for a property of type INT on the pipeline configuration page, they will get an error.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-components/26)*

**Comment by clnowacki** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-components/26)*

**Comment by clnowacki** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-components/26#-:-KuKNk5Hjme1EgOMK5Wn:bnfp4nl)*

**Comment by clnowacki** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[cpp/CaffeDetection/plugin-files/descriptor/descriptor.json, line 179 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-components/26#-KuJhQTQiUh8d6vTikfM:-KuKNyFPHhfDkhCVamBP:b3mso7k) ([raw file](https://github.com/openmpf/openmpf-components/blob/415fec918e752dcebf09bc561f71c9a313d10907/cpp/CaffeDetection/plugin-files/descriptor/descriptor.json#L179)):*
<details><summary><i>Previously, clnowacki wrote…</i></summary><blockquote>

I'm not exactly sure that I understand your comment. But if the user tries to enter a non-integral value for a property of type INT on the pipeline configuration page, they will get an error.
</blockquote></details>

Never mind. I see that I did misunderstand you, and approved your changes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-components/26)*

**Pull request merged**
