### PR TITLE
Issue189

### PR DESCRIPTION
**Pull request by clnowacki**
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/28)

### CODE REVIEW

**Comment by jrobble** [comment]
Let's see what the users say about using cv::FileStorage.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-components/28#-:-Kv2uhD_PtfNSjpidgSO:bhl1shq)*

**Comment by brosenberg42** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[cpp/CaffeDetection/CaffeDetection.cpp, line 226 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-components/28#-Kv8ATSS6lCnIU00BHMl:-Kv8ATSS6lCnIU00BHMm:bixtdej) ([raw file](https://github.com/openmpf/openmpf-components/blob/79afaa6ac76fb93b13634ddf67d491cc5c665283/cpp/CaffeDetection/CaffeDetection.cpp#L226)):*
> ```cpp
>         // Now put any activation layers in the detection properties
>         if (!activation_info.empty()) {
>             for (std::pair<std::string,std::string> activation : activation_info) {
> ```

I think `activation` should be a const reference.

---

*[cpp/CaffeDetection/CaffeDetection.cpp, line 307 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-components/28#-Kv8AIBcsKNv-XQ-1L2p:-Kv8AIBcsKNv-XQ-1L2q:b-9aspm8) ([raw file](https://github.com/openmpf/openmpf-components/blob/79afaa6ac76fb93b13634ddf67d491cc5c665283/cpp/CaffeDetection/CaffeDetection.cpp#L307)):*
> ```cpp
>         boost::split(act_layer_names, layers_list,
>                      boost::is_any_of(" ;"), boost::token_compress_on);
>         for (std::string name : act_layer_names) {
> ```

I think `name` should be a const reference.

---

*[cpp/CaffeDetection/CaffeDetection.cpp, line 414 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-components/28#-Kv8AstTCN1eZL7Ui7W_:-Kv8AstTCN1eZL7Ui7Wa:bd81utz) ([raw file](https://github.com/openmpf/openmpf-components/blob/79afaa6ac76fb93b13634ddf67d491cc5c665283/cpp/CaffeDetection/CaffeDetection.cpp#L414)):*
> ```cpp
>         // final output layer that was used to get the list of
>         // classifications. The rest are output for the activation layers.
>         cv::Mat act = mats[i+1];
> ```

Will `mats.size()` always be at least `good_names.size() + 1`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-components/28)*

**Comment by jrobble** [comment]
*[cpp/CaffeDetection/CaffeDetection.cpp, line 430 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-components/28#-Kv8Dki_yQ3hPIdEDkVE:-Kv8Dki_yQ3hPIdEDkVF:brifm86) ([raw file](https://github.com/openmpf/openmpf-components/blob/79afaa6ac76fb93b13634ddf67d491cc5c665283/cpp/CaffeDetection/CaffeDetection.cpp#L430)):*
> ```cpp
> 
>         std::transform(name.begin(), name.end(), name.begin(), ::toupper);
>         name += " ACTIVATION LIST";
> ```

Let's say "ACTIVATION MATRIX" instead.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-components/28)*

**Comment by jrobble** [comment]
*[cpp/CaffeDetection/CaffeDetection.cpp, line 439 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-components/28#-Kv8CzjizrhnAHvZAyKa:-Kv8Czjjl3b0X6UzkskN:b-bnqn15) ([raw file](https://github.com/openmpf/openmpf-components/blob/79afaa6ac76fb93b13634ddf67d491cc5c665283/cpp/CaffeDetection/CaffeDetection.cpp#L439)):*
> ```cpp
>         std::transform(name.begin(), name.end(), name.begin(), ::toupper);
>         name += " ACTIVATION LIST";
>         activations.push_back(std::make_pair(name, "NOT FOUND"));
> ```

Now that I've thought about it some more, I would prefer that we use "INVALID" instead of "NOT FOUND".

If we end up writing the activation matrix JSON to disk, users might get confused when we have something like:

"LAYER X ACTIVATION MATRIX PATH": "NOT FOUND"

That makes it seem like we couldn't write the file or something.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-components/28)*

**Comment by jrobble** [comment]
*[cpp/CaffeDetection/CaffeDetection.cpp, line 430 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-components/28#-Kv8Dki_yQ3hPIdEDkVE:-Kv8E1wn7MujBIEx9eMc:b-qdi9en) ([raw file](https://github.com/openmpf/openmpf-components/blob/79afaa6ac76fb93b13634ddf67d491cc5c665283/cpp/CaffeDetection/CaffeDetection.cpp#L430)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Let's say "ACTIVATION MATRIX" instead.
</blockquote></details>

That is, if we're writing out the whole JSON, let's use "ACTIVATION MATRIX". As you currently have it, it is a flat list.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-components/28)*

**Comment by clnowacki** [comment]
Review status: 0 of 3 files reviewed at latest revision, 5 unresolved discussions.

---

*[cpp/CaffeDetection/CaffeDetection.cpp, line 414 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-components/28#-Kv8AstTCN1eZL7Ui7W_:-Kv8XyqJeZAS33ij7A1H:bb77ufg) ([raw file](https://github.com/openmpf/openmpf-components/blob/79afaa6ac76fb93b13634ddf67d491cc5c665283/cpp/CaffeDetection/CaffeDetection.cpp#L414)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

Will `mats.size()` always be at least `good_names.size() + 1`?
</blockquote></details>

Yes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-components/28)*

**Comment by jrobble** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[cpp/CaffeDetection/CaffeDetection.cpp, line 430 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-components/28#-Kv8Dki_yQ3hPIdEDkVE:-KvDu0N3tp7Q1l6AUj7s:bgr13p9) ([raw file](https://github.com/openmpf/openmpf-components/blob/79afaa6ac76fb93b13634ddf67d491cc5c665283/cpp/CaffeDetection/CaffeDetection.cpp#L430)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

That is, if we're writing out the whole JSON, let's use "ACTIVATION MATRIX". As you currently have it, it is a flat list.
</blockquote></details>

Let's move forward with the encoded JSON approach.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-components/28)*

**Comment by clnowacki** [comment]
Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[cpp/CaffeDetection/CaffeDetection.cpp, line 430 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-components/28#-Kv8Dki_yQ3hPIdEDkVE:-KvTN_wPk3rz-yijcT9y:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/79afaa6ac76fb93b13634ddf67d491cc5c665283/cpp/CaffeDetection/CaffeDetection.cpp#L430)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Let's move forward with the encoded JSON approach.
</blockquote></details>

Done.

---

*[cpp/CaffeDetection/CaffeDetection.cpp, line 439 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-components/28#-Kv8CzjizrhnAHvZAyKa:-KvTNbM5MIS_diyDYg1K:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/79afaa6ac76fb93b13634ddf67d491cc5c665283/cpp/CaffeDetection/CaffeDetection.cpp#L439)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Now that I've thought about it some more, I would prefer that we use "INVALID" instead of "NOT FOUND".

If we end up writing the activation matrix JSON to disk, users might get confused when we have something like:

"LAYER X ACTIVATION MATRIX PATH": "NOT FOUND"

That makes it seem like we couldn't write the file or something.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-components/28)*

**Comment by jrobble** [comment]
Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[cpp/CaffeDetection/plugin-files/descriptor/descriptor.json, line 149 at r2](https://reviewable.io:443/reviews/openmpf/openmpf-components/28#-KvTQMUWSPpqZV26rZye:-KvTQMUWSPpqZV26rZyf:b-6mev8m) ([raw file](https://github.com/openmpf/openmpf-components/blob/391625987d87788569866ecc7ba74f9ad9dd9bd7/cpp/CaffeDetection/plugin-files/descriptor/descriptor.json#L149)):*
> ```JSON
>         {
>           "name": "ACTIVATION_LAYER_LIST",
>           "description": "The list of names of layers within the specified model for which activation values should be reported in the output. The model activation layer names are defined in the .prototxt file associated with the model.",
> ```

Let's say "The semicolon-delimited list of names ...".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-components/28)*

**Comment by clnowacki** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[cpp/CaffeDetection/plugin-files/descriptor/descriptor.json, line 149 at r2](https://reviewable.io:443/reviews/openmpf/openmpf-components/28#-KvTQMUWSPpqZV26rZye:-KvXIUEjYqrlZIuny1Ju:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/391625987d87788569866ecc7ba74f9ad9dd9bd7/cpp/CaffeDetection/plugin-files/descriptor/descriptor.json#L149)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Let's say "The semicolon-delimited list of names ...".
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-components/28)*

**Comment by jrobble** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-components/28)*

**Pull request merged**
