### PR TITLE
Add support for whitelist to darknet

### PR DESCRIPTION
**Pull request by brosenberg42**
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/55)

### CODE REVIEW

**Comment by jrobble** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[cpp/DarknetDetection/DarknetDetection.cpp, line 59 at r1](https://beta.reviewable.io/reviews/openmpf/openmpf-components/55#-L8p5atF5KMczAFLqRKg:-L8p5atH-J2Jeoninrq-:bwhykkz) ([raw file](https://github.com/openmpf/openmpf-components/blob/8d492b243a4f27b7ec68a390b220898985c20bc1/cpp/DarknetDetection/DarknetDetection.cpp#L59)):*
> ```cpp
> 
> 
>     void trim(std::string& str) {
> ```

Can we use Boost for this?

---

*[cpp/DarknetDetection/DarknetDetection.cpp, line 102 at r1](https://beta.reviewable.io/reviews/openmpf/openmpf-components/55#-L8p6aoD6c3OogVowJA-:-L8p6aoD6c3OogVowJA0:ba4mfod) ([raw file](https://github.com/openmpf/openmpf-components/blob/8d492b243a4f27b7ec68a390b220898985c20bc1/cpp/DarknetDetection/DarknetDetection.cpp#L102)):*
> ```cpp
> 
>             for (const std::string &name : names) {
>                 size_t num_erased = temp_whitelist.erase(name);
> ```

Are you using erase here to speed up the search on the next loop iteration, or is there another reason?

---

*[cpp/DarknetDetection/DarknetDetection.cpp, line 448 at r1](https://beta.reviewable.io/reviews/openmpf/openmpf-components/55#-L8p80P--um4H7NZVa1V:-L8p80P--um4H7NZVa1W:b-ssz08x) ([raw file](https://github.com/openmpf/openmpf-components/blob/8d492b243a4f27b7ec68a390b220898985c20bc1/cpp/DarknetDetection/DarknetDetection.cpp#L448)):*
> ```cpp
> 
> 
> template <typename CF>
> ```

Do you need to use `CF` here or can we use `ClassFilter`?

---

*[cpp/DarknetDetection/DarknetDetection.cpp, line 467 at r1](https://beta.reviewable.io/reviews/openmpf/openmpf-components/55#-L8p88p16C09yWA2Hzyb:-L8p88p16C09yWA2Hzyc:b-ssz08x) ([raw file](https://github.com/openmpf/openmpf-components/blob/8d492b243a4f27b7ec68a390b220898985c20bc1/cpp/DarknetDetection/DarknetDetection.cpp#L467)):*
> ```cpp
> 
> 
> template <typename CF>
> ```

Do you need to use `CF` here or can we use `ClassFilter`?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/openmpf/openmpf-components/55)*

**Comment by jrobble** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[cpp/DarknetDetection/DarknetDetection.cpp, line 72 at r1](https://beta.reviewable.io/reviews/openmpf/openmpf-components/55#-L8pMxKL2UNizN_T5zcK:-L8pMxKN1nhH570wBOq4:b-ti1x0f) ([raw file](https://github.com/openmpf/openmpf-components/blob/8d492b243a4f27b7ec68a390b220898985c20bc1/cpp/DarknetDetection/DarknetDetection.cpp#L72)):*
> ```cpp
>     public:
> 
>         WhitelistFilter(const MPF::COMPONENT::Properties& props, const std::vector<std::string>& names) {
> ```

Currently, if the whitelist file is empty, UNRECOGNIZED_DETECTION_ERROR shows up in the output JSON. For errors related to the whitelist, consider using the following:

MPF_COULD_NOT_OPEN_DATAFILE (cannot open file)
MPF_COULD_NOT_READ_DATAFILE (content is invalid)

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/openmpf/openmpf-components/55)*

**Comment by brosenberg42** [comment]
Review status: 3 of 5 files reviewed at latest revision, 5 unresolved discussions.

---

*[cpp/DarknetDetection/DarknetDetection.cpp, line 59 at r1](https://beta.reviewable.io/reviews/openmpf/openmpf-components/55#-L8p5atF5KMczAFLqRKg:-L8rqh7L3Xntt72gwdse:b8svj3d) ([raw file](https://github.com/openmpf/openmpf-components/blob/8d492b243a4f27b7ec68a390b220898985c20bc1/cpp/DarknetDetection/DarknetDetection.cpp#L59)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Can we use Boost for this?
</blockquote></details>

I don't want to link and include boost in the component just to save 4 lines. If you really want to use boost, I can add a function to DetectionComponentUtils that calls boost::trim.

---

*[cpp/DarknetDetection/DarknetDetection.cpp, line 72 at r1](https://beta.reviewable.io/reviews/openmpf/openmpf-components/55#-L8pMxKL2UNizN_T5zcK:-L8rrSsL47RqbTYH0Q6k:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/8d492b243a4f27b7ec68a390b220898985c20bc1/cpp/DarknetDetection/DarknetDetection.cpp#L72)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Currently, if the whitelist file is empty, UNRECOGNIZED_DETECTION_ERROR shows up in the output JSON. For errors related to the whitelist, consider using the following:

MPF_COULD_NOT_OPEN_DATAFILE (cannot open file)
MPF_COULD_NOT_READ_DATAFILE (content is invalid)
</blockquote></details>

Done.

---

*[cpp/DarknetDetection/DarknetDetection.cpp, line 102 at r1](https://beta.reviewable.io/reviews/openmpf/openmpf-components/55#-L8p6aoD6c3OogVowJA-:-L8rrUat7dk-rP3FeZYs:b1ktzkm) ([raw file](https://github.com/openmpf/openmpf-components/blob/8d492b243a4f27b7ec68a390b220898985c20bc1/cpp/DarknetDetection/DarknetDetection.cpp#L102)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Are you using erase here to speed up the search on the next loop iteration, or is there another reason?
</blockquote></details>

There was no reason. It's a hash table so the size doesn't matter. 

---

*[cpp/DarknetDetection/DarknetDetection.cpp, line 448 at r1](https://beta.reviewable.io/reviews/openmpf/openmpf-components/55#-L8p80P--um4H7NZVa1V:-L8rrvp10tmq87E_gZR_:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/8d492b243a4f27b7ec68a390b220898985c20bc1/cpp/DarknetDetection/DarknetDetection.cpp#L448)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Do you need to use `CF` here or can we use `ClassFilter`?
</blockquote></details>

Done.

---

*[cpp/DarknetDetection/DarknetDetection.cpp, line 467 at r1](https://beta.reviewable.io/reviews/openmpf/openmpf-components/55#-L8p88p16C09yWA2Hzyb:-L8rrwJyAgi8Y8l3DCpr:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/8d492b243a4f27b7ec68a390b220898985c20bc1/cpp/DarknetDetection/DarknetDetection.cpp#L467)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Do you need to use `CF` here or can we use `ClassFilter`?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/openmpf/openmpf-components/55)*

**Comment by jrobble** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[cpp/DarknetDetection/DarknetDetection.cpp, line 59 at r1](https://beta.reviewable.io/reviews/openmpf/openmpf-components/55#-L8p5atF5KMczAFLqRKg:-L96fJOyEm4a4m4pBTFZ:bku38w3) ([raw file](https://github.com/openmpf/openmpf-components/blob/8d492b243a4f27b7ec68a390b220898985c20bc1/cpp/DarknetDetection/DarknetDetection.cpp#L59)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

I don't want to link and include boost in the component just to save 4 lines. If you really want to use boost, I can add a function to DetectionComponentUtils that calls boost::trim.
</blockquote></details>

Since DetectionComponentUtils already uses Boost for `GetProperty`, I think adding an additional utility function makes sense. I agree; it's not worth linking Boost with the component logic.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/openmpf/openmpf-components/55)*

**Comment by brosenberg42** [comment]
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[cpp/DarknetDetection/DarknetDetection.cpp, line 59 at r1](https://beta.reviewable.io/reviews/openmpf/openmpf-components/55#-L8p5atF5KMczAFLqRKg:-L9Amtro6TyXOz6THpoD:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/8d492b243a4f27b7ec68a390b220898985c20bc1/cpp/DarknetDetection/DarknetDetection.cpp#L59)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Since DetectionComponentUtils already uses Boost for `GetProperty`, I think adding an additional utility function makes sense. I agree; it's not worth linking Boost with the component logic.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/openmpf/openmpf-components/55)*

**Comment by jrobble** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/openmpf/openmpf-components/55)*

**Pull request merged**
