### PR TITLE
Add FRAME_RATE_CAP to descriptors

### PR DESCRIPTION
**Pull request by brosenberg42**
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/64)

### CODE REVIEW

**Comment by jrobble** [comment]
Update Sphinx too.

---

Reviewed 6 of 6 files at r1.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/64#-:-LF5JFvZAJgpQxsgMF_P:b-p1q3uo)*

**Comment by brosenberg42** [comment]
For Sphinx, I understand that you want to change MPF properties file to OpenMPF properties file. Currently the Sphinx descriptor has a FRAME_INTERVAL property. Should that even be there?

---

Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/64#-:-LFHj_zD7yBAEEk9MZDt:b3p3uqi)*

**Comment by jrobble** [comment]
Here are the current Sphinx properties:

1. FRAME_INTERVAL
2. CONFIDENCE_THRESHOLD
3. MIN_GAP_BETWEEN_SEGMENTS
4. TARGET_SEGMENT_LENGTH
5. MIN_SEGMENT_LENGTH
6. MERGE_TRACKS
7. MIN_GAP_BETWEEN_TRACKS
8. MIN_TRACK_LENGTH
9. MIN_OVERLAP

Regarding how these are used by the WFM:

1 is used to create a TrackMergingPlan, but that field getter is never used. Also, it is used to create a SegmentingPlan, but that field getter is never used. For all intents and purposes, it seems that FRAME_INTERVAL is not used by the WFM for anything; however, at one time we had considered using it to create segments that start/stop on frame intervals.

2 applies to all media types. It's used to filter out detections with low confidence.

3-5 are used by the DetectionSplitter to create a SegmentingPlan, which is only done for VIDEO. However, Sphinx can process video, so technically, in that case, multiple Sphinx jobs are created for a single piece of video media.

6-9 are used by the TrackMergingProcessor, which the DetectionResponseRouteBuilder applies to every detection response. It really only makes sense for videos, so it should probably be disabled for Sphinx tracks.

To answer your question, Sphinx can process videos, and the FRAME_INTERVAL is part of the TrackMergingPlan and SegmentingPlan (even though it isn't currently used for anything, we might eventually use it for segmenting). That said, let's include FRAME_INTERVAL and FRAME_RATE_CAP for Sphinx. If Sphinx was only processing audio files, then it would be a different story.

While you're at it, please set MERGE_TRACKS to FALSE in the Sphinx descriptor file (it currently uses the system property). Also, remove "Default value is defined by the MPF properties file" from the description.

---







*Comments from [Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/64#-:-LFHl_xZ5jN0PjM572u2:b-x6m6r8)*

**Comment by jrobble** [comment]
Reviewed 1 of 1 files at r2.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/64)*

**Pull request merged**
