### PR TITLE
Add Azure OCR component

### PR DESCRIPTION
**Pull request by brosenberg42**
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/146)

### CODE REVIEW

**Comment by brosenberg42** [comment]
___
*[python/AzureOcr/tests/data/NOTICE, line 25 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/146#-M5S7zEHCIz_WYe54jyZ:-M5SAACMAIeYSUXBq8ZJ:b-r84edk) ([raw file](https://github.com/openmpf/openmpf-components/blob/851835423ad02006e7b42ad92ce2a62ab8137e45/python/AzureOcr/tests/data/NOTICE#L25)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Love those scribbles.
</blockquote></details>

It is surprisingly difficult to get ACS to report multiple regions with short text.

**Comment by jrobble** [comment]
___
*[python/AzureOcr/Dockerfile, line 36 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/146#-M5SAR_R2LC82qgJ7M83:-M5SAR_SBey7b4ME085T:bxiwliq) ([raw file](https://github.com/openmpf/openmpf-components/blob/851835423ad02006e7b42ad92ce2a62ab8137e45/python/AzureOcr/Dockerfile#L36)):*
> ```Dockerfile
> COPY . /home/mpf/component_src/
> 
> RUN /home/mpf/scripts/install-component.sh
> ```

Are you waiting to land this to develop before adding the lines to run the unit tests? How are we going to make that work if a license is required?

**Comment by brosenberg42** [comment]
___
*[python/AzureOcr/plugin-files/descriptor/descriptor.json, line 24 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/146#-M5SbVWdCdvppIBjv83f:-M5X1DT697WTRScZVGax:b-5qwggs) ([raw file](https://github.com/openmpf/openmpf-components/blob/033cebb8e2728c0fe43468e473890a6451ce2e31/python/AzureOcr/plugin-files/descriptor/descriptor.json#L24)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Please mention that only v1.0 has been tested.
</blockquote></details>

It works with v1.0, v2.0, and v2.1. 3.0 is in preview and doesn't have an OCR endpoint.

**Comment by jrobble** [comment]
___
*[python/AzureOcrTextDetection/acs_ocr_component/text-tags.json, line 2 at r6](https://reviewable.io/reviews/openmpf/openmpf-components/146#-M62q5sI4Kw8lZNkcxNu:-M6DUirh0t3WL9N0lvTq:b5waogu) ([raw file](https://github.com/openmpf/openmpf-components/blob/ff545b2f92d6ecaea5dc6d498352a199356fc2dc/python/AzureOcrTextDetection/acs_ocr_component/text-tags.json#L2)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

I'll leave this to your discretion based on your conversations with the end user.
</blockquote></details>

To be clear, I'm referring to: "Minimally, please mention in your README how a user would specify search phrases that can tolerate newlines and whitespace. Mention the right operators to use."

**Comment by jrobble** [comment]
___
*[python/AzureOcrTextDetection/README.md, line 16 at r9](https://reviewable.io/reviews/openmpf/openmpf-components/146#-M6GkfOo3q7b5dBGh6cb:-M6H2yFgCndtOY3wl4Gx:b-g9gzjd) ([raw file](https://github.com/openmpf/openmpf-components/blob/6fe0547b1a0c41ff494fb324920014f9b1d0de68/python/AzureOcrTextDetection/README.md#L16)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Use backticks: `text-tags.json`. Tesseract has a `config` folder. I don't see one in your component.
</blockquote></details>

FYI, I would have just approved your PR if it was just the other stylistic comments.

**Pull request merged**
