### PR TITLE
feature/cli-runner - Update component logging

### PR DESCRIPTION
**Pull request by brosenberg42**
Issue: https://github.com/openmpf/openmpf/issues/1003
Associated PRs:
- https://github.com/openmpf/openmpf/pull/1168
- https://github.com/openmpf/openmpf-components/pull/183
- https://github.com/openmpf/openmpf-contrib-components/pull/64
- https://github.com/openmpf/openmpf-docker/pull/118
- https://github.com/openmpf/openmpf-cpp-component-sdk/pull/90
- https://github.com/openmpf/openmpf-python-component-sdk/pull/27
- https://github.com/openmpf/openmpf.github.io/pull/120

This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/183)

### CODE REVIEW

**Review by jrobble — CHANGES_REQUESTED** [review]
> Reviewed 31 of 31 files at r1, 40 of 40 files at r2.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/183)* status: all files reviewed, 3 unresolved discussions (waiting on @brosenberg42)

___
*[cpp/OcvFaceDetection/test/test_ocv_face_detection.cpp, line 77 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/183#-MQrNsmqDBqVUu3Zv7c9:-MQrNsmr2XP1opun-NPm:b-rm3u37) ([raw file](https://github.com/openmpf/openmpf-components/blob/25e3ebe47b3dcc6a0c4fad40aff4eb2f7b55f97a/cpp/OcvFaceDetection/test/test_ocv_face_detection.cpp#L77)):*
> ```cpp
>     return true;
> }
> bool logging_initialized = init_logging();
> ```

Is this necessary? Should we be adding basic logging to all of the C++ component unit tests?
___
*[cpp/TesseractOCRTextDetection/TesseractOCRTextDetection.cpp, line 114 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/183#-MQrPDmiEM8xVi7FwAnt:-MQrPDmiEM8xVi7FwAnu:bb4uonb) ([raw file](https://github.com/openmpf/openmpf-components/blob/373cc62fa96a7c345a2813400b6634b6d88b8fd1/cpp/TesseractOCRTextDetection/TesseractOCRTextDetection.cpp#L114)):*
> ```cpp
>     string plugin_path = run_dir + "/TesseractOCRTextDetection";
>     string config_path = plugin_path + "/config";
>     cout << "looking for logger at " << plugin_path + "/config/Log4cxxConfig.xml" << endl;
> ```

The following files should be removed:

```
./openmpf-components/cpp/TesseractOCRTextDetection/plugin-files/config/Log4cxxConfig.xml
./openmpf-components/cpp/TrtisDetection/plugin-files/config/Log4cxxConfig.xml
```
___
*[python/AzureOcrTextDetection/tests/test_acs.py, line 64 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/183#-MQrR67c8346Crb8b2sD:-MQrR67c8346Crb8b2sE:b-bq52gw) ([raw file](https://github.com/openmpf/openmpf-components/blob/25e3ebe47b3dcc6a0c4fad40aff4eb2f7b55f97a/python/AzureOcrTextDetection/tests/test_acs.py#L64)):*
> ```Python
>     @classmethod
>     def setUpClass(cls):
>         logging.basicConfig(level=logging.DEBUG)
> ```

Why do we add basic logging to the ACS OCR and EAST unit tests but not ACS Speech unit tests? Should it be added to all the Python component unit tests?

**Review by brosenberg42 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/183)* status: all files reviewed, 3 unresolved discussions (waiting on @brosenberg42 and @jrobble)

___
*[cpp/OcvFaceDetection/test/test_ocv_face_detection.cpp, line 77 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/183#-MQrNsmqDBqVUu3Zv7c9:-MVpiist9nTFR2frSJ4y:bq599hh) ([raw file](https://github.com/openmpf/openmpf-components/blob/25e3ebe47b3dcc6a0c4fad40aff4eb2f7b55f97a/cpp/OcvFaceDetection/test/test_ocv_face_detection.cpp#L77)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Is this necessary? Should we be adding basic logging to all of the C++ component unit tests?
</blockquote></details>

This is an example to make sure there is a way for unit tests to configure their own logging. We were perfectly fine with the unit test output only going to the log file in the past, so I decided it wasn't worth my time to go through and change every component.
___
*[python/AzureOcrTextDetection/tests/test_acs.py, line 64 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/183#-MQrR67c8346Crb8b2sD:-MVpjFFo8yIm-5dCe0wU:b-9wxdq0) ([raw file](https://github.com/openmpf/openmpf-components/blob/25e3ebe47b3dcc6a0c4fad40aff4eb2f7b55f97a/python/AzureOcrTextDetection/tests/test_acs.py#L64)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Why do we add basic logging to the ACS OCR and EAST unit tests but not ACS Speech unit tests? Should it be added to all the Python component unit tests?
</blockquote></details>

I did it in EAST as an example to make sure there is a way for unit tests to configure their own logging. We were perfectly fine with the unit test output only going to the log file in the past, so I decided it wasn't worth my time to go through and change every component. The logging in ACS OCR is an example of how I expect it to be added in the future. If a component developer wants to add logging, they can do it when they find it necessary.

**Review by jrobble — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/183)* status: all files reviewed, 1 unresolved discussion (waiting on @brosenberg42)

___
*[cpp/OcvFaceDetection/test/test_ocv_face_detection.cpp, line 77 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/183#-MQrNsmqDBqVUu3Zv7c9:-MVrFFHMD6DrhJbCuRFQ:b-1a4h9m) ([raw file](https://github.com/openmpf/openmpf-components/blob/25e3ebe47b3dcc6a0c4fad40aff4eb2f7b55f97a/cpp/OcvFaceDetection/test/test_ocv_face_detection.cpp#L77)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

This is an example to make sure there is a way for unit tests to configure their own logging. We were perfectly fine with the unit test output only going to the log file in the past, so I decided it wasn't worth my time to go through and change every component.
</blockquote></details>

I'm fine with that. Just making sure we're not missing anything. We can always add it to the unit tests later if necessary.

**Review by brosenberg42 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/183)* status: 42 of 50 files reviewed, 1 unresolved discussion (waiting on @brosenberg42 and @jrobble)

___
*[cpp/TesseractOCRTextDetection/TesseractOCRTextDetection.cpp, line 114 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/183#-MQrPDmiEM8xVi7FwAnt:-MWdsPt59-9tWHovYJ06:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/373cc62fa96a7c345a2813400b6634b6d88b8fd1/cpp/TesseractOCRTextDetection/TesseractOCRTextDetection.cpp#L114)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

The following files should be removed:

```
./openmpf-components/cpp/TesseractOCRTextDetection/plugin-files/config/Log4cxxConfig.xml
./openmpf-components/cpp/TrtisDetection/plugin-files/config/Log4cxxConfig.xml
```
</blockquote></details>

Done.

**Review by jrobble — APPROVED** [review]
> Reviewed 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/183)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @brosenberg42)

**Pull request merged**
