### PR TITLE
TEMPORARY_PADDING_X and TEMPORARY_PADDING_Y

### PR DESCRIPTION
**Pull request by cdglasz**
Perform padding on x- and y-axes separately, to allow for easier handling of tabular images

---
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/201)

### CODE REVIEW

**Review by jrobble — CHANGES_REQUESTED** [review]
If the user needs this as a 5.0 hotfix, please create a PR to land the changes to the master branch first.

> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/201#-:-MKrcxUiCSuozC2-CY-b:b-6sf1a8)* status: all files reviewed, 3 unresolved discussions (waiting on @cdglasz)

___
*[python/EastTextDetection/east_component/east_processor.py, line 213 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/201#-MKri30i9P98Y8xn7Ap2:-MKri30j4VBouopxvB1h:b-y04rah) ([raw file](https://github.com/openmpf/openmpf-components/blob/d5be86a68d2ef99a2bafe156cf6191eb54adf6fa/python/EastTextDetection/east_component/east_processor.py#L213)):*
> ```Python
>                 width of bounding boxes during non-maximum suppression or
>                 merging. The right and left side of bounding boxes are both
>                 extended by 0.5 * temp_padding_x * box_height.
> ```

Is this "0.5" part accurate? You removed it from the `process_frames()` comment.
___
*[python/EastTextDetection/tests/test_east.py, line 225 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/201#-MKreNDi2R2Yvkkg4qjA:-MKreNDi2R2Yvkkg4qjB:b-txzfbl) ([raw file](https://github.com/openmpf/openmpf-components/blob/d5be86a68d2ef99a2bafe156cf6191eb54adf6fa/python/EastTextDetection/tests/test_east.py#L225)):*
> ```Python
>         )
>         detections = list(comp.get_detections_from_image(job))
>         low_padding_x_area = sum(d.width * d.height for d in detections)
> ```

`low_padding_x_area` is never used.
___
*[python/EastTextDetection/tests/test_east.py, line 242 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/201#-MKreQbb8DXr5J6ht5i3:-MKreQbb8DXr5J6ht5i4:b7dq0cu) ([raw file](https://github.com/openmpf/openmpf-components/blob/d5be86a68d2ef99a2bafe156cf6191eb54adf6fa/python/EastTextDetection/tests/test_east.py#L242)):*
> ```Python
>         )
>         detections = list(comp.get_detections_from_image(job))
>         low_padding_y_area = sum(d.width * d.height for d in detections)
> ```

`low_padding_y_area` is never used.

**Review by cdglasz — COMMENTED** [review]
Asked the user beforehand, they indicated a regular PR is fine

> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/201#-:-MKtsXASDT_imbTbmVuA:baoybdz)* status: all files reviewed, 3 unresolved discussions (waiting on @cdglasz)

**Review by cdglasz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/201)* status: 5 of 7 files reviewed, 3 unresolved discussions (waiting on @jrobble)

___
*[python/EastTextDetection/east_component/east_processor.py, line 213 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/201#-MKri30i9P98Y8xn7Ap2:-MKu-knd2PmtrqITo7p1:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/d5be86a68d2ef99a2bafe156cf6191eb54adf6fa/python/EastTextDetection/east_component/east_processor.py#L213)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Is this "0.5" part accurate? You removed it from the `process_frames()` comment.
</blockquote></details>

Done.
___
*[python/EastTextDetection/tests/test_east.py, line 225 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/201#-MKreNDi2R2Yvkkg4qjA:-MKu-lPsEKwiyMaSjMLq:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/d5be86a68d2ef99a2bafe156cf6191eb54adf6fa/python/EastTextDetection/tests/test_east.py#L225)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

`low_padding_x_area` is never used.
</blockquote></details>

Done.
___
*[python/EastTextDetection/tests/test_east.py, line 242 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/201#-MKreQbb8DXr5J6ht5i3:-MKu-liw7XQFZWf8k2f9:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/d5be86a68d2ef99a2bafe156cf6191eb54adf6fa/python/EastTextDetection/tests/test_east.py#L242)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

`low_padding_y_area` is never used.
</blockquote></details>

Done.

**Review by jrobble — APPROVED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/201)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
