### PR TITLE
Update TikaImageDetection component to extract images from document (*.doc, *.docx) and PowerPoint (*.ppt, *.pptx) files.

### PR DESCRIPTION
**Pull request by hhuangMITRE**
**Issues:**

- https://github.com/openmpf/openmpf/issues/1372

---
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/274)

### CODE REVIEW

**Review by jrobble — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/274)* status: all files reviewed, 4 unresolved discussions (waiting on @hhuangMITRE)

___
*[java/TikaImageDetection/src/main/java/org/mitre/mpf/detection/tika/EmbeddedContentExtractor.java, line 139 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/274#-MgLsnL87NuB2t8r_dO3:-MgLsnL87NuB2t8r_dO4:b-vw9npr) ([raw file](https://github.com/openmpf/openmpf-components/blob/fd1705b7201085ebffff8f15167216ec35088e98/java/TikaImageDetection/src/main/java/org/mitre/mpf/detection/tika/EmbeddedContentExtractor.java#L139)):*
> ```Java
>             imageMap.add(current);
>             if (separatePages) {
>                 outputDir = Paths.get(path + "/tika-extracted/page-" + String.valueOf(pageNum + 1));
> ```

This might be an old bug since I didn't test it in your last PR. If I update `testGetDetectionsPdf()` to use `ORGANIZE_BY_PAGE=TRUE`, I see the following structure:

```
`-- TestRun
    `-- tika-extracted
        |-- a39c7392-3c08-4bef-8ac5-3c74378223a5
        |   `-- common
        |       |-- image0.jpg
        |       `-- image1.jpg
        `-- page-6
            |-- image2.jpg
            `-- image3.png
```

`page-6` needs to be under the UUID directory.
___
*[java/TikaImageDetection/src/test/java/org/mitre/mpf/detection/tika/TestTikaImageDetectionComponent.java, line 209 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/274#-MgM-bGbC_2I6hNWd-b7:-MgM-bGbC_2I6hNWd-b8:b6z2f3) ([raw file](https://github.com/openmpf/openmpf-components/blob/fd1705b7201085ebffff8f15167216ec35088e98/java/TikaImageDetection/src/test/java/org/mitre/mpf/detection/tika/TestTikaImageDetectionComponent.java#L209)):*
> ```Java
>         testTrack = tracks.get(3);
>         assertEquals("4", testTrack.getDetectionProperties().get("PAGE_NUM"));
>         assertTrue(testTrack.getDetectionProperties().get("SAVED_IMAGES").contains("image0.emf"));
> ```

Looking at the pptx, I see that there are 3 large flowers, but only two of the extracted files are large flowers. One is a .eml file, and one is a .jpeg file. I assume that one of those images is used twice, but I have no idea which one.

For clarity, please use a different image in the pptx file to test out different image formats.
___
*[java/TikaImageDetection/src/test/java/org/mitre/mpf/detection/tika/TestTikaImageDetectionComponent.java, line 249 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/274#-MgLxWhrCpx3M6p1V8ZX:-MgLxWhrCpx3M6p1V8ZY:b-x8ztf9) ([raw file](https://github.com/openmpf/openmpf-components/blob/fd1705b7201085ebffff8f15167216ec35088e98/java/TikaImageDetection/src/test/java/org/mitre/mpf/detection/tika/TestTikaImageDetectionComponent.java#L249)):*
> ```Java
> 
>         // Test extraction of images from *.docx format.
>         // Six extracted images should be present in one track:
> ```

Do you mean "eight" extracted images?

When I look at the 8 images extracted, I see:

- 3 for the large flower
- 3 for the pink flowers
- 1 for the mountain
- 1 for the flower drawing
 
However, that's not what's shown in the doc. The doc shows:

- 4 for the large flower
- 2 for the pink flowers
- 1 for the mountain
- 1 for the flower drawing

Do you know why? It's a bit confusing.
___
*[java/TikaImageDetection/src/test/resources/data/NOTICE, line 35 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/274#-MgLq8818P8SfmmWhHgg:-MgLq8818P8SfmmWhHgh:bcom6sf) ([raw file](https://github.com/openmpf/openmpf-components/blob/fd1705b7201085ebffff8f15167216ec35088e98/java/TikaImageDetection/src/test/resources/data/NOTICE#L35)):*
> ```
>     Public Domain
> 
> # test-tika-image-extraction.pdf
> ```

Is this supposed to be `test-tika-image-extraction.doc` ?

That file also contains:

```
    # bloom-blossom-flora-40797.jpg
    https://www.pexels.com/photo/nature-flowers-blue-summer-40797/
    Public Domain
```

**Comment by jrobble** [comment]
___
*[java/TikaImageDetection/src/test/java/org/mitre/mpf/detection/tika/TestTikaImageDetectionComponent.java, line 249 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/274#-MgLxWhrCpx3M6p1V8ZX:-MgM3nGP-8vU9WifCD6G:b-kfumpm) ([raw file](https://github.com/openmpf/openmpf-components/blob/fd1705b7201085ebffff8f15167216ec35088e98/java/TikaImageDetection/src/test/java/org/mitre/mpf/detection/tika/TestTikaImageDetectionComponent.java#L249)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Do you mean "eight" extracted images?

When I look at the 8 images extracted, I see:

- 3 for the large flower
- 3 for the pink flowers
- 1 for the mountain
- 1 for the flower drawing
 
However, that's not what's shown in the doc. The doc shows:

- 4 for the large flower
- 2 for the pink flowers
- 1 for the mountain
- 1 for the flower drawing

Do you know why? It's a bit confusing.
</blockquote></details>

Also, more generally, can we avoid extracting the same image file more than once?

**Review by hhuangMITRE — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/274)* status: 2 of 8 files reviewed, 4 unresolved discussions (waiting on @jrobble)

___
*[java/TikaImageDetection/src/main/java/org/mitre/mpf/detection/tika/EmbeddedContentExtractor.java, line 139 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/274#-MgLsnL87NuB2t8r_dO3:-MgyPCUs09sIG7ditPIH:b-qvhnp1) ([raw file](https://github.com/openmpf/openmpf-components/blob/fd1705b7201085ebffff8f15167216ec35088e98/java/TikaImageDetection/src/main/java/org/mitre/mpf/detection/tika/EmbeddedContentExtractor.java#L139)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

This might be an old bug since I didn't test it in your last PR. If I update `testGetDetectionsPdf()` to use `ORGANIZE_BY_PAGE=TRUE`, I see the following structure:

```
`-- TestRun
    `-- tika-extracted
        |-- a39c7392-3c08-4bef-8ac5-3c74378223a5
        |   `-- common
        |       |-- image0.jpg
        |       `-- image1.jpg
        `-- page-6
            |-- image2.jpg
            `-- image3.png
```

`page-6` needs to be under the UUID directory.
</blockquote></details>

Fixed, thanks for catching that. I've updated the outputDir with the `uniqueId` tag.
___
*[java/TikaImageDetection/src/test/java/org/mitre/mpf/detection/tika/TestTikaImageDetectionComponent.java, line 209 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/274#-MgM-bGbC_2I6hNWd-b7:-MgyREzX-Oe6vMcLqX9V:bpgs56b) ([raw file](https://github.com/openmpf/openmpf-components/blob/fd1705b7201085ebffff8f15167216ec35088e98/java/TikaImageDetection/src/test/java/org/mitre/mpf/detection/tika/TestTikaImageDetectionComponent.java#L209)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Looking at the pptx, I see that there are 3 large flowers, but only two of the extracted files are large flowers. One is a .eml file, and one is a .jpeg file. I assume that one of those images is used twice, but I have no idea which one.

For clarity, please use a different image in the pptx file to test out different image formats.
</blockquote></details>

Thanks! I recreated the test documents with more distinct images. Along the way I also tested out more image duplication within the Microsoft documents (ppt/docx). 

Overall, the word document duplication issue appears to have been resolved (see below comment).

PowerPoint document still contains an extra "emf" file, so I'm looking to see if that can be cleaned up but it could be an artifact. When I tested out some other image formatting options, tika sometimes extracted it as a separate embedded file.  
___
*[java/TikaImageDetection/src/test/java/org/mitre/mpf/detection/tika/TestTikaImageDetectionComponent.java, line 249 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/274#-MgLxWhrCpx3M6p1V8ZX:-MgyRy7X-JeNzl8ck5NQ:b-dby9v4) ([raw file](https://github.com/openmpf/openmpf-components/blob/fd1705b7201085ebffff8f15167216ec35088e98/java/TikaImageDetection/src/test/java/org/mitre/mpf/detection/tika/TestTikaImageDetectionComponent.java#L249)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Also, more generally, can we avoid extracting the same image file more than once?
</blockquote></details>

Hey Jeff, so I was examining the `tika-parsers/microsoft` code + testing out more media files.

I think the issue is mainly how duplicate images are created in the word/ppt documents. When I created the new test files (w/ multiple copies of a flower + brick/sphere scene), the duplicate images were only reported once. Perhaps other ways of creating duplicates (copying from sources / copying then resizing/formatting images) will generate unique copies that can't be filtered out by the parsers. 

Looking through the Microsoft parsers right now, I don't see any immediate options for cleaning up embeddings of similar/duplicated images. 

I'll keep looking to see if other options exist, but for now I've resolved the duplicate image extraction issue for our test documents. 
___
*[java/TikaImageDetection/src/test/resources/data/NOTICE, line 35 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/274#-MgLq8818P8SfmmWhHgg:-MgyQwaz8PyLnnzpfTYA:b-ej5jns) ([raw file](https://github.com/openmpf/openmpf-components/blob/fd1705b7201085ebffff8f15167216ec35088e98/java/TikaImageDetection/src/test/resources/data/NOTICE#L35)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Is this supposed to be `test-tika-image-extraction.doc` ?

That file also contains:

```
    # bloom-blossom-flora-40797.jpg
    https://www.pexels.com/photo/nature-flowers-blue-summer-40797/
    Public Domain
```

</blockquote></details>

Fixed, thanks! I've remade the test documents (with more distinct images) and updated the `NOTICE` file.

**Comment by jrobble** [comment]
___
*[java/TikaImageDetection/src/test/java/org/mitre/mpf/detection/tika/TestTikaImageDetectionComponent.java, line 238 at r3](https://reviewable.io/reviews/openmpf/openmpf-components/274#-Mj0Xukx9dZqJ6QYYHaZ:-Mj0Xukx9dZqJ6QYYHa_:bgts4lx) ([raw file](https://github.com/openmpf/openmpf-components/blob/e6e44fb80ac82b5f252e3fcfb5bd4dcc262d70b1/java/TikaImageDetection/src/test/java/org/mitre/mpf/detection/tika/TestTikaImageDetectionComponent.java#L238)):*
Note to self: Make sure this is fixed:

> NPE on `jrobble-test.odp`

**Review by jrobble — COMMENTED** [review]
> Reviewed 3 of 6 files at r2, 6 of 6 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/274)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @hhuangMITRE)

**Pull request closed without merging**
